### PR TITLE
Generate quarterly report and mail it

### PR DESCRIPTION
**Pull request by sserurich**
**_WHAT DOES THIS PR DO?_**
  - [x] This PR contains code for a scheduled job that can be used to automate quarterly reporting by generating analysis, saving it in word doc and emailing the results to selected contacts.
  - [x] #1202 

**_WHAT ISSUES ARE RELATED TO THIS PR?_**

- Jira cards
    - [https://airqoteam.atlassian.net/browse/DP-271](https://airqoteam.atlassian.net/browse/DP-271)

**_HOW DO I TEST OUT THIS PR?_**
 -  Fetch and checkout this branch to local machine
 -  cd to  analytics/jobs/reports
 -  create .env and get .env variables
 -  create and activate virtual env 
 -  install packages in requirements.txt
 - update .env email sender credentials and enable this setting for the email used
 - [https://www.google.com/settings/security/lesssecureapps](https://www.google.com/settings/security/lesssecureapps)
 -  run python main.py

**_WHICH ENDPOINTS SHOULD BE READY FOR TESTING?:_** 
N/A
**_IS THERE ANY JENKINS CONSOLE LINK FOR CODE COVERAGE AND BUILD INFO?_**
N/A
**_ARE THERE ANY RELATED PRs?_**
- #1202

### CODE REVIEW

**Review by 123MwanjeMike — COMMENTED** [review]
Hi @sserurich 
The PR deploy preview is failing because of a very long PR name(>63 characters).
Renaming it to something shorter should address the issue and spin up a preview environment

**Comment by wabinyai** [comment]
I am getting this eror

    from google.cloud import storage
ModuleNotFoundError: No module named 'google.cloud'

**Review by wabinyai — COMMENTED** [review]
Looks good

**Review by wabinyai — APPROVED** [review]

**Comment by uman95** [comment]
@sserurich Could you please look into this to address the error.

**Comment by 123MwanjeMike** [comment]
This is a parent PR to #1202

**Review by 123MwanjeMike — APPROVED** [review]

**Pull request merged**
