### PR TITLE
Enhancements to KYA

### PR DESCRIPTION
**Pull request by BenjaminSsempala**
**_WHAT DOES THIS PR DO?_**
- Enhancements to the Kya Endpoint for utilization in the mobile App.

**_WHAT ISSUES ARE RELATED TO THIS PR?_**

- Jira cards
    - []()
- GitHub issues
    - Closes #<enter GitHub issue number here>

**_HOW DO I TEST OUT THIS PR?_**

**_WHICH ENDPOINTS SHOULD BE READY FOR TESTING?:_** 

**_IS THERE ANY JENKINS CONSOLE LINK FOR CODE COVERAGE AND BUILD INFO?_**

**_ARE THERE ANY RELATED PRs?_**

### CODE REVIEW

**Review by Baalmart — APPROVED** [review]
Thanks @BenjaminSsempala

**Review by Baalmart — CHANGES_REQUESTED** [review]
@BenjaminSsempala , please crosscheck as to why we have a package.lock file changed yet we do not have changes in the package.json

**Comment by BenjaminSsempala** [comment]
> @BenjaminSsempala , please crosscheck as to why we have a package.lock file changed yet we do not have changes in the package.json

Hey @Baalmart 
I think the reason for this was that I did an npm install and I'm seeing some fields in the node modules changed. One example is as seen below.
image

**Comment by Baalmart** [comment]
> > @BenjaminSsempala , please crosscheck as to why we have a package.lock file changed yet we do not have changes in the package.json
> 
> Hey @Baalmart I think the reason for this was that I did an npm install and I'm seeing some fields in the node modules changed. One example is as seen below. Should i revert these package.lock file changes? image

Yes, it is usually advisable to revert or "ignore" the package.lock changes in cases where no new module was introduced. It is just a safe guard from introducing "invisible" problems @BenjaminSsempala

**Comment by BenjaminSsempala** [comment]
> > > @BenjaminSsempala , please crosscheck as to why we have a package.lock file changed yet we do not have changes in the package.json
> > 
> > 
> > Hey @Baalmart I think the reason for this was that I did an npm install and I'm seeing some fields in the node modules changed. One example is as seen below. Should i revert these package.lock file changes? image
> 
> Yes, it is usually advisable to revert or "ignore" the package.lock changes in cases where no new module was introduced. It is just a safe guard from introducing "invisible" problems @BenjaminSsempala

@Baalmart I tried reverting changes for the package.lock in vain. 
I've  raised a new PR excluding the package.lock changes.
https://github.com/airqo-platform/AirQo-api/pull/1886/files

**Pull request closed without merging**
