### PR TITLE
[Analytics] Fix flask dependencies

### PR DESCRIPTION
**Pull request by ja-odur**
**_WHAT DOES THIS PR DO?_**
- Fix flask dependencies

### CODE REVIEW

**Review by 123MwanjeMike — COMMENTED** [review]
Thanks @ja-odur 
However, the deploy preview is failing because of the error below, do you think it may be something of concern?
image
`2022-07-26T18:15:19.218619Z
Traceback (most recent call last): File "/usr/local/bin/flask", line 8, in <module> sys.exit(main()) File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 995, in main cli.main(args=sys.argv[1:]) File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 601, in main return super().main(*args, **kwargs) File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1055, in main rv = self.invoke(ctx) File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1657, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1404, in invoke return ctx.invoke(self.callback, **ctx.params) File "/usr/local/lib/python3.7/site-packages/click/core.py", line 760, in invoke return __callback(*args, **kwargs) File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 84, in new_func return ctx.invoke(f, obj, *args, **kwargs) File "/usr/local/lib/python3.7/site-packages/click/core.py", line 760, in invoke return __callback(*args, **kwargs) File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 850, in run_command app = DispatchingApp(info.load_app, use_eager_loading=eager_loading) File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 325, in __init__ self._load_unlocked() File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 351, in _load_unlocked self._app = rv = self.loader() File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 407, in load_app app = locate_app(self, import_name, name) File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 260, in locate_app __import__(module_name) File "/app/manage.py", line 9, in <module> from main import create_app, rest_api File "/app/main.py", line 19, in <module> from config import BASE_URL, CONFIGURATIONS File "/app/config.py", line 58, in <module> class ProductionConfig(Config): File "/app/config.py", line 64, in ProductionConfig BIGQUERY_MOBILE_EVENTS = env_var("BIGQUERY_MOBILE_EVENTS_PROD") File "/usr/local/lib/python3.7/site-packages/decouple.py", line 243, in __call__ return self.config(*args, **kwargs) File "/usr/local/lib/python3.7/site-packages/decouple.py", line 105, in __call__ return self.get(*args, **kwargs) File "/usr/local/lib/python3.7/site-packages/decouple.py", line 90, in get raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option)) decouple.UndefinedValueError: BIGQUERY_MOBILE_EVENTS_PROD not found. Declare it as envvar or define a default value.`

**Comment by ja-odur** [comment]
> Thanks @ja-odur However, the deploy preview is failing because of the error below, do you think it may be something of concern? image `2022-07-26T18:15:19.218619Z Traceback (most recent call last): File "/usr/local/bin/flask", line 8, in <module> sys.exit(main()) File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 995, in main cli.main(args=sys.argv[1:]) File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 601, in main return super().main(*args, **kwargs) File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1055, in main rv = self.invoke(ctx) File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1657, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1404, in invoke return ctx.invoke(self.callback, **ctx.params) File "/usr/local/lib/python3.7/site-packages/click/core.py", line 760, in invoke return __callback(*args, **kwargs) File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 84, in new_func return ctx.invoke(f, obj, *args, **kwargs) File "/usr/local/lib/python3.7/site-packages/click/core.py", line 760, in invoke return __callback(*args, **kwargs) File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 850, in run_command app = DispatchingApp(info.load_app, use_eager_loading=eager_loading) File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 325, in __init__ self._load_unlocked() File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 351, in _load_unlocked self._app = rv = self.loader() File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 407, in load_app app = locate_app(self, import_name, name) File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 260, in locate_app __import__(module_name) File "/app/manage.py", line 9, in <module> from main import create_app, rest_api File "/app/main.py", line 19, in <module> from config import BASE_URL, CONFIGURATIONS File "/app/config.py", line 58, in <module> class ProductionConfig(Config): File "/app/config.py", line 64, in ProductionConfig BIGQUERY_MOBILE_EVENTS = env_var("BIGQUERY_MOBILE_EVENTS_PROD") File "/usr/local/lib/python3.7/site-packages/decouple.py", line 243, in __call__ return self.config(*args, **kwargs) File "/usr/local/lib/python3.7/site-packages/decouple.py", line 105, in __call__ return self.get(*args, **kwargs) File "/usr/local/lib/python3.7/site-packages/decouple.py", line 90, in get raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option)) decouple.UndefinedValueError: BIGQUERY_MOBILE_EVENTS_PROD not found. Declare it as envvar or define a default value.`

These are missing environment variables. You might want to cross-check with @NoahNsimbe .

**Comment by 123MwanjeMike** [comment]
> These are missing environment variables. You might want to cross-check with @NoahNsimbe .
Thanks @ja-odur.
I've gotten them.
Although I think we can avoid having production secrets inside staging .env files, and vice versa.
Otherwise, changes have been successfully deployed [here](https://fix-flask-dependencies-analytics-preview-w7kzhvlewq-ew.a.run.app)

**Review by 123MwanjeMike — APPROVED** [review]
LGTM
image

**Review by Baalmart — APPROVED** [review]
LGTM

**Pull request merged**
