### PR TITLE
[hotfix] JSON response for recent feeds

### PR DESCRIPTION
**Pull request by Baalmart**
- **What does this PR do?**

This PR changes the response for recent data from feeds. 
It also addresses the issue of incorrect GPS coordinates. 

- **What JIRA task is related to this PR?**

No link available

- **How do I test out this PR?**

 `cd AirQo-api/src/data-mgt`
Windows: `npm run dev-pc` or `npm run stage-pc`
Mac:  `npm run dev-mac` or` npm run stage-mac`

- **Which end points should be tested?**
**Get most recent device data:** http://localhost:3000/api/v1/data/feeds/recent/{CHANNEL ID}

RESPONSE:
image

More details about this ready endpoint can be found [here](https://docs.google.com/spreadsheets/d/1-NGTDBtTcIi8Fg2UYSWjcK6geKrZdopz5kxRFsCEMPs/edit#gid=897606332)

### CODE REVIEW

**Review by lilly-muyama — COMMENTED** [review]
I get the error below for any channel ID I use:
Capture

**Comment by Baalmart** [comment]
In what environment could you be running this? Just want to reproduce the issue on my end.

> I get the error below for any channel ID I use:
> Capture

**Comment by Baalmart** [comment]
This has been addressed, please crosscheck. It was a runtime error....just like the error message specified.
> I get the error below for any channel ID I use:
> Capture

**Review by lilly-muyama — APPROVED** [review]
Works as expected.

**Review by Priscilla-AL — APPROVED** [review]
Looks good.

**Pull request merged**
