### PR TITLE
Improvements calibration

### PR DESCRIPTION
**Pull request by Priscilla-AL**
# <Feature/Chore/Hotfix/Topic/Bug Title>

**_WHAT DOES THIS PR DO?_**
-Disables the multi-hop approach 
-Adds random forest 

**_WHAT JIRA STORY/TASK IS RELATED TO THIS PR?_**
NA

**_WHAT IS THE LINK TO THE PR BRANCH_**
https://github.com/airqo-platform/AirQo-api/tree/Improvements-calibration

**_HOW DO I TEST OUT THIS PR?_**

cd AirQo-api/src/calibrate
python -m venv [DESTINATION_FOLDER]
[DESTINATION_FOLDER]/Scripts/activate
pip install -r requirements.txt
flask run

**_WHICH ENDPOINTS SHOULD BE READY FOR TESTING?:_** 
[POST]  http://localhost:4001/api/v1/calibrate

Sample request body
{
    "datetime": "2020-07-15 13:00:00",
    "raw_values": [
        {
            "device_id":"aq_01",
            "pm2.5": 44.12	,
            "pm10":54.20,
            "temperature":25.3,
            "humidity":62.0	
        },
        {
            "device_id":"aq_02",
            "pm2.5": 35.42,
            "pm10":41.53,
            "temperature":26.5,
            "humidity":57.0
        },
        {
            "device_id":"aq_03",
            "pm2.5": 36.34,
            "pm10":43.06,
            "temperature":27.0,
            "humidity":56.0
        }
    ]
}
          

**_IS THERE ANY JENKINS CONSOLE LINK FOR CODE COVERAGE AND BUILD INFO?_**
NA

**_ARE THERE ANY RELATED PRs?_**
NA

### CODE REVIEW

**Review by danielogen — APPROVED** [review]
The code runs well with docker but after install `pyarrow` package (see attached). The docker image size is greatly reduced from 3.66GB to 1.93GB.

Screenshot 2021-04-19 at 19 13 24

Screenshot 2021-04-19 at 19 29 48

**Review by Baalmart — COMMENTED** [review]
Not sure what I could be doing wrong but I am currently experiencing some challenges are mentioned below:

- When using flask run, I am getting some runtime error of : `ModuleNotFoundError: No module named 'pymongo'`
- On using Docker, there is no activity, keep on getting: `Error: socket hang up`
- Generally, the downloads/packages associated with the microservice could be taking up a lot of storage space, my PC keeps on complaining about storage whenever I run the requirements installations.

Screenshots:

- image
- image

**Comment by Priscilla-AL** [comment]
> Not sure what I could be doing wrong but I am currently experiencing some challenges are mentioned below:
> 
> * When using flask run, I am getting some runtime error of : `ModuleNotFoundError: No module named 'pymongo'`
> * On using Docker, there is no activity, keep on getting: `Error: socket hang up`
> * Generally, the downloads/packages associated with the microservice could be taking up a lot of storage space, my PC keeps on complaining about storage whenever I run the requirements installations.
> 
> Screenshots:
> 
> * image
> * image

Hi Martin, did you reinstall the packages from the dev.txt. I removed most of the redundant packages

**Review by lilly-muyama — APPROVED** [review]
Maybe we can restrict the calibrated values to a few decimal places.

**Review by NoahNsimbe — APPROVED** [review]

**Pull request merged**
