### PR TITLE
move to production

### PR DESCRIPTION
**Pull request by Baalmart**
**_WHAT DOES THIS PR DO?_**

- [x] https://github.com/airqo-platform/AirQo-api/pull/1418
- [x] https://github.com/airqo-platform/AirQo-api/pull/1422
- [x] https://github.com/airqo-platform/AirQo-api/pull/1417
- [x] https://github.com/airqo-platform/AirQo-api/pull/1421

### CODE REVIEW

**Comment by 123MwanjeMike** [comment]
> Hi @123MwanjeMike , I see many files changed perhaps because of other PRs. Please review and add them to the PR description accordingly.
> 
> Thanks!

Hi @Baalmart 
Those are from https://github.com/airqo-platform/AirQo-api/pull/1417

**Comment by Baalmart** [comment]
Alright, thanks!

**Comment by 123MwanjeMike** [comment]
Converted to draft
Investigating a possible bug
cc @Baalmart

**Comment by 123MwanjeMike** [comment]
> Converted to draft Investigating a possible bug cc @Baalmart

#1422 fixes the identified bug @Baalmart

**Comment by 123MwanjeMike** [comment]
This PR should only be merged after  #1422 has been merged.

**Comment by Baalmart** [comment]
Hi @123MwanjeMike , I have converted this PR to work in progress as we wait for your final approval. Thanks! cc: @BenjaminSsempala

**Comment by 123MwanjeMike** [comment]
> Hi @123MwanjeMike , I have converted this PR to work in progress as we wait for your final approval. Thanks! cc: @BenjaminSsempala

Thanks @Baalmart 
This PR is dependent on https://github.com/airqo-platform/AirQo-api/pull/1422.
Let's only merge it after merging #1422

**Pull request merged**
