### PR TITLE
Adjusting lengthscales and background function

### PR DESCRIPTION
**Pull request by lilly-muyama**
# Updating gp endpoint

**_WHAT DOES THIS PR DO?_**
This PR adjusts the lengthscales of the model, adjust the time interval of the background function and adds an import statement. 

**_WHAT JIRA STORY/TASK IS RELATED TO THIS PR?_**

**_WHAT IS THE LINK TO THE PR BRANCH_**

**_HOW DO I TEST OUT THIS PR?_**
Git clone this repo and run these commands:

1. `cd src/predict`
2. `env\scripts\activate` for Windows or `source  env/bin/activate for MAC OS
3. `pip install -r requirements.txt`
4. `flask run`

**_WHICH ENDPOINTS SHOULD BE READY FOR TESTING?:_** 
 http://127.0.0.1:5000/api/v1/predict/heatmap

**_IS THERE ANY JENKINS CONSOLE LINK FOR CODE COVERAGE AND BUILD INFO?_**

**_ARE THERE ANY RELATED PRs?_**

### CODE REVIEW

**Review by danielogen — APPROVED** [review]
LGTM

**Review by Baalmart — COMMENTED** [review]
Getting a 404 on my machine. @lilly-muyama 

image

**Review by ja-odur — APPROVED** [review]
The endpoint works fine on my end

**Review by Baalmart — APPROVED** [review]
works fine....some extra characters observed by @lilly-muyama in the screenshot of the terminal logs were the problem.

**Pull request merged**
