### PR TITLE
Implementing Email design improvements.

### PR DESCRIPTION
**Pull request by BenjaminSsempala**
**_WHAT DOES THIS PR DO?_**

- [x] Creating General Email Template according to given designs.
- [x] Making updates to all the content and design of all mobile app emails.
- [x] Making updates to the platform verification email.

**_WHAT ISSUES ARE RELATED TO THIS PR?_**

- Jira cards
    - [MOB-213](https://airqoteam.atlassian.net/browse/MOB-213)
- GitHub issues
    - Closes #<enter GitHub issue number here>

**_HOW DO I TEST OUT THIS PR?_**

***_For Mobile account creation and deletion._***
- Checkout this branch and navigate to the `firebase/auth/functions` directory.
- Run` npm init`
- Run `firebase emulators:start`
- You can proceed with the testing.

***_For the rest of the emails_***
- Check the corresponding email content in this [doc](https://docs.google.com/document/d/10h_tos78FC97fEQqUNQCIvPvlPBOncLm8pZ90V4LTWE/edit).

image
image

[MOB-213]: https://airqoteam.atlassian.net/browse/MOB-213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by NoahNsimbe — APPROVED** [review]
LGTM thanks @BenjaminSsempala

**Review by Baalmart — COMMENTED** [review]
Hi @BenjaminSsempala , thanks!
Just seen a new deploy preview (8 minutes ago), are you still working on the PR? New commits? work in progress?

Otherwise, all looks good on my end.

**Comment by BenjaminSsempala** [comment]
> Hi @BenjaminSsempala , thanks! Just seen a new deploy preview (8 minutes ago), are you still working on the PR? New commits? work in progress?
> 
> Otherwise, all looks good on my end.

Thanks @Baalmart , All is good now, Last changes I pushed were minor changes(organisation) made during deployment to firebase functions

**Review by Baalmart — APPROVED** [review]
thanks @BenjaminSsempala

**Pull request merged**
