### PR TITLE
Kcca frequency measurements

### PR DESCRIPTION
**Pull request by NoahNsimbe**
# Kcca meaurements connector

**_WHAT DOES THIS PR DO?_**
Creates a kafka connector to  fetch and store Kcca frequency device measurements on a topic

**_WHAT JIRA STORY/TASK IS RELATED TO THIS PR?_**
[Stream all Kcca frequency measurements (hour and day)](https://airqoteam.atlassian.net/browse/PLAT-632?atlOrigin=eyJpIjoiMTgxNTc1Mjg0NTQ3NDIyN2FkYTQ0NWIxMTdhMjI4YTUiLCJwIjoiaiJ9)

**_WHAT IS THE LINK TO THE PR BRANCH_**
[ft-kcca-frequency-measurements](https://github.com/airqo-platform/AirQo-api/tree/ft-kcca-frequency-measurements)

**_HOW DO I TEST OUT THIS PR?_**
- You must have access to a kubernetes cluster with kafka installed using strimzi
- https://strimzi.io/quickstarts/

 **_Wait for the cluster to be created._**

 **_Wait for the cluster to be created._**

**_WHICH ENDPOINTS SHOULD BE READY FOR TESTING?:_** 
None

**_IS THERE ANY JENKINS CONSOLE LINK FOR CODE COVERAGE AND BUILD INFO?_**
None

**_ARE THERE ANY RELATED PRs?_**
None

### CODE REVIEW

**Review by danielogen — APPROVED** [review]
LGTM

**Review by ja-odur — APPROVED** [review]
LGTM

**Review by Baalmart — COMMENTED** [review]
just a few merge conflicts that need to be resolved. otherwise, all looks good. @NoahNsimbe

**Review by Baalmart — CHANGES_REQUESTED** [review]
These conflicts actually need to be resolved as earlier mentioned. so changing my feedback status.

**Review by Baalmart — APPROVED** [review]
LGTM now

**Pull request merged**
