### PR TITLE
Ft uptime analysis

### PR DESCRIPTION
**Pull request by sserurich**
**What does this PR do?**
 This PR contains endpoint for network uptime
**What JIRA task is related to this PR?**
https://airqoteam.atlassian.net/jira/software/projects/NET/boards/28/backlog?selectedIssue=NET-8
**How do I test out this PR?**
 - git clone this repo cd AirQo-api/src/device-monitoring 
 - git fetch branch ft-uptime-analysis
 - run pip install -r requirements/dev.txt to get all the relevant packages.
 - Afterwards run flask run to test out the end points using any REST client tool available to you.

**Which end points should are ready for testing?**
  https://docs.google.com/spreadsheets/d/1-NGTDBtTcIi8Fg2UYSWjcK6geKrZdopz5kxRFsCEMPs/edit#gid=1063367751
 /api/v1/monitor/network/uptime

### CODE REVIEW

**Comment by sserurich** [comment]
> 1. There are a lot of services in this PR. I am seeing analytics, auth-service, device-monitoring.
> 2. Also, in the first file, cloud_function_update_raw_measurement.py), the MONGO URI is exposed.
> 3. testing.env which shouldn't be in the PR is exposing the environment variables.
 

Mongo URI  being exposed is fixed in this [PR](https://github.com/airqo-platform/AirQo-api/pull/79). So after merging this in master, I can fix this and it will remove the changes from analytics service.
 testing.env  & setting.json from other services have been eliminated. only device-monitoring service is currently available.

**Comment by sserurich** [comment]
> > 1. There are a lot of services in this PR. I am seeing analytics, auth-service, device-monitoring.
> > 2. Also, in the first file, cloud_function_update_raw_measurement.py), the MONGO URI is exposed.
> > 3. testing.env which shouldn't be in the PR is exposing the environment variables.
> 
> Mongo URI being exposed is fixed in this [PR](https://github.com/airqo-platform/AirQo-api/pull/79). So after merging this in master, I can fix this and it will remove the changes from analytics service.
> testing.env & setting.json from other services have been eliminated. only device-monitoring service is currently available.

@lilly-muyama , these issues have been fixed,  have updated this file "cloud_function_update_raw_measurement.py" from analytics here, seems it was missing in the fixes in the PR.

**Comment by lilly-muyama** [comment]
> 
> 
> > > 1. There are a lot of services in this PR. I am seeing analytics, auth-service, device-monitoring.
> > > 2. Also, in the first file, cloud_function_update_raw_measurement.py), the MONGO URI is exposed.
> > > 3. testing.env which shouldn't be in the PR is exposing the environment variables.
> > 
> > 
> > Mongo URI being exposed is fixed in this [PR](https://github.com/airqo-platform/AirQo-api/pull/79). So after merging this in master, I can fix this and it will remove the changes from analytics service.
> > testing.env & setting.json from other services have been eliminated. only device-monitoring service is currently available.
> 
> @lilly-muyama , these issues have been fixed, have updated this file "cloud_function_update_raw_measurement.py" from analytics here, seems it was missing in the fixes in the PR.

@Richard, that first file shouldn't be there (from the analytics micro service) as this is a device-monitoring PR

**Comment by sserurich** [comment]
> There is code for `src/analytics/helpers/cloud_function_update_raw_measurements.py ` in this PR for `device-monitoring` microservice. Could you remove it? @sserurich

@Baalmart , I have removed the file.

**Comment by sserurich** [comment]
> > > > 1. There are a lot of services in this PR. I am seeing analytics, auth-service, device-monitoring.
> > > > 2. Also, in the first file, cloud_function_update_raw_measurement.py), the MONGO URI is exposed.
> > > > 3. testing.env which shouldn't be in the PR is exposing the environment variables.
> > > 
> > > 
> > > Mongo URI being exposed is fixed in this [PR](https://github.com/airqo-platform/AirQo-api/pull/79). So after merging this in master, I can fix this and it will remove the changes from analytics service.
> > > testing.env & setting.json from other services have been eliminated. only device-monitoring service is currently available.
> > 
> > 
> > @lilly-muyama , these issues have been fixed, have updated this file "cloud_function_update_raw_measurement.py" from analytics here, seems it was missing in the fixes in the PR.
> 
> @richard, that first file shouldn't be there (from the analytics micro service) as this is a device-monitoring PR

@lilly-muyama , I have removed that file.

**Pull request merged**
