### PR TITLE
[chore] update base url of device monitoring microservice

### PR DESCRIPTION
**Pull request by danielogen**
# [chore] update base url of device monitoring microservice

**_WHAT DOES THIS PR DO?_**
This endpoint attempt to update the base URL of device monitoring microservice so that it can be easily utilized by the API gateway configuration. The base URL changes to `http://ipaddress:port/api/v1/monitor/.....`.
**_WHAT JIRA STORY/TASK IS RELATED TO THIS PR?_**
[PLAT-99](https://airqoteam.atlassian.net/browse/PLAT-99)

**_WHAT IS THE LINK TO THE PR BRANCH_**
N/A
**_HOW DO I TEST OUT THIS PR?_**
Check out to this branch. Using a REST API client of your choice, test out the endpoints.
**_WHICH ENDPOINTS SHOULD BE READY FOR TESTING?:_** 
All endpoints of device monitoring microservice. Use the following base URL, http://ipaddress:port/api/v1/monitor/...`. E.g `http://localhost:4001/api/v1/monitor/device/status?tenant=airqo`
**_IS THERE ANY JENKINS CONSOLE LINK FOR CODE COVERAGE AND BUILD INFO?_**
N/A
**_ARE THERE ANY RELATED PRs?_**
N/A

### CODE REVIEW

**Comment by danielogen** [comment]
Once the PR is review and accepted, we can update the API documentation accordingly

**Review by lilly-muyama — APPROVED** [review]
LGTM

**Review by ja-odur — APPROVED** [review]
LGTM

**Review by Priscilla-AL — APPROVED** [review]
looks good

**Comment by lilly-muyama** [comment]
@danielogen please merge the latest staging and we merge this PR

**Pull request merged**
