### PR TITLE
Inaccurate GPS sensor reading and no device feeds

### PR DESCRIPTION
**Pull request by Baalmart**
This PR does error handling for cases where a device ID does not have any feeds.
Also handles another edge case (1000.000) of inaccurate GPS sensor values from the device

# Hotfix

Description
This PR does error handling for cases where a device ID does not have any feeds.
Also handles another edge case (1000.000) of inaccurate GPS sensor values from the device

JIRA ID: https://airqoteam.atlassian.net/browse/PLAT-161?atlOrigin=eyJpIjoiYThjMDBjZmYzY2Q3NDAyOGEzOTNkMWE2ZGZkNTk4NDkiLCJwIjoiaiJ9

Unit tests completed?: Y

PR Branch
https://github.com/airqo-platform/AirQo-api/tree/hotfix-gps-data

Procedure
`cd AirQo-api/src/data-mgt`
`npm install`
`npm run prod-pc` (Windows) or` npm run prod-mac` (Linux)

Existing endpoints?: Y
[Get Last Entry] http://localhost:3000/api/v1/data/feeds/recent/#CHANNEL_ID
More details in the [API documentation](https://docs.google.com/spreadsheets/d/1-NGTDBtTcIi8Fg2UYSWjcK6geKrZdopz5kxRFsCEMPs/edit#gid=757070984)

Code Coverage & Build Info
N/A

E2E Approved
N/A

Windows Testing
NO

Related PR
N/A

UX Approved
N/A

### CODE REVIEW

**Review by lilly-muyama — COMMENTED** [review]
I a not getting any response. Not sure what the problem is

**Comment by Baalmart** [comment]
Hi @lilly-muyama :
Please share screenshot.
> I a not getting any response. Not sure what the problem is

**Review by Priscilla-AL — COMMENTED** [review]
Hi Martin, please update the endpoint to reflect a production link since we are running production

"http://localhost:3000/api/v1/data/api/v1/data/feeds/recent/#CHANNEL_ID"

**Comment by Baalmart** [comment]
> Hi @lilly-muyama :
> Please check now....issue was the PR description....

> > I a not getting any response. Not sure what the problem is

**Review by Priscilla-AL — APPROVED** [review]
looks good now

**Review by danielogen — APPROVED** [review]
Looks good

**Pull request merged**
