### PR TITLE
migrating ml-service functionality to predict

### PR DESCRIPTION
**Pull request by sserurich**
**What does this PR do?**
 This PR ensures functionality in ml-service is transferred to the predict project with the latest master changes incorporated.
**How do I test out this PR?**
 - git fetch branch transfer-ml-service-to-predict
 - run pip install -r requirements.txt to get all the relevant packages.
 - Afterwards run flask run to start the backend service 
- Utelise any of any  REST client to test out this endpoint 

 - Alternatively build the docker image using commands below 
    docker build -t airqo-prediction-api  . 
    docker run -d -p 8000:5000 airqo-prediction-api 

**Which end points should are ready for testing?**
   http://127.0.0.1:5000/api/v1/predict/
[https://docs.google.com/spreadsheets/d/1-NGTDBtTcIi8Fg2UYSWjcK6geKrZdopz5kxRFsCEMPs/edit#gid=2008416453](https://docs.google.com/spreadsheets/d/1-NGTDBtTcIi8Fg2UYSWjcK6geKrZdopz5kxRFsCEMPs/edit#gid=2008416453)

**NOTE**

- You must have the `airqo-250220-642e046f4223.json`  file within your root directory.
- Also ensure that you have the required `.env` file in your root directory

### CODE REVIEW

**Comment by sserurich** [comment]
> * Works well without containerisation.
> * We shall need to do some performance improvements by employing some caching or indexing for second attempts using same input data.
> * On containerisation, we get the following server error:
>   image

@Baalmart , there's gcp authentication file which isn't checked into git.. can push that privately to you or incase you any other authentication file to gcp, can replace that.

**Comment by Baalmart** [comment]
> > * Works well without containerisation.
> > * We shall need to do some performance improvements by employing some caching or indexing for second attempts using same input data.
> > * On containerisation, we get the following server error:
> >   image
> 
> @Baalmart , there's gcp authentication file which isn't checked into git.. can push that privately to you or incase you any other authentication file to gcp, can replace that.

Cooll containerised app now works well as expected.

**Comment by danielogen** [comment]
Working very well without docker. I am containerizing now and will share my experience shortly.

**Comment by danielogen** [comment]
> Working very well without docker. I am containerizing now and will share my experience shortly.

Works well with docker too! Thank you.

**Pull request merged**
