### PR TITLE
Api device maintenance

### PR DESCRIPTION
**Pull request by Priscilla-AL**
What does this PR do?
adds isDueMaintainace field to out put
What JIRA task is related to this PR?
https://airqoteam.atlassian.net/jira/software/projects/NET/boards/28?assignee=5d91eed256bb950dd6489270&selectedIssue=NET-5
How do I test out this PR?
Git clone this repo cd AirQo-api/src/device-monitoring  e.t.c

Endpoint: [GET] /api/v1/monitor/devices/online_offline

### CODE REVIEW

**Comment by Priscilla-AL** [comment]
Requested changes made

**Comment by lilly-muyama** [comment]
The isDueMaintenance field is not displaying accurate results. Some devices that are being shown as codeGreen should be codeRed. I tested 3 and they were all inaccurate

**Comment by Priscilla-AL** [comment]
Yes, @lilly-muyama  I am aware. We agreed I would make further changes after you clarify with PO and users. for now its over due and not. Two categories.

**Comment by lilly-muyama** [comment]
> 
> 
> Yes, @lilly-muyama I am aware. We agreed I would make further changes after you clarify with PO and users. for now its over due and not. Two categories.

@Priscilla-AL , my point is most of your devices are green which is not true. Most devices are overdue for maintenance. We can't have a map showing a lot of green nodes yet the top cards are showing the opposite. The endpoint is giving inaccurate results. The clarifications from the PO/users concern the frontend not the endpoint.

**Comment by Priscilla-AL** [comment]
Yes @lilly-muyama, I am aware, as I mentioned its work in progress, but depending on your feedback I may need to change the back end as well or do the logic from the frontend. So the back end may be affected too. 
There is still a lot to be improved, Just thought you show demo the ring whatevers to account for my time.

**Pull request merged**
