### PR TITLE
Airqo meaurements connector

### PR DESCRIPTION
**Pull request by NoahNsimbe**
# Airqo meaurements connector

**_WHAT DOES THIS PR DO?_**
Creates a kafka connector to  fetch and store AirQo device measurements on a topic

**_WHAT JIRA STORY/TASK IS RELATED TO THIS PR?_**
None

**_WHAT IS THE LINK TO THE PR BRANCH_**
[airqo-meaurements-connector](https://github.com/airqo-platform/AirQo-api/tree/airqo-meaurements-connector)

**_HOW DO I TEST OUT THIS PR?_**
- You must have access to a kubernetes cluster with kafka installed using strimzi
- https://strimzi.io/quickstarts/

 **_Wait for the cluster to be created._**

 **_Wait for the cluster to be created._**

**_WHICH ENDPOINTS SHOULD BE READY FOR TESTING?:_** 
None

**_IS THERE ANY JENKINS CONSOLE LINK FOR CODE COVERAGE AND BUILD INFO?_**
None

**_ARE THERE ANY RELATED PRs?_**
None

### CODE REVIEW

**Review by ja-odur — APPROVED** [review]
LGTM

**Review by danielogen — APPROVED** [review]
LGTM

**Review by Baalmart — CHANGES_REQUESTED** [review]
Has some merge conflicts that need resolving. @NoahNsimbe

**Review by Baalmart — APPROVED** [review]
LGTM

**Pull request merged**
