### PR TITLE
return device details alongside the device measurements

### PR DESCRIPTION
**Pull request by Baalmart**
# return device details alongside the device measurements

**_WHAT DOES THIS PR DO?_**
This PR enhances the endpoint for returning the recent device measurements by addling the device details accordingly. In summary, this PR addresses this[ issue-354](https://github.com/airqo-platform/AirQo-api/issues/354)

**_WHAT JIRA STORY/TASK IS RELATED TO THIS PR?_**
N/A

**_WHAT IS THE LINK TO THE PR BRANCH_**
https://github.com/airqo-platform/AirQo-api/tree/issue-354

**_HOW DO I TEST OUT THIS PR?_**
cd AirQo-api/src/device-registry
npm install
npm run stage-mac

**_WHICH ENDPOINTS SHOULD BE READY FOR TESTING?:_** 
The endpoint for the most recent events. You can leave the recent query parameter since the default is always **yes**. You can also use **no** as a value in case you want to just randomly return any values just based on entry age (a rare use-case).
**GET:** http://localhost:3000/api/v1/devices/events?tenant=airqo&recent=yes

image

**_IS THERE ANY JENKINS CONSOLE LINK FOR CODE COVERAGE AND BUILD INFO?_**
N/A

**_ARE THERE ANY RELATED PRs?_**
N/A

### CODE REVIEW

**Review by ja-odur — COMMENTED** [review]
@Baalmart  Running this endpoint `GET http://localhost:3000/api/v1/devices/events?tenant=airqo&recent=true` I dont get any device details.
But ignoring the recent key, I do get device details. This behaviour is quite different from the screenshoot

**Comment by Baalmart** [comment]
> @Baalmart Running this endpoint `GET http://localhost:3000/api/v1/devices/events?tenant=airqo&recent=true` I dont get any device details.
> But ignoring the recent key, I do get device details. This behaviour is quite different from the screenshoot

Hi @ja-odur :
Please take note that the value for the recent parameter is now a string, it is either **yes** or **no** . Example:  http://localhost:3000/api/v1/devices/events?tenant=airqo&recent=yes

The screenshot is misleading, let me update asap.....

**Comment by danielogen** [comment]
> > @Baalmart Running this endpoint `GET http://localhost:3000/api/v1/devices/events?tenant=airqo&recent=true` I dont get any device details.
> > But ignoring the recent key, I do get device details. This behaviour is quite different from the screenshoot
> 
> Hi @ja-odur :
> Please take note that the value for the recent parameter is now a string, it is either **yes** or **no** . Example: http://localhost:3000/api/v1/devices/events?tenant=airqo&recent=yes
> 
> The screenshot is misleading, let me update asap.....

Great, now it's working well. Just wondering why "recent=true" also return data. Could we add some checks?

**Review by danielogen — APPROVED** [review]
Working well as expected

**Comment by ja-odur** [comment]
> > @Baalmart Running this endpoint `GET http://localhost:3000/api/v1/devices/events?tenant=airqo&recent=true` I dont get any device details.
> > But ignoring the recent key, I do get device details. This behaviour is quite different from the screenshoot
> 
> Hi @ja-odur :
> Please take note that the value for the recent parameter is now a string, it is either **yes** or **no** . Example: http://localhost:3000/api/v1/devices/events?tenant=airqo&recent=yes
> 
> The screenshot is misleading, let me update asap.....

Thank you @Baalmart, works as expected

**Review by ja-odur — APPROVED** [review]
LGTM

**Review by Priscilla-AL — COMMENTED** [review]
What does recent mean?
I set it to yes and got data from Apr 28 then set it to no and got data from today

**Comment by Baalmart** [comment]
> What does recent mean?
> I set it to yes and got data from Apr 28 then set it to no and got data from today

Good question @Priscilla-AL , recent means the most recent data for each device. You got recent values which are for Apr 28 because of our issues with ThingSpeak.

As for the "no" option, it just returns values from the database irrespective of whether it is recent or not.

**Comment by Priscilla-AL** [comment]
> > What does recent mean?
> > I set it to yes and got data from Apr 28 then set it to no and got data from today
> 
> Good question @Priscilla-AL , recent means the most recent data for each device. You got recent values which are for Apr 28 because of our issues with ThingSpeak.
> 
> As for the "no" option, it just returns values from the database irrespective of whether it is recent or not.

okay, noted

**Review by Priscilla-AL — APPROVED** [review]

**Review by NoahNsimbe — APPROVED** [review]
LGTM

**Pull request merged**
