### PR TITLE
Enhancements and hotfixes for device registry

### PR DESCRIPTION
**Pull request by Baalmart**
# Enhancements and hotfixes on device-registry

**_WHAT DOES THIS PR DO?_**

- [x] On `api/v2`, automatically adds two fields during the insertion of events (`is_test_data` and `is_device_primary`). 
- [x] On `api/v2`. again for the add Events endpoints, corrects the status codes for cases where duplicate events are entered.
- [x] In both api/v1 and api/v2, one can be able to query events by Site
- [x] On `api/v2`, onquerying hourly data, response should also include all the time details, maintaining  zero values for minute, seconds and milliseconds.
- [x] Ability to query data by list of sites given across all endpoints
- [x] Ensure that no nulls are inserted for site_id and device_id
- [x] Put more input validation for GPS coordinates. Only allow 5 decimal places, nothing more, nothing less. Otherwise, more decimal places are rounded off by the system.
- [ ] Adding caching to the V2 endpoint for fetching Events.
- [x] Carry out quality assurance checks for EDIT and DEPLOY endpoints of device registry

**_WHAT JIRA STORY/TASK IS RELATED TO THIS PR?_**
N/A

**_WHAT IS THE LINK TO THE PR BRANCH_**
https://github.com/airqo-platform/AirQo-api/tree/hotfixes-device-registry

**_HOW DO I TEST OUT THIS PR?_**
Details are in the READMe file of this microservice

**_WHICH ENDPOINTS SHOULD BE READY FOR TESTING?:_** 

- [x] Get Events
GET (v1) http://localhost:3000/api/v1/devices/events?tenant={TENANT}&frequency={FREQUENCY}

> Query parameters that can be comma separated
> 
> - device
> - site
> - device_id
> - site_id

GET (v2) http://localhost:3000/api/v2/devices/events?tenant={TENANT}&frequency={FREQUENCY}
For V2, the frequency options are still the same as for v1.
> Query parameters that can be comma separated
> 
> - device
> - site
> - device_id
> - site_id

- [x] Add Events

POST (V2) http://localhost:3000/api/v2/devices/events?tenant={TENANT}
```
[
    {
        "time": "2021-03-21T03:17:52.207Z",
        "site_id": "70d2b510679018a1a8d38c1f",
        "frequency": "raw",
        "device_id": "60a81f2ac01cec5f7fa5d1bf",
        "altitude": {
            "value": 150.4
        }
    },
...
]
```
POST (V1) http://localhost:3000/api/v1/devices/events?tenant={TENANT}
```
[
    {
        "time": "2021-03-21T03:17:52.207Z",
        "site_id": "70d2b510679018a1a8d38c1f",
        "frequency": "raw",
        "device_id": "60a81f2ac01cec5f7fa5d1bf",
        "altitude": {
            "value": 150.4
        }
    },
...
]
```
- [x] Get Sites
GET  http://localhost:3000/api/v1/devices/sites?tenant={TENANT}&id={SITE_ID}

- [x] Create a Site 
POST (V1 and V2) http://localhost:3000/api/v1/devices/sites?tenant=airqo
```
{
    "latitude": 0.68,   
    "longitude": 32990.34,
    "name": "richard" ,
    "description": "making more checks right now"   
}

```
Check the error responses for that.
**_IS THERE ANY JENKINS CONSOLE LINK FOR CODE COVERAGE AND BUILD INFO?_**
N/S

**_ARE THERE ANY RELATED PRs?_**
N/A

### CODE REVIEW

**Comment by NoahNsimbe** [comment]
@Baalmart, some help...I dont get any sites
error3

**Comment by NoahNsimbe** [comment]
@Baalmart 
error

**Comment by Baalmart** [comment]
> @Baalmart, some help...I dont get any sites
> error3

Okay, thanks for the feedback.
What environment are you running in? @NoahNsimbe

**Comment by NoahNsimbe** [comment]
> > @Baalmart, some help...I dont get any sites
> > error3
> 
> Okay, thanks for the feedback.
> What environment are you running in? @NoahNsimbe

Dev...pointing to stage db

**Comment by NoahNsimbe** [comment]
@Baalmart 
error2

**Comment by Baalmart** [comment]
> @Baalmart
> error

Thanks, I will try to reproduce.....

**Comment by Baalmart** [comment]
> @Baalmart
> error2

Thanks @NoahNsimbe   Some of the responses for the GET events (V1 and V2) might require some more checks at the DB config level because:

- The schemas for V2 and V1 are slight different
- The events being searched for might be missing.
- There is an ongoing "null" issue on `sites, site_id, device_id and device` elements for the GET events (V2)

**Comment by Baalmart** [comment]
> > > @Baalmart, some help...I dont get any sites
> > > error3
> > 
> > 
> > Okay, thanks for the feedback.
> > What environment are you running in? @NoahNsimbe
> 
> Dev...pointing to stage db
@NoahNsimbe , I have failed to reproduce the issue. Also running locally but pointing to staging.
Screenshot 2021-07-29 at 12 47 51

**Review by danielogen — APPROVED** [review]
LGTM

**Pull request merged**
