### PR TITLE
Extract Data endpoints

### PR DESCRIPTION
**Pull request by NoahNsimbe**
**_WHAT DOES THIS PR DO?_**
- [x] Updates the flask version to the latest in order resolve application startup errors

**_HOW DO I TEST OUT THIS PR?_**
Follow instructions in the [readme file](https://github.com/airqo-platform/AirQo-api/tree/extract-data-endpoints-requirements/src/data-mgt/python/extract-external-data#datawarehouse-microservice)

**_WHICH ENDPOINTS SHOULD BE READY FOR TESTING?:_** 
All the extract-data-from-external-sources endpoints found [here](https://app.gitbook.com/o/-MCogOVGQqjUharJKchL/s/-MKqyQkcfs54GYi-q96G/extract-data-from-external-sources)

**_ARE THERE ANY RELATED PRs?_**
#763

### CODE REVIEW

**Review by 123MwanjeMike — APPROVED** [review]
LGTM

**Review by sserurich — COMMENTED** [review]
the change looks good, but still trying to ensure I run it successfully.
This is happening when I use the virtual environment instructions.
image
investigating with docker

**Comment by NoahNsimbe** [comment]
> the change looks good, but still trying to ensure I run it successfully. This is happening when I use the virtual environment instructions. image investigating with docker

Shall revist this @sserurich

**Comment by NoahNsimbe** [comment]
This as resolved cc @sserurich @123MwanjeMike

**Pull request closed without merging**
