### PR TITLE
move to production

### PR DESCRIPTION
**Pull request by Baalmart**
**_WHAT DOES THIS PR DO?_**

- [x] https://github.com/airqo-platform/AirQo-api/pull/1387
- [ ] https://github.com/airqo-platform/AirQo-api/pull/1371
- [ ] https://github.com/airqo-platform/AirQo-api/pull/1386
- [x] https://github.com/airqo-platform/AirQo-api/pull/1390

### CODE REVIEW

**Comment by danielogen** [comment]
LGTM 👍

**Comment by NoahNsimbe** [comment]
@Baalmart @BenjaminSsempala @123MwanjeMike 
[these changes](https://github.com/airqo-platform/AirQo-api/pull/1390/files) need to be merged into Production. Any updates on the this PR??

**Comment by Baalmart** [comment]
Thanks @NoahNsimbe , all looks good to me.  

With the context of the attached screenshots taken from the notifs channel for device-registry,could you also review this PR from @BenjaminSsempala : https://github.com/airqo-platform/AirQo-api/pull/1389#pullrequestreview-1335862506

image

**Comment by NoahNsimbe** [comment]
> Thanks @NoahNsimbe , all looks good to me.
> 
> With the context of the attached screenshots taken from the notifs channel for device-registry,could you also review this PR from @BenjaminSsempala : [#1389 (review)](https://github.com/airqo-platform/AirQo-api/pull/1389#pullrequestreview-1335862506)
> 
> image

Thanks @Baalmart. Benjamin's PR requires me to onboard him on python and airflow. It  might take more time than expected.

**Comment by Baalmart** [comment]
Alright @NoahNsimbe , as you onboard the rest, could we also fix those duplicate Kafka messages? Or are those duplicates intentional by design?

**Comment by Baalmart** [comment]
Otherwise, please go ahead with the merge. @NoahNsimbe I see nothing alarming.

Thanks!

**Comment by NoahNsimbe** [comment]
In this context, the duplicates are not intentional.

**Pull request merged**
