### PR TITLE
[features] device, sensor(component) and location activities

### PR DESCRIPTION
**Pull request by Baalmart**
- What does this PR do?
This PR introduces new endpoints for device registry. That is: `get devices in a Location`, `recall a device`.  At the same time, it updates the responses for some existing endpoints as highlighted further in the PR definition.

- What JIRA task is related to this PR?
No link available

- How do I test out this PR?
Git clone this repo `cd AirQo-api/src/device-registry`
Create a docker image locally: `docker build -t us.gcr.io/airqo-250220/airqo-device-registry-api .`
Afterwards, run the newly created image: `docker run -d -p 5000:3000 us.gcr.io/airqo-250220/airqo-device-registry-api`
Using your REST client, test out all the endpoints for the` device-registry`, use port 5000 as specified above or change to what you would like to use.

**Alternatively.......**
 `cd AirQo-api/src/device-registry`
`npm install`

For MAC users....
`npm run prod-mac` for "production"
`npm run dev-mac` for "development"

For Windows users
`npm run prod-pc` for  "production"
`npm run dev-pc` for  "development"

- Which end points should are ready for testing?
> a) Get All devices 
> b) Get Devices by Location
> c) Create Thing  
> d) Delete Thing
> e) Clear Thing 
> f)  Update Thing
> g) deploy/recall/maintain Thing
> h) List Components (filter results by DeviceName or ComponentName) 
> i) Add One Component
> j) Delete Component
> k) Update/Calibrate Component

more detailed notes about these endpoints can be found inside the `device-registry` sheet of the [API documentation](https://docs.google.com/spreadsheets/d/1-NGTDBtTcIi8Fg2UYSWjcK6geKrZdopz5kxRFsCEMPs/edit#gid=897606332).

- **OPTIONAL for testing:** 
One could also push to the Google Container Registry using `docker push us.gcr.io/airqo-250220/airqo-device-registry-api`

### CODE REVIEW

**Comment by danielogen** [comment]
After creating and deleting a `think`, I can not create that `thing` again :)

**Comment by lilly-muyama** [comment]
And this for activityType=recall
Capture

**Comment by lilly-muyama** [comment]
> 
> 
> After creating and deleting a `think`, I can not create that `thing` again :)

Martin said that deleteThing only deletes from Thingspeak and not the database. So you can't create because the device is till there in the MongoDB. Anywho, we shall not be utilizing this endpoint since according to requirements, a user shouldn't be able to delete a device once created

**Comment by sserurich** [comment]
> Looks good

Reviewing this, approval was meant for another PR which I have addressed.

**Comment by Baalmart** [comment]
> After creating and deleting a `think`, I can not create that `thing` again :)

Yeah...the Thing is not deleted in the local database...it is just deleted from ThingSpeak.

**Comment by danielogen** [comment]
> > After creating and deleting a `think`, I can not create that `thing` again :)
> 
> Martin said that deleteThing only deletes from Thingspeak and not the database. So you can't create because the device is till there in the MongoDB. Anywho, we shall not be utilizing this endpoint since according to requirements, a user shouldn't be able to delete a device once created

OK cool... thanks for the clarification

**Comment by danielogen** [comment]
> > After creating and deleting a `think`, I can not create that `thing` again :)
> 
> Yeah...the Thing is not deleted in the local database...it is just deleted from ThingSpeak.

Alright noted!

**Comment by danielogen** [comment]
> I get this message for any device I try to deploy
> Capture

Same on my side

**Comment by danielogen** [comment]
All the other endpoints are working very well. The only challenge I'm facing is mentioned here https://github.com/airqo-platform/AirQo-api/pull/118#issuecomment-663199123. cc: @Baalmart

**Comment by lilly-muyama** [comment]
> 
> 
> > I get this message for any device I try to deploy
> > Capture
> 
> Same on my side

@danielogen it is supposed to say that if a device has a locationID already. Try deploy a device that doesn't have a locationID. You can use one of those devices I'm going to delete. Let me remove their location IDs

**Comment by danielogen** [comment]
> > > I get this message for any device I try to deploy
> > > Capture
> > 
> > 
> > Same on my side
> 
> @danielogen it is supposed to say that if a device has a locationID already. Try deploy a device that doesn't have a locationID. You can use one of those devices I'm going to delete. Let me remove their location IDs

oh ok...

**Comment by danielogen** [comment]
If we can 2 approvals here, please go on and merge @Baalmart . I can't seem to get around the other challenge I shared on slack. Every other API is work as expected. cc: @lilly-muyama

**Comment by sserurich** [comment]
so far have succeeded with two endpoints Get All Sensors, get devices by location, will test out others.

**Comment by lilly-muyama** [comment]
> 
> 
> image
> also create thing works perfect.. but it's missing **some of the fields like status,** and **createdAt comes in as date time yet in all the device collection it was string as seen in the attachment.. This creates issues is some services running.. need to adopt it to** what the rest of devices contain.
> image
> image
> 
>     * update thing endpoint uses the actual deviceid according to documentation but they say it's not available on the platform when device Id is used or devicename
> 
> 
> image
> 
> Same thing the clear thing endpoint, device with specified deviceId does not exist on platfom
> image

@sserurich, a couple of comments:

- deviceID in this case is the Thingspeak ID (saved as channelID) in the database. It seems you are using the MongoDB _id field

- To make life easy and following system design, the status field is going to be removed in the next sprint. We introduced a new field, 'isActive' which takes on a Boolean value. It is updated to true when a device is deployed.

**Comment by lilly-muyama** [comment]
> 
> 
> @Baalmart could you add the isActive field among those returned by the get all devices endpoint.

Nvm, I think it's already there

**Comment by Baalmart** [comment]
> Update Thing endpoint not updating

Okay, going to look into asap today. Thanks.

**Comment by Baalmart** [comment]
> * Update Thing endpoints shows success message yet in the database, the data is not updates
> * Deployment endpoint should also update latitude and longitude coordinates since they are in the request body

Duly noted, let me act accordingly.

**Comment by Baalmart** [comment]
> > @Baalmart could you add the isActive field among those returned by the get all devices endpoint.
> 
> Nvm, I think it's already there
Hmm, thought it was not there. Let me confirm in my next commits

**Comment by lilly-muyama** [comment]
> 
> 
> image
> also create thing works perfect.. but it's missing **some of the fields like status,** and **createdAt comes in as date time yet in all the device collection it was string as seen in the attachment.. This creates issues is some services running.. need to adopt it to** what the rest of devices contain.
> image
> image
> 
>     * update thing endpoint uses the actual deviceid according to documentation but they say it's not available on the platform when device Id is used or devicename
> 
> 
> image
> 
> Same thing the clear thing endpoint, device with specified deviceId does not exist on platfom
> image

@sserurich the devices fields and datatypes have been updated to be uniform. e.g createdAt is now datetime and channelID is an integer

**Comment by lilly-muyama** [comment]
@Baalmart , I was just wondering if the endpoint that updates the maintenance log can be moved to this service and can be modified to write to the activities table. What do you think?

**Comment by Baalmart** [comment]
> @Baalmart , I was just wondering if the endpoint that updates the maintenance log can be moved to this service and can be modified to write to the activities table. What do you think?

Thanks, I totally subscribe to this thought. On it....

**Comment by lilly-muyama** [comment]
Please add 'visibility' and 'owner' to the fields returned by the Get all devices endpoint
Additionally, you seem to have changed the 'Create Thing' and 'Update Thing' visibility' field datatype. Why?

**Comment by Baalmart** [comment]
> Please add 'visibility' and 'owner' to the fields returned by the Get all devices endpoint
Okay, let me address this. 
> Additionally, you seem to have changed the 'Create Thing' and 'Update Thing' visibility' field datatype. Why?
As I was going about the implementation of this, I realised that the public_flag on ThingSpeak which corresponds to the purpose of visibility was Boolean. So when updates the visibility of MONGO DB, they also also update the public_flag on ThingSpeak.
--Otherwise, more than happy to review this further with you. :)

**Comment by lilly-muyama** [comment]
> 
> 
> > Please add 'visibility' and 'owner' to the fields returned by the Get all devices endpoint
> 
> Okay, let me address this.
> 
> > Additionally, you seem to have changed the 'Create Thing' and 'Update Thing' visibility' field datatype. Why?
> 
> As I was going about the implementation of this, I realised that the public_flag on ThingSpeak which corresponds to the purpose of visibility was Boolean. So when updates the visibility of MONGO DB, they also also update the public_flag on ThingSpeak.
> --Otherwise, more than happy to review this further with you. :)

It's okay. Let me make some changes to the frontend

**Comment by Baalmart** [comment]
> @Baalmart could you add the isActive field among those returned by the get all devices endpoint.

@lilly-muyama Please crosscheck this requested change, I think it was addressed sometime back. Thanks.

**Comment by Baalmart** [comment]
> Am failing to run this

Please share error messages + screenshots. Thanks.

**Comment by Priscilla-AL** [comment]
> > Am failing to run this
> 
> Please share error messages + screenshots. Thanks.

> device-registry@0.0.0 dev-pc C:\Users\User\Documents\Projects\AirQo-api\src\device-registry> set NODE_ENV=development node ./bin/www


C:\Users\User\Documents\Projects\AirQo-api\src\device-registry>

no error - just the above in the terminal

**Pull request merged**
