### PR TITLE
addressing percentage error

### PR DESCRIPTION
**Pull request by lilly-muyama**
# Device Uptime Hotfix
**_WHAT DOES THIS PR DO?_**
Ensures maximum device uptime is 100%
**_WHAT JIRA STORY/TASK IS RELATED TO THIS PR?_**
N/A
**_WHAT IS THE LINK TO THE PR BRANCH_**

**_HOW DO I TEST OUT THIS PR?_**
Git clone this repo. `cd src/device-uptime`, `env\scripts\activate`, `pip install -r requirements.txt`, `flask run`
**_WHICH ENDPOINTS SHOULD BE READY FOR TESTING?:_** 

**_IS THERE ANY JENKINS CONSOLE LINK FOR CODE COVERAGE AND BUILD INFO?_**

**_ARE THERE ANY RELATED PRs?_**

### CODE REVIEW

**Review by ja-odur — APPROVED** [review]
LGTM

**Review by danielogen — APPROVED** [review]
Looks good

**Review by Priscilla-AL — APPROVED** [review]
looks good

**Review by Baalmart — APPROVED** [review]
Looks good, thanks.

**Pull request merged**
