### PR TITLE
remove some backend validations

### PR DESCRIPTION
**Pull request by Baalmart**
# loosen up one some backend validations

**_WHAT DOES THIS PR DO?_**

- [x] loosen up one some backend validations for device registry CREATE and MAINTAIN.
- [x] Ensure that tags are added during device maintenance. Works so NO fix has been made ---just tests done. 

**_WHAT JIRA STORY/TASK IS RELATED TO THIS PR?_**
N/A

**_WHAT IS THE LINK TO THE PR BRANCH_**
https://github.com/airqo-platform/AirQo-api/tree/hotfixes-device-registry

**_HOW DO I TEST OUT THIS PR?_**
The README, use staging...

**_WHICH ENDPOINTS SHOULD BE READY FOR TESTING?:_** 

- [x] create device
[POST] http://localhost:3000/api/v1/devices?tenant=airqo
```
{}
```
- [x] maintain device
[POST] http://localhost:3000/api/v2/devices/activities/maintain?tenant=airqo&deviceName={DEVICE_NAME}

1. Try without any body to check out the mandatory fields --- we have remove maintananceType field.
2. Also ensure that the tags are also added.

```
{
     "date": "2021-09-05T16:09:24.611Z",
    "tags":["blowing", "dusting","metoo"],
     "description": "This is a test log"
}

```

**_IS THERE ANY JENKINS CONSOLE LINK FOR CODE COVERAGE AND BUILD INFO?_**
N/A

**_ARE THERE ANY RELATED PRs?_**
N/A

**_SCREENSHOTS_**
Screenshot 2021-08-27 at 21 28 05

Screenshot 2021-08-27 at 21 28 25

### CODE REVIEW

**Comment by ja-odur** [comment]
@Baalmart The test for updating maintenance logs (new/updated tags are not persisted)

**Review by ja-odur — CHANGES_REQUESTED** [review]
@Baalmart  I am getting this error whenever I try to create a device with minimal fields
```
Input data
{
    long_name: "AirQo Unit Test Odur", 
    generation_version: "5", 
    generation_count: "15"
}
```
Error
image

**Comment by Baalmart** [comment]
> @Baalmart The test for updating maintenance logs (new/updated tags are not persisted)

Unfortunately,  I am unable to reproduce the issue.... @ja-odur 
Screenshot 2021-08-27 at 21 28 05

**Comment by Baalmart** [comment]
> @Baalmart I am getting this error whenever I try to create a device with minimal fields
> 
> ```
> Input data
> {
>     long_name: "AirQo Unit Test Odur", 
>     generation_version: "5", 
>     generation_count: "15"
> }
> ```
> 
> Error
> image

That is strange, let me try to recreate the issue.

**Comment by Baalmart** [comment]
> @Baalmart I am getting this error whenever I try to create a device with minimal fields
> 
> ```
> Input data
> {
>     long_name: "AirQo Unit Test Odur", 
>     generation_version: "5", 
>     generation_count: "15"
> }
> ```
> 
> Error
> image

@ja-odur , I am unable to recreate the issue from my end. See screenshot below. Could this be related to "**_it works in Postman but it cannot work in the Frontend (React)_**"?
Screenshot 2021-08-28 at 10 58 52

**Comment by ja-odur** [comment]
> > @Baalmart I am getting this error whenever I try to create a device with minimal fields
> > ```
> > Input data
> > {
> >     long_name: "AirQo Unit Test Odur", 
> >     generation_version: "5", 
> >     generation_count: "15"
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Error
> > image
> 
> @ja-odur , I am unable to recreate the issue from my end. See screenshot below. Could this be related to "**_it works in Postman but it cannot work in the Frontend (React)_**"?
> Screenshot 2021-08-28 at 10 58 52

@Baalmart could try with the exact input that I have provided

**Comment by Baalmart** [comment]
> > > @Baalmart I am getting this error whenever I try to create a device with minimal fields
> > > ```
> > > Input data
> > > {
> > >     long_name: "AirQo Unit Test Odur", 
> > >     generation_version: "5", 
> > >     generation_count: "15"
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Error
> > > image
> > 
> > 
> > @ja-odur , I am unable to recreate the issue from my end. See screenshot below. Could this be related to "**_it works in Postman but it cannot work in the Frontend (React)_**"?
> > Screenshot 2021-08-28 at 10 58 52
> 
> @Baalmart could try with the exact input that I have provided

Cool...on it.

**Review by ja-odur — CHANGES_REQUESTED** [review]
@Baalmart This issue still exists. I tried to update the name  field only

image

**Comment by Baalmart** [comment]
> > > > @Baalmart I am getting this error whenever I try to create a device with minimal fields
> > > > ```
> > > > Input data
> > > > {
> > > >     long_name: "AirQo Unit Test Odur", 
> > > >     generation_version: "5", 
> > > >     generation_count: "15"
> > > > }
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Error
> > > > image
> > > 
> > > 
> > > @ja-odur , I am unable to recreate the issue from my end. See screenshot below. Could this be related to "**_it works in Postman but it cannot work in the Frontend (React)_**"?
> > > Screenshot 2021-08-28 at 10 58 52
> > 
> > 
> > @Baalmart could try with the exact input that I have provided
> 
> Cool...on it.

Done with the input, still works.... @ja-odur could I be missing something?
Screenshot 2021-08-28 at 11 06 31

**Comment by Baalmart** [comment]
> @Baalmart This issue still exists. I tried to update the name field only
> 
> image

Cool, let us allow long, lat and description to be empty. Checking....

**Comment by ja-odur** [comment]
> > > > > @Baalmart I am getting this error whenever I try to create a device with minimal fields
> > > > > ```
> > > > > Input data
> > > > > {
> > > > >     long_name: "AirQo Unit Test Odur", 
> > > > >     generation_version: "5", 
> > > > >     generation_count: "15"
> > > > > }
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > Error
> > > > > image
> > > > 
> > > > 
> > > > @ja-odur , I am unable to recreate the issue from my end. See screenshot below. Could this be related to "**_it works in Postman but it cannot work in the Frontend (React)_**"?
> > > > Screenshot 2021-08-28 at 10 58 52
> > > 
> > > 
> > > @Baalmart could try with the exact input that I have provided
> > 
> > 
> > Cool...on it.
> 
> Done with the input, still works.... @ja-odur could I be missing something?
> Screenshot 2021-08-28 at 11 06 31

Very strange @Baalmart  I am running this branch directly on staging (using staging db).  Could the be the issue?

**Comment by Baalmart** [comment]
> > > > > > @Baalmart I am getting this error whenever I try to create a device with minimal fields
> > > > > > ```
> > > > > > Input data
> > > > > > {
> > > > > >     long_name: "AirQo Unit Test Odur", 
> > > > > >     generation_version: "5", 
> > > > > >     generation_count: "15"
> > > > > > }
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > >     
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >     
> > > > > >   
> > > > > > Error
> > > > > > image
> > > > > 
> > > > > 
> > > > > @ja-odur , I am unable to recreate the issue from my end. See screenshot below. Could this be related to "**_it works in Postman but it cannot work in the Frontend (React)_**"?
> > > > > Screenshot 2021-08-28 at 10 58 52
> > > > 
> > > > 
> > > > @Baalmart could try with the exact input that I have provided
> > > 
> > > 
> > > Cool...on it.
> > 
> > 
> > Done with the input, still works.... @ja-odur could I be missing something?
> > Screenshot 2021-08-28 at 11 06 31
> 
> Very strange @Baalmart I am running this branch directly on staging (using staging db). Could the be the issue?

I am also running on Staging ( with localhost), check out screenshot. @ja-odur 
Screenshot 2021-08-28 at 11 12 42

**Comment by Baalmart** [comment]
> > > > > > @Baalmart I am getting this error whenever I try to create a device with minimal fields
> > > > > > ```
> > > > > > Input data
> > > > > > {
> > > > > >     long_name: "AirQo Unit Test Odur", 
> > > > > >     generation_version: "5", 
> > > > > >     generation_count: "15"
> > > > > > }
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > >     
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >     
> > > > > >   
> > > > > > Error
> > > > > > image
> > > > > 
> > > > > 
> > > > > @ja-odur , I am unable to recreate the issue from my end. See screenshot below. Could this be related to "**_it works in Postman but it cannot work in the Frontend (React)_**"?
> > > > > Screenshot 2021-08-28 at 10 58 52
> > > > 
> > > > 
> > > > @Baalmart could try with the exact input that I have provided
> > > 
> > > 
> > > Cool...on it.
> > 
> > 
> > Done with the input, still works.... @ja-odur could I be missing something?
> > Screenshot 2021-08-28 at 11 06 31
> 
> Very strange @Baalmart I am running this branch directly on staging (using staging db). Could the be the issue?

It is starting to sound like: “_**it works in Postman client but it cannot work in the React client**_” @ja-odur

**Comment by ja-odur** [comment]
@Baalmart Just tested this on my postman while pointing to the staging db. Same results.

image

**Comment by Baalmart** [comment]
> @Baalmart This issue still exists. I tried to update the name field only
> 
> image

What if we had different form sections for editing some critical properties like the `latitude` and `longitude`? Why should we allow someone to edit and save invalid coordinates into our system? @ja-odur

**Comment by ja-odur** [comment]
> > @Baalmart This issue still exists. I tried to update the name field only
> > image
> 
> What if we had different form sections for editing some critical properties like the `latitude` and `longitude`? Why should we allow someone to edit and save invalid coordinates into our system? @ja-odur

@Baalmart The fields are already few,  we cant do lower than this. The invalid values are coming from the system (already in the system)

**Review by ja-odur — CHANGES_REQUESTED** [review]
@Baalmart  I am getting a new error when I try to edit device `long_name`

image

**Comment by Baalmart** [comment]
> @Baalmart I am getting a new error when I try to edit device `long_name`
> 
> image
Failed to reproduce issue. @ja-odur 
Screenshot 2021-08-28 at 12 24 56

**Review by ja-odur — APPROVED** [review]
LGTM

**Pull request merged**
