### PR TITLE
Setup device weather data downloads

### PR DESCRIPTION
**Pull request by Mnoble-19**
**_WHAT DOES THIS PR DO?_**

- [x] Updates data export backend code to enable downloading device weather data

**_HOW DO I TEST OUT THIS PR?_**

- [x] Analytics: [Link to Analytics README](https://github.com/airqo-platform/AirQo-api/tree/staging/src/analytics#readme)

**_WHICH ENDPOINTS SHOULD BE READY FOR TESTING?:_** 

- [ ] Analytics data download endpoint
Screenshot 2024-06-14 at 13 14 56

## Summary by CodeRabbit

- **New Features**
  - Introduced handling for weather-related fields in air quality data processing.
  - Added `weatherFields` parameter for enhanced data export capabilities.

- **Bug Fixes**
  - Improved error handling and logging messages for better clarity and consistency.
  - Enhanced structure and formatting of JSON responses.

- **Style**
  - Standardized use of single and double quotes across multiple files for consistency.
  - Reformatted import statements for better readability.

- **Chores**
  - Added spaces around assignment operators and introduced blank lines for improved code readability.

### CODE REVIEW

**Review by MartinKalema — APPROVED** [review]
All good, thanks

**Comment by BenjaminSsempala** [comment]
@coderabbitai review

**Comment by Mnoble-19** [comment]
@Codebmk the code is setup to work the same way as pollutant selection works. 
From the front end, kindly set it up so that one specifies which weather fields they want (temperature, humidity, wind_speed) and then these are what are put in the body. 

just as it is done for the pollutants. 

you're welcome to reach out if anything  isn't clear

**Comment by Baalmart** [comment]
thanks @Mnoble-19

**Pull request merged**
