### PR TITLE
chore: device monitoring data segregation

### PR DESCRIPTION
**Pull request by danielogen**
- What does this PR do?
This PR adds multi-tenancy to the `device-monitoring` microservice.
- What JIRA task is related to this PR?
The link to the JIRA board task is [here](https://airqoteam.atlassian.net/browse/PLAT-73).
- How do I test out this PR?
Git clone this repo `cd AirQo-api/src/device-monitory` . And then run the following `docker` commands
`docker build -t test-device-monitor .` and `docker run -it -p 5555:4001 test-device-monitor`. `OR:` You can create and activate a python virtual env to run the service. Using: `python3 -m venv env`, `source env/bin/activate` and `pip install -r requirements.txt`. Now run `flask run` to test out the points using any REST client of your choice.
- Which end points should are ready for testing?
All endpoints as shown [in this documentation](https://docs.google.com/spreadsheets/d/1-NGTDBtTcIi8Fg2UYSWjcK6geKrZdopz5kxRFsCEMPs/edit#gid=1063367751) You just need to add the tenant parameter to each url e.g. http://localhost:5555/device/monitor/status?tenant=airqo or `?tenant=kcca`

### CODE REVIEW

**Review by Baalmart — COMMENTED** [review]
Been testing and getting many 500 internal server errors. Samples below:

1.  Getting network uptime

image

image

5. List of offline and online devices

image

image

**Review by Baalmart — CHANGES_REQUESTED** [review]
I have also noticed changes to the `auth-service`, we might need to review the changes accordingly....

**Review by Baalmart — COMMENTED** [review]
Just tried testing without Docker....

image

**Comment by danielogen** [comment]
> I have also noticed changes to the `auth-service`, we might need to review the changes accordingly....

I will raise a new PR tomorrow morning to resolve this

**Comment by danielogen** [comment]
> Been testing and getting many 500 internal server errors. Samples below:
> 
> 
> 
> 1.  Getting network uptime
> 
> 
> 
> image
> 
> 
> 
> image
> 
> 
> 
> 5. List of offline and online devices
> 
> 
> 
> image
> 
> 
> 
> image
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 

I think the data for those endpoints are not yet available - trying using `airqo` as tenant. I will have to add some user-friendly error reporting

**Review by lilly-muyama — CHANGES_REQUESTED** [review]
Error I get on testing second endpoint. Need more error handling
Capture

**Review by Baalmart — CHANGES_REQUESTED** [review]
- [ ] we need to resolve merge conflicts

- [ ] we also need to appropriately handle different run environments (staging, production, development) as we run things using Docker or flask run.
**Resources:**
1. https://kelvinmwinuka.com/organising-flask-configurations/
2. https://stackoverflow.com/questions/44951244/flask-production-and-development-mode

- [ ] we shall also need to either create a new PR or undo the changes to other microservices (auth-service). Or just update this PR accordingly.

- [ ] we also need appropriate error handling for cases where the endpoint does not exist for this microservices. got confused when fetching without the API version number as specified in the PR description. 

- [ ] GET device status summary - works as expected - just need appropriate error handling for non existent tenant and missing query params 

- [ ] GET number of Devices offline/online - needs proper error handling with JSON response for cases with non existent tenant. Same case for missing tenant ID in the query URI. 

- [ ] GET list of offline devices - needs error handling (appropriate JSON response) for cases where the organisation does not exist. The endpoint works as expected for airqo. I also realise that the path description of the endpoint is not consistent with others of the same microservice, that is: "api/v1/monitor" yet others are: "api/v1/devices/monitor". 

- [ ] Network Uptime - needs error handling for cases where the tenant does not exist. The endpoint works as expected for airqo tenant. Needs appropriate error handling (JSON response) for cases when the user forgets to put the tenant in their query params. The path of this endpoint is also inconsitent with the one for others, that is: it is "api/v1/monitor...." yet others are "api/v1/device/monitor" 

- [ ] We also need to handle BAD REQUEST errors for endpoints that do not exist in this microservice. Resource: https://flask.palletsprojects.com/en/1.1.x/patterns/errorpages/ 

- [ ] List of online and offline devices - no appropriate error response for cases where the tenant is not provided. Returns response when airqo tenant is provided. No appropriate error handling (JSON response) for cases where the tenant does not exist. 

- [ ] List maintenance log - this one functions as expected. Returns empty array for cases where the tenant does not exist. 

- [ ] List maintenance log for a single device - needs appropriate error handling because it returns empty array even when device name is innacurate, example: used <device_name> as device name and it responded with an empty array. Returns an empty array for cases where the tenant ID does exist in system. Needs more appropriate error response (JSON) when the tenant ID is not provided in the request body. 

- [ ] List Power Type - works as expected for airqo tenant. Same case for kcca tenant. Returns empty array for non existent tenant DB. Needs error handling for cases where the user forgets to provide the tenant query parameter. The response for kcca tenant just provides the device IDs and names but no information about their power type. 

- [ ] Device Uptime - needs appropriate error response for cases where incorrect channel ID is provided. Also needs error handling (informative JSON response) for cases where the tenant does not exist - this could just be an empty array as a response. Also needs appropriate error handling for cases where a tenant is not provided in the request URI. The path of this endpoint is also not consistent with others of this microservice: has "monitor/device..." while others have "device/monitor....", we need to have some consistency,perhaps just have "monitor/devices" in the base URI? 

- [ ] Battery Voltage graph data - needs appropriate error response for cases where the tenant ID is not provided. Works as expected for cases where tenant is airqo. Needs appropriate error handling for cases where the tenant does not exist - OR we can just return an empty array. Endpoint does not have the same path as the rest of the endpoints - needs some consistency in the base URI 

- [ ] Sensor Correlation graph data - works as expected for airqo. This endpoint needs to be generic enough since KCCA does not have channel IDs but rather has device ID or device name. Does not have appropriate error handling (JSON response) for cases where the tenant query param is not provided. The path of the endpoint is also not consistent with the rest when it comes to the base URI - could we try to choose one format throughout?

**Comment by danielogen** [comment]
Raising new pr for this in a few

**Pull request closed without merging**
