### PR TITLE
move to production

### PR DESCRIPTION
**Pull request by Baalmart**
**_WHAT DOES THIS PR DO?_**

- [x] https://github.com/airqo-platform/AirQo-api/pull/1448
- [x] https://github.com/airqo-platform/AirQo-api/pull/1447

### CODE REVIEW

**Comment by Baalmart** [comment]
@123MwanjeMike / @uman95 / @wabinyai / @sserurich  . I can see a couple of changed files for the Predict microservice.

1. Could you confirm which PR introduced these changes?
2. Are the changes ready to be moved to production?
3. Could these changes relate to the current challenges in the heatmap implementation?

**Comment by uman95** [comment]
Sorry, I have no knowledge of this.

**Review by sserurich — COMMENTED** [review]
@Baalmart , there some things that were still being addressed with the merged PR for the forecast cc @Mnoble-19.

**Comment by Baalmart** [comment]
> @Baalmart , there some things that were still being addressed with the merged PR for the forecast cc @Mnoble-19.

Thanks @sserurich , we want to move a bit fast and address corresponding issues as the endpoint is being used in the frontend apps. We should be able to review decision again.

cc: @Mnoble-19

**Pull request merged**
