### PR TITLE
Update ALL API routes to V2

### PR DESCRIPTION
**Pull request by Mnoble-19**
**_WHAT DOES THIS PR DO?_**
* Updates all API routes for all microservices to V2

### CODE REVIEW

**Review by 123MwanjeMike — CHANGES_REQUESTED** [review]
Hi @Mnoble-19 
I'm seeing the error log below failing the predict deploy preview. Could we have it fixed too?

```
textPayload: "Traceback (most recent call last):
  File "/usr/local/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 1063, in main
    cli.main()
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 93, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 911, in run_command
    raise e from None
  File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 897, in run_command
    app = info.load_app()
  File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 218, in locate_app
    __import__(module_name)
  File "/app/app.py", line 47, in <module>
    postgres_db = SQLAlchemy(application)
  File "/usr/local/lib/python3.9/site-packages/flask_sqlalchemy/extension.py", line 221, in __init__
    self.init_app(app)
  File "/usr/local/lib/python3.9/site-packages/flask_sqlalchemy/extension.py", line 310, in init_app
    raise RuntimeError(
RuntimeError: Either 'SQLALCHEMY_DATABASE_URI' or 'SQLALCHEMY_BINDS' must be set."
timestamp: "2023-07-11T10:22:24.852017Z"
```

image

**Comment by NoahNsimbe** [comment]
> Hi @Mnoble-19 I'm seeing the error log below failing the predict api deploy preview. Could we have it fixed too?
> 
> ```
> textPayload: "Traceback (most recent call last):
>   File "/usr/local/bin/flask", line 8, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 1063, in main
>     cli.main()
>   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1078, in main
>     rv = self.invoke(ctx)
>   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 783, in invoke
>     return __callback(*args, **kwargs)
>   File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 93, in new_func
>     return ctx.invoke(f, obj, *args, **kwargs)
>   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 783, in invoke
>     return __callback(*args, **kwargs)
>   File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 911, in run_command
>     raise e from None
>   File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 897, in run_command
>     app = info.load_app()
>   File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 308, in load_app
>     app = locate_app(import_name, name)
>   File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 218, in locate_app
>     __import__(module_name)
>   File "/app/app.py", line 47, in <module>
>     postgres_db = SQLAlchemy(application)
>   File "/usr/local/lib/python3.9/site-packages/flask_sqlalchemy/extension.py", line 221, in __init__
>     self.init_app(app)
>   File "/usr/local/lib/python3.9/site-packages/flask_sqlalchemy/extension.py", line 310, in init_app
>     raise RuntimeError(
> RuntimeError: Either 'SQLALCHEMY_DATABASE_URI' or 'SQLALCHEMY_BINDS' must be set."
> timestamp: "2023-07-11T10:22:24.852017Z"
> ```
> 
> image

This has been resolved. @123MwanjeMike

**Comment by 123MwanjeMike** [comment]
Thanks @NoahNsimbe

**Review by 123MwanjeMike — APPROVED** [review]
LGTM

**Pull request closed without merging**
