### PR TITLE
[device-uptime] Eliminate BQ from device uptime

### PR DESCRIPTION
**Pull request by ja-odur**
#### Summary of Changes (What does this PR do?)
- Eliminate BQ from device uptime calculation
- Remove unused code
- Flatten directories
- Add ReadMe.md file
- General refactoring
#### Is this change ready to hit production in its current state?
- [x] Yes
- [ ] No

#### Status of maturity (all need to be checked before merging):

- [x] I consider this code done
- [x] I've tested this locally
- [ ] This branch has been LGTM'ed by a reviewer

#### How should this be manually tested?
* Fetch this branch locally.
* Change directory to the `device-uptime` micro-service directory.
* Follow the steps in the `README.md` file to run the script.
* The script should run successfully.

#### What are the relevant tickets?
- [PLAT-569](https://airqoteam.atlassian.net/browse/PLAT-569)

### CODE REVIEW

**Review by danielogen — APPROVED** [review]
Working great! There is need to update the data side of things

**Review by sserurich — APPROVED** [review]
looks good, an extra eye is required to see whether these devices didn't have data as the results indicated. 
image

**Review by lilly-muyama — COMMENTED** [review]
There's a need to investigate why some supposedly active devices are returning no records e.g. aq_18, aq_47, aq_55 etc.

**Review by Baalmart — APPROVED** [review]
runs as expected, I share the same comments raised by @sserurich  in his review.

**Pull request merged**
