### PR TITLE
[Analytics] BigQuery Data Export

### PR DESCRIPTION
**Pull request by ja-odur**
#### Summary of Changes (What does this PR do?)
* Enhance d3 chart data endpoint to return pie multilayer chart data

#### Is this change ready to hit production in its current state?
- [x] Yes
- [ ] No

#### Status of maturity (all need to be checked before merging):

- [x] I consider this code done
- [ ] I've tested this locally
- [ ] This branch has been LGTM'ed by a reviewer

#### How should this be manually tested?
* Fetch and checkout to this branch locally
* Change directory to the analytics microservice
* Start redis (in another terminal)
* Create and/or start your `python` virtual env
* Install requirements `pip install -r requirements.txt
* Set the `.env` file. Sample [here](https://drive.google.com/file/d/1oK3Dg7Z1xXuIPpnALLXOLokxh1B1shs-/view?usp=sharing)
* Start application `flask run`
* Check the swagger docs `http://localhost:5000/api/v1/analytics/apidocs/`
* The download data endpoint `POST` `http://localhost:5000/api/v1/analytics/dashboard/chart/d3/data` should be returning sorted data.

###### Endpoint

    POST http://localhost:5000/api/v1/analytics/data/download?tenant=airQo&downloadType=json

###### Sample data
```
{
	"startDate": "2022-01-01T00:00:00.000Z",
	"endDate": "2022-02-01T00:00:00.000Z",
	"frequency": "hourly",
	"pollutants": ["pm2_5", "pm10"],
	"sites": ["60d058c8048305120d2d6133", "617002d2965742002965ab69"],
	"fromBigQuery": true
}
```

### CODE REVIEW

**Review by Baalmart — APPROVED** [review]
All runs well, thanks @ja-odur code also looks clean.

Please check the Swagger documentation, appears some endpoints return Bad Requests on Testing

**Review by Baalmart — COMMENTED** [review]
Consider all previous as just comments/thoughts, no changes requested except more PR description notes as we test out the PR. Thanks

My reviews are mostly biased by the PR title so I would like to appreciate the Big Query part, unless this is not the PR for such? Thanks @ja-odur

**Comment by ja-odur** [comment]
> @ja-odur ,
> 
> running with `fromBigQuery = true`, i was able to get results in about 10seconds. Is this the expected wait time? And what kind of tests should we carry out to ensure that we thoroughly test out the solution?
> 
> 1. Duration of downloads? What happens when someone wants to download data for 3 years at once? What happens? How long does it take? How can we do that with the existing endpoint in the PR example?
> 2. Could there be any other non functional requirements we need to be aware of? As we test out the PR?

@Baalmart no any other requirements are required. To rule out internet issue, probably try to run the endpoint with `fromBigQuery` set to both `true` and `false`.

**Review by NoahNsimbe — COMMENTED** [review]
Thanks @ja-odur 
The functionality involves usage of a GCP secret file but it hasn't been added to `.gitignore`. Won't that cause issues in the future??

**Comment by ja-odur** [comment]
> Thanks @ja-odur The functionality involves usage of a GCP secret file but it hasn't been added to `.gitignore`. Won't that cause issues in the future??

@NoahNsimbe Tracking filenames may be tricky in the `.gitignore`. Maybe we use convention (such as having a `.secret` folder which can then be added to the gitignore) to store the credential files.

**Review by Baalmart — COMMENTED** [review]
Thanks @ja-odur , awesome work! Making a second attempt at testing this....
Just been trying to run the backend, to support the frontend tests of a related PR.
Unfortunately, have run into the following issue after running `flask run`:
Screenshot 2022-02-24 at 16 59 11
Screenshot 2022-02-24 at 16 59 19

**Comment by Baalmart** [comment]
> {
> 	"startDate": "2022-01-01T00:00:00.000Z",
> 	"endDate": "2022-02-01T00:00:00.000Z",
> 	"frequency": "hourly",
> 	"pollutants": ["pm2_5", "pm10"],
> 	"sites": ["60d058c8048305120d2d6133", "617002d2965742002965ab69"],
> 	"fromBigQuery": true
> }

Good catch, we need to add it to the .gitignore for the start. As we continue to find a better solution. cc: @ja-odur

**Review by Baalmart — COMMENTED** [review]
LGTM now, please add the json file to the .gitignore as the first iteration of dealing with the security of this resource. @ja-odur

**Review by Baalmart — APPROVED** [review]
LGTM now. Just added the GCP file to the .gitignore. @NoahNsimbe @ja-odur

**Pull request merged**
