### PR TITLE
Pm10 calibration

### PR DESCRIPTION
**Pull request by Priscilla-AL**
# <Feature/Chore/Hotfix/Topic/Bug Title>

**_WHAT DOES THIS PR DO?_**
Calibrate PM10 values

**_WHAT JIRA STORY/TASK IS RELATED TO THIS PR?_**
https://airqoteam.atlassian.net/jira/software/projects/DP/boards/44?assignee=5d91eed256bb950dd6489270&selectedIssue=DP-82

**_WHAT IS THE LINK TO THE PR BRANCH_**
https://github.com/airqo-platform/AirQo-api/tree/PM10_calibration

**_HOW DO I TEST OUT THIS PR?_**

Git clone this repo
cd calibrate
python -m venv env to create an environment if you don't already have one
env\scripts\activate or source env/bin/activate for MacOS
You need a GCP key and .env: found in the drive - https://drive.google.com/drive/u/0/folders/1N9I8eyx5A0RMgikQHlVfofkxGSh1sLSG 
pip install -r requirements.txt
python jobs\regression.py
flask run

**_WHICH ENDPOINTS SHOULD BE READY FOR TESTING?:_** 
http://127.0.0.1:4001/api/v1/calibrate

Documentation: https://app.gitbook.com/@airqo/s/airqo-platform-api/calibrate

**_IS THERE ANY JENKINS CONSOLE LINK FOR CODE COVERAGE AND BUILD INFO?_**
NA
**_ARE THERE ANY RELATED PRs?_**
NA

### CODE REVIEW

**Review by sserurich — CHANGES_REQUESTED** [review]
the endpoint works as expected, however some changes might need to be enacted
- may be join the microservice functionality to the calibrate microservice
- add versions to some packages in requirements.txt
- jenkins file seems similar to the one in calibrate ,this might cause issues in case this microservice runs

**Comment by sserurich** [comment]
> the endpoint works as expected, however some changes might need to be enacted
> 
> * may be join the microservice functionality to the calibrate microservice
> * add versions to some packages in requirements.txt
> * jenkins file seems similar to the one in calibrate ,this might cause issues in case this microservice runs

issues addressed except the package version issues which doesn't block anything and still below is the results from rerunning 
image

**Review by sserurich — APPROVED** [review]
minor improvement you can do, 
- can may be put the GCP credential file in the jobs/regression.py to .env
- Thanks Richard, I have updated the package versions

**Review by NoahNsimbe — APPROVED** [review]
Works as expxected however we might need to review the dockerfile and make any necessary updates for example: 
```
RUN --mount=type=cache,target=/root/.cache/pip pip install -r requirements.txt
RUN python jobs/regression.py
```

**Pull request merged**
