### PR TITLE
Heatmap all aqs

### PR DESCRIPTION
**Pull request by lilly-muyama**
# <Heatmap Endpoint Update>

**_WHAT DOES THIS PR DO?_**
This PR modifies the heatmap endpoint to return predictions for all airqlouds.

**_WHAT JIRA STORY/TASK IS RELATED TO THIS PR?_**
[DP-67](https://airqoteam.atlassian.net/browse/DP-67)

**_WHAT IS THE LINK TO THE PR BRANCH_**

**_HOW DO I TEST OUT THIS PR?_**
Please note that before you run this PR, you must have run [another PR](https://github.com/airqo-platform/AirQo-api/pull/547) in the gp-model microservice.

`Git clone this repo`
`cd predict`
`py -m venv env` to create an environment if you don't already have one
`env\scripts\activate` or `source env/bin/activate` for MacOS
`pip install -r requirements.txt`
`flask run` 

**_WHICH ENDPOINTS SHOULD BE READY FOR TESTING?:_** 
NOTE: Please set the airqloud or id parameters 
http://localhost:5000/api/v1/predict/heatmap

**_IS THERE ANY JENKINS CONSOLE LINK FOR CODE COVERAGE AND BUILD INFO?_**

**_ARE THERE ANY RELATED PRs?_**

### CODE REVIEW

**Review by sserurich — APPROVED** [review]
LGTM. 
image

**Review by danielogen — APPROVED** [review]
LGTM

**Comment by danielogen** [comment]
Updated this PR to accommodate changes requested by PLATFORM team
cc: @Baalmart, @ja-odur

**Review by ja-odur — APPROVED** [review]
LGTM

**Pull request merged**
