### PR TITLE
Search history Endpoints

### PR DESCRIPTION
**Pull request by BenjaminSsempala**
**_WHAT DOES THIS PR DO?_**

**_WHAT ISSUES ARE RELATED TO THIS PR?_**

- Jira cards
    - []()
- GitHub issues
    - Closes #<enter GitHub issue number here>

**_HOW DO I TEST OUT THIS PR?_**

**_WHICH ENDPOINTS SHOULD BE READY FOR TESTING?:_** 

**_IS THERE ANY JENKINS CONSOLE LINK FOR CODE COVERAGE AND BUILD INFO?_**

**_ARE THERE ANY RELATED PRs?_**

### CODE REVIEW

**Review by Baalmart — COMMENTED** [review]
Hi @BenjaminSsempala , thanks for this amazing work!

A quick observation:
Do we have some duplication of work between this PR and this one:https://github.com/airqo-platform/AirQo-api/pull/1929?

**Comment by BenjaminSsempala** [comment]
> Hi @BenjaminSsempala , thanks for this amazing work!
> 
> A quick observation: Do we have some duplication of work between this PR and this one:#1929?

@Baalmart They are a little bit similar although one use case is for location and the other one is search.

**Comment by Baalmart** [comment]
> > Hi @BenjaminSsempala , thanks for this amazing work!
> > A quick observation: Do we have some duplication of work between this PR and this one:#1929?
> 
> @Baalmart They are a little bit similar although one use case is for location and the other one is search.

Thanks @BenjaminSsempala , I do notice some code duplication where one PR creates a new file and that same new file is also created in another PR? Could I be missing something? Perhaps all this was meant to be in one PR? Please crosscheck and get back to me. Thanks!

**Comment by BenjaminSsempala** [comment]
> > > Hi @BenjaminSsempala , thanks for this amazing work!
> > > A quick observation: Do we have some duplication of work between this PR and this one:#1929?
> > 
> > 
> > @Baalmart They are a little bit similar although one use case is for location and the other one is search.
> 
> Thanks @BenjaminSsempala , I do notice some code duplication where one PR creates a new file and that same new file is also created in another PR? Could I be missing something? Perhaps all this was meant to be in one PR? Please crosscheck and get back to me. Thanks!

Thanks @Baalmart Yes I stemmed this branch from the `locationHistory` Branch and not staging, because I required some changes from the other one too.
So I think either:

- The other one can be merged first then I can merge staging into  this one.
- Or only this one needs to be merged since it has changes from both branches

**Review by NoahNsimbe — APPROVED** [review]
LGTM

**Pull request closed without merging**
