### PR TITLE
Location registry backend

### PR DESCRIPTION
**Pull request by lilly-muyama**
- What does this PR do?
This PR created a location-registry microservice and endpoints to be utilized by the location registry.
- What JIRA task is related to this PR?
[1](https://airqoteam.atlassian.net/jira/software/projects/NET/boards/28?selectedIssue=NET-11)
[2](https://airqoteam.atlassian.net/jira/software/projects/NET/boards/28?selectedIssue=NET-23)
[3](https://airqoteam.atlassian.net/jira/software/projects/NET/boards/28?selectedIssue=NET-26)
[4](https://airqoteam.atlassian.net/jira/software/projects/NET/boards/28?selectedIssue=NET-22)
[5](https://airqoteam.atlassian.net/jira/software/projects/NET/boards/28?selectedIssue=NET-12)
[6](https://airqoteam.atlassian.net/jira/software/projects/NET/boards/28?selectedIssue=NET-24)
[7](https://airqoteam.atlassian.net/jira/software/projects/NET/boards/28?selectedIssue=NET-13)
- How do I test out this PR?
Git clone this repo `cd AirQo-api/src/location-registry` Then run `pip install -r requirements.txt` to get all the relevant packages. Afterwards run `flask run` to test out the end points using any REST client tool available to you.
- Which end points should are ready for testing?
partial url: /api/v1/location_registry/create_id
partial url: /api/v1/location_registry/register
partial url: /api/v1/location_registry/locations
partial url: /api/v1/location_registry
partial url: /api/v1/location_registry/edit
partial url: /api/v1/location_registry/update

### CODE REVIEW

**Comment by Baalmart** [comment]
> **Issue Alert:** I need some assistance. After running `pip install requirements.txt`, I get the following error shown in this screenshot.:
> 
> image

"Could not find a version that satisfies the requirement requirements.txt"

**Comment by danielogen** [comment]
@Baalmart, looks like you are missing `-r` switch. Try running `pip install -r requirements.txt`

**Comment by Baalmart** [comment]
> @Baalmart, looks like you are missing `-r` switch. Try running `pip install -r requirements.txt`

Thanks, I have made some progress with your suggestion and then encountered another error: 
**"Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/home/conda/feedstock_root/build_artifacts/branca_1588860304135/work"**

image

**Comment by danielogen** [comment]
> > @Baalmart, looks like you are missing `-r` switch. Try running `pip install -r requirements.txt`
> 
> Thanks, I have made some progress with your suggestion and then encountered another error:
> **"Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/home/conda/feedstock_root/build_artifacts/branca_1588860304135/work"**
> 
> image

@lilly-muyama will pick it up from here :)

**Comment by Baalmart** [comment]
> > > @Baalmart, looks like you are missing `-r` switch. Try running `pip install -r requirements.txt`
> > 
> > 
> > Thanks, I have made some progress with your suggestion and then encountered another error:
> > **"Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/home/conda/feedstock_root/build_artifacts/branca_1588860304135/work"**
> > image
> 
> @lilly-muyama will pick it up from here :)

Okay @lilly-muyama , patiently waiting for your updates... :)

**Comment by lilly-muyama** [comment]
> 
> 
> > > > @Baalmart, looks like you are missing `-r` switch. Try running `pip install -r requirements.txt`
> > > 
> > > 
> > > Thanks, I have made some progress with your suggestion and then encountered another error:
> > > **"Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/home/conda/feedstock_root/build_artifacts/branca_1588860304135/work"**
> > > image
> > 
> > 
> > @lilly-muyama will pick it up from here :)
> 
> Okay @lilly-muyama , patiently waiting for your updates... :)

I had created my environment using conda. I am going to raise a new PR which hopefull fixes this issue

**Pull request closed without merging**
