### PR TITLE
Added codecov workflow file

### PR DESCRIPTION
**Pull request by Kisakye-e**
**_WHAT DOES THIS PR DO?_**

Setups Code cov  for this repository

**_HOW DO I TEST OUT THIS PR?_**

Set  up a codecov account at https://about.codecov.io/
Setup the repo and add the codecov token to the repository secrets(Must be done by an admin)
Once successfully set up, the codecov status checks will show on every push and pull request.

### CODE REVIEW

**Review by Baalmart — COMMENTED** [review]
Hi @Kisakye-e , thanks for this.
Just a couple of feedback points:

1. Please also add the introduction notes: “what does this PR do?“, etc…..and remove sections which are not relevant to you. Thanks
2. Also, I notice only pytests, could you shed some light on how this workflow would work for a node.js project?

Thanks again!

**Comment by Baalmart** [comment]
Hi @Kisakye-e . What is the current status of this PR? Does it pass all the checks for merging? cc: @Psalmz777

**Comment by Kisakye-e** [comment]
> Hi @Kisakye-e , thanks for this. Just a couple of feedback points:
> 
> 1. Please also add the introduction notes: “what does this PR do?“, etc…..and remove sections which are not relevant to you. Thanks
> 2. Also, I notice only pytests, could you shed some light on how this workflow would work for a node.js project?
> 
> Thanks again!

Hi @Baalmart , we need to have the tests written before we can add a section for them to the workflow files..

**Comment by Baalmart** [comment]
Thanks @Kisakye-e 
1. the tests for Node.js projects already exist. 
2. Perhaps I could be missing something in your response? 🤔

**Comment by Kisakye-e** [comment]
@Baalmart , if that's the case then let me work on adding them to the workflow file...I hope the repo was setup and the token was added successfully. Thank you !

**Comment by Baalmart** [comment]
Yes @Kisakye-e the secrets were all added successfully.

**Pull request closed without merging**
