### PR TITLE
Streaming NASA data from Purple Air

### PR DESCRIPTION
**Pull request by NoahNsimbe**
**_WHAT DOES THIS PR DO?_**

- [ ] Functions to process and store raw data from NASA devices in Ethiopia

**_WHAT ISSUES ARE RELATED TO THIS PR?_**

- Jira cards
    - [PLAT-1179](https://airqoteam.atlassian.net/browse/PLAT-1179)

### CODE REVIEW

**Comment by Baalmart** [comment]
Hi @NoahNsimbe , looks like this PR has some merge conflicts.
What is the actual review status for the PR?

**Comment by 123MwanjeMike** [comment]
This PR's branch has been stale for 3 months.
Please consider deleting it if it's obsolete to minimise the size of the repo clone.
cc @NoahNsimbe

**Comment by NoahNsimbe** [comment]
> This PR's branch has been stale for 3 months. Please consider deleting it if it's obsolete to minimise the size of the repo clone. cc @NoahNsimbe

Thanks @123MwanjeMike. This was put on hold. I shall revisit it next week/sprint.

**Comment by Baalmart** [comment]
Hi @NoahNsimbe ,  thanks for this PR.I gather this feeds so much into the OKR about streamlining the ingestion of data from external networks.

1. what is the status of this PR? What label should go here? `work-in-progress`? r`eady-for-review`? or `both`?
2. Also, I do notice some merge conflicts.

**Pull request closed without merging**
