### PR TITLE
Location Registry Fix

### PR DESCRIPTION
**Pull request by lilly-muyama**
## Changing Database Collection Name

**_WHAT DOES THIS PR DO?_**
This PR changes the name of the location for looking up the administrative areas of a site.

**_WHAT JIRA STORY/TASK IS RELATED TO THIS PR?_**
N/A
**_WHAT IS THE LINK TO THE PR BRANCH_**

**_HOW DO I TEST OUT THIS PR?_**

**_WHICH ENDPOINTS SHOULD BE READY FOR TESTING?:_** 
http://localhost:4000/api/v1/location_registry/register?tenant=kcca

**_IS THERE ANY JENKINS CONSOLE LINK FOR CODE COVERAGE AND BUILD INFO?_**

**_ARE THERE ANY RELATED PRs?_**

### CODE REVIEW

**Review by danielogen — APPROVED** [review]
Looks to me, just changing the collection name.

**Review by sserurich — APPROVED** [review]
looks good to me, though a better name might be needed to store these

**Review by ja-odur — APPROVED** [review]
LGTM

**Review by Baalmart — APPROVED** [review]
Looks good to me, just curious about this "parishes" collection. And other collections related to this microservice.

I guess I will need to do some homework in the near future. :)

**Pull request merged**
