### PR TITLE
intrducing the device status field

### PR DESCRIPTION
**Pull request by Baalmart**
# introducing the device status field

**_WHAT DOES THIS PR DO?_**
introducing the device status field

**_WHAT JIRA STORY/TASK IS RELATED TO THIS PR?_**
N/A

**_WHAT IS THE LINK TO THE PR BRANCH_**
https://github.com/airqo-platform/AirQo-api/tree/enhancement-device-status

**_HOW DO I TEST OUT THIS PR?_**
in the read ME, using then staging environment

**_WHICH ENDPOINTS SHOULD BE READY FOR TESTING?:_** 
[PUT] Update device:
http://localhost:3000/api/v1/devices?tenant=airqo&name={DEVICE_NAME}
status can be:

- ready
- recalled
- deployed
- undeployed
- decommissioned
- assembly

_THE BODY:_
```
{
    "status": "recalled"
}
```

**_IS THERE ANY JENKINS CONSOLE LINK FOR CODE COVERAGE AND BUILD INFO?_**
N/A

**_ARE THERE ANY RELATED PRs?_**
N/A

### CODE REVIEW

**Comment by danielogen** [comment]
All LTGM - Let me wait for PR review session to get up to speed on the significance of this powerful feature

**Review by NoahNsimbe — APPROVED** [review]
LGTM

**Review by NoahNsimbe — COMMENTED** [review]
Please update your branch with the changes in  staging

**Review by ja-odur — APPROVED** [review]
LGTM

**Pull request merged**
