### PR TITLE
Airqualibrate pdt1   similar devices

### PR DESCRIPTION
**Pull request by Priscilla-AL**
# Airqualibrate pdt1 similar devices

**_WHAT DOES THIS PR DO?_**
Creates 2 APIs
1. For calibrating data from the user using the model trained with AirQo data. 
2. For training and calibrating data using a model trained with collocation data from the user. (If the user has their own data from the collocation of a low-cost and a reference monitor)

**_WHAT JIRA STORY/TASK IS RELATED TO THIS PR?_**
https://airqoteam.atlassian.net/jira/software/projects/DP/boards/44?assignee=5d91eed256bb950dd6489270&selectedIssue=DP-172

**_WHAT IS THE LINK TO THE PR BRANCH_**
https://github.com/airqo-platform/AirQo-api/tree/Airqualibrate-pdt1---similar-devices/

**_HOW DO I TEST OUT THIS PR?_**
cd AirQo-api/src/calibrate
python -m venv [DESTINATION_FOLDER]
[DESTINATION_FOLDER]/Scripts/activate
pip install -r requirements.txt

python jobs\regression.py (one time)
flask run
NB: Make sure you add a GCP service account key under jobs/      (available on request)

flask run

SAMPLE REQUEST BODY:
 See images below for sample request bodies

NB:  
1.  accepted values for the KEY "pollutant"  are PM2.5 and PM10 (this will be a radio button on the frontend)
2. for KEY "file", please upload a CSV containing data for each of the keys specified except "file" and "pollutant"
3. for the rest of the entries except where KEY is "file" or "pollutant", the KEY is the column name in the uploaded CSV corresponding to the fields given by VALUE.  i.e. datetime, sensor1 pm2.5, sensor2 pm2.5, sensor1 pm10, sensor1 pm10, temperature, humidity and collocated reference monitor PM values. 
4. SAMPLE CSV FILE AVAILABLE ON REQUEST

API 1
api 1

API 2

api 2

EXPECTED RESULTS:
API 1: data in CSV format with calibrated data (PM2.5 and PM10).
API 2:data in CSV format with calibrated data (PM2.5 or PM10) depending on the choice of reference pollutant selected.

**_WHICH ENDPOINTS SHOULD BE READY FOR TESTING?:_** 
[POST] http://127.0.0.1:4001/api/v1/calibrate_tool
[POST] http://127.0.0.1:4001/api/v1/train_calibrate_tool

**_IS THERE ANY JENKINS CONSOLE LINK FOR CODE COVERAGE AND BUILD INFO?_**
NA
**_ARE THERE ANY RELATED PRs?_**
NA

### CODE REVIEW

**Review by Baalmart — COMMENTED** [review]
Hi @Priscilla-AL , any way we can have some of this sample input as text? So that the reviewer's can just copy paste? Thanks.

Also, I have had to lower my pandas version to resolve some installation errors.

**Comment by Priscilla-AL** [comment]
> Hi @Priscilla-AL , any way we can have some of this sample input as text? So that the reviewer's can just copy paste? Thanks.
> 
> Also, I have had to lower my pandas version to resolve some installation errors.

Thanks, Martin for the review, I have updated the instructions

**Review by Baalmart — APPROVED** [review]
Thanks @Priscilla-AL , great work!

1. We need to document these API endpoints using Gitbooks or any other appropriate tool before we let this PR in. cc: @123MwanjeMike 
2. We shall also need to document most of our awesome engineering works using appropriate distribution channels like: Youtube, Medium, Twitter, etc. cc: @Codebmk

**Review by NoahNsimbe — APPROVED** [review]
Below are a few observations @Priscilla-AL 

1. I had to add `itsdangerous==2.0.1` to the requirements for the app to work in Docker.
2. The APIs aren't documented in Gitbooks. 
3. An index column is returned in the results. It is useful??
Screenshot 2022-02-23 at 18 11 33

**Comment by Priscilla-AL** [comment]
> 1. itsdangerous==2.0.1

Hi Noah, Thanks for the review.
1. I have added the package to the requirements file
2. The documentation is on my to-do
3. There is actually no index. It defaults to numbered rows when no index is set.

**Pull request merged**
