### PR TITLE
Calibrate basic version

### PR DESCRIPTION
**Pull request by Priscilla-AL**
**_WHAT DOES THIS PR DO?_**
Create a minimum version of the calibrate API  
**_WHAT ISSUES ARE RELATED TO THIS PR?_**
NA
- Jira cards
    - https://airqoteam.atlassian.net/jira/software/projects/DP/boards/44?assignee=5d91eed256bb950dd6489270&selectedIssue=DP-330 
- GitHub issues
    - Closes #<enter GitHub issue number here>

**_HOW DO I TEST OUT THIS PR?_**
See ReadMe
**_WHICH ENDPOINTS SHOULD BE READY FOR TESTING?:_** 
[POST] http://127.0.0.1:4001/api/v1/calibrate/minimum
**_IS THERE ANY JENKINS CONSOLE LINK FOR CODE COVERAGE AND BUILD INFO?_**
NA
**_ARE THERE ANY RELATED PRs?_**
NA

### CODE REVIEW

**Review by NoahNsimbe — COMMENTED** [review]
Hi @Priscilla-AL, the API seems to function well. A few observations/notes:
- The readme file does not contain instructions for generating the pickle file. i.e `python jobs/regression_minimum.py`
- The deployment needs to be updated to cater for the new changes(I shall followup on this)
Thanks, Noah, I will update that

**Review by Baalmart — COMMENTED** [review]
Hi @Priscilla-AL , please add more details to the PR description. Is the endpoint a POST, GET, PUT? etc?

Thanks.

**Review by lilly-muyama — COMMENTED** [review]
@Priscilla-AL  detailed step-by-step instructions of how to review this PR would be useful.

**Comment by lilly-muyama** [comment]
> @Priscilla-AL detailed step-by-step instructions of how to review this PR would be useful.

Never mind. I've seen them

**Comment by Priscilla-AL** [comment]
> Hi @Priscilla-AL , please add more details to the PR description. Is the endpoint a POST, GET, PUT? etc?
> 
> Thanks.

done!

**Review by lilly-muyama — COMMENTED** [review]
@Priscilla-AL When I run `flask run`, I get this
image

**Review by lilly-muyama — COMMENTED** [review]
Using docker, I get  a missing file error:
image

**Comment by 123MwanjeMike** [comment]
This PR's branch has been stale for 4 months.
Please consider deleting it if it's obsolete to minimise the size of the repo clone.
cc @Priscilla-AL

**Pull request closed without merging**
