### PR TITLE
Refactor device-monitoring

### PR DESCRIPTION
**Pull request by Baalmart**
# Hotfix

**_WHAT DOES THIS PR DO?_**

This PR generally refactors the Device Monitoring microservice with a main focus being put on the Cloud Functions that to support it. Below is an overview of the main tasks that were involved in this refactoring.

It is important to note that 2 new microservices (**device-status** and **device-uptime**) were created where each one was targeting the functionality of the 2 cloud functions for this microservice.

- [x] Makes changes to the file organisation structure of `device-monitoring`

- [x] Device Uptime microservice (A CronJob for calculating the device uptime) 

- [x] Device Status microservice (A CronJob for calculating the device status)

- [x] Adds separation of ENVs to the microservices

**_WHAT JIRA STORY/TASK IS RELATED TO THIS PR?_**
N/A

**_WHAT IS THE LINK TO THE PR BRANCH_**
https://github.com/airqo-platform/AirQo-api/tree/refactor-device-monitoring

**_HOW DO I TEST OUT THIS PR?_**

> device status

`cd AirQo-api/src/device-status`
Using your OS commands, set the python ENV and activate it
install the python dependencies using `pip install -r requirements.txt`
run `python3 app.py --tenant={TENANT}`

> device-uptime

`cd AirQo-api/src/device-uptime`
Using your OS commands, set the python ENV and activate it
install the python dependencies using `pip install -r requirements.txt`
run `python3 app.py --tenant={TENANT}`

> device monitoring

`cd AirQo-api/device-monitoring`
`docker build -t us.gcr.io/airqo-250220/airqo-device-monitoring-api .`
`docker run -d -p 4001:4001 us.gcr.io/airqo-250220/airqo-device-monitoring-api`

**_WHICH ENDPOINTS SHOULD BE READY FOR TESTING?:_** 

> device monitoring

All the endpoints for device monitoring microservice 

**_IS THERE ANY JENKINS CONSOLE LINK FOR CODE COVERAGE AND BUILD INFO?_**
N/A

**_ARE THERE ANY RELATED PRs?_**
N/A

### CODE REVIEW

**Review by danielogen — APPROVED** [review]
LGTM

**Review by ja-odur — APPROVED** [review]
LGTM

**Review by Baalmart — COMMENTED** [review]
The endpoints for device uptime and device status work as expected, awesome. :)

Please review my review notes.... 

@danielogen @ja-odur

**Review by Baalmart — COMMENTED** [review]
All works as expected, just a few comments that I will leave as recommendations in our issues....
Unfortunately, I am not able to approve since I was the one who opened up the PR. Loool!

**Review by lilly-muyama — COMMENTED** [review]
I am unable to run the app.py files for the device-status and device-uptime microservices. I am using the same .env file for both. I get the respective errors

device_status_error
device_uptime error

**Review by Priscilla-AL — COMMENTED** [review]
Am unable to run both Device status and device uptime. Will leave it, for now, might take forever to fix

Error message. Could not install packages due to an EnvironmentError:

**Comment by lilly-muyama** [comment]
> 
> 
> I am unable to run the app.py files for the device-status and device-uptime microservices. I am using the same .env file for both. I get the respective errors
> 
> device_status_error
> device_uptime error

I have managed to resolve the above errors. Now I am getting the error below for device-monitoring
device_monitoring_error

**Review by sserurich — COMMENTED** [review]
All the parts look good, device status, device uptime and monitoring.. except something to do with the order of results returned when the apis for device monitioring are run 
image
image


when I put days = 0 , I could get all the results and I observe results for today, but if i put in say 5, 4 I get results from while a go

**Comment by ja-odur** [comment]
> > I am unable to run the app.py files for the device-status and device-uptime microservices. I am using the same .env file for both. I get the respective errors
> > device_status_error
> > device_uptime error
> 
> I have managed to resolve the above errors. Now I am getting the error below for device-monitoring
> device_monitoring_error

@lilly-muyama your .env file might be missing some keys that are specific to the job

**Comment by ja-odur** [comment]
> All the parts look good, device status, device uptime and monitoring.. except something to do with the order of results returned when the apis for device monitioring are run
> image
> image
> 
> when I put days = 0 , I could get all the results and I observe results for today, but if i put in say 5, 4 I get results from while a go

@sserurich This has been fixed

**Comment by lilly-muyama** [comment]
> 
> 
> @lilly-muyama your .env file might be missing some keys that are specific to the job

I still get the same error about the MONGO_URI Flask config variable

**Review by sserurich — APPROVED** [review]
Issue was fixed, now works as expected.

**Pull request merged**
