### PR TITLE
added gulucity airqloud heatmap

### PR DESCRIPTION
**Pull request by uman95**
**_WHAT DOES THIS PR DO?_**

- Added Gulucity AirQloud to list of AirQlouds with heatmap on the Platform map.

**_HOW DO I TEST OUT THIS PR?_**

- create a virtual environment
- install all requirements, src/gpmodel/requirements.txt
- get the .env and test using development environment (**note that: for the event API we now use .../api/v2/..**)
- run the src/gpmodel/main.py

**_WHICH ENDPOINTS SHOULD BE READY FOR TESTING?:_** 

The [**heatmap** API](https://staging-platform.airqo.net/api/v1/predict/heatmap)

### CODE REVIEW

**Review by wabinyai — APPROVED** [review]
Looks ok

**Review by sserurich — COMMENTED** [review]
the change looks good, don't have any reservation about it.. 
however I ran this on staging and obtained this in the attachment, I understand you advised to use development but currently was in position to test on staging.
image

**Comment by uman95** [comment]
@sserurich This is as a result of TOKEN.

**Review by Mnoble-19 — APPROVED** [review]

**Comment by uman95** [comment]
@Baalmart need this moved to production, it's already merged to staging last week. 
Thanks.

**Pull request merged**
