### PR TITLE
Kafka configurations

### PR DESCRIPTION
**Pull request by NoahNsimbe**
# Kafka configurations

**_WHAT DOES THIS PR DO?_**
- [x] Fixes multiple failures in the pipeline
- [x] Quick fixes for batch jobs
- [x] Transfers Kafka k8s files to the k8s folder
- [x] Refactors code to reduce the number of folders and remove unused applications
- [x] Setups an Istio gateway for schema registry.

**_WHAT JIRA STORY/TASK IS RELATED TO THIS PR?_**
None

**_WHAT IS THE LINK TO THE PR BRANCH_**
[kafka-configurations](https://github.com/airqo-platform/AirQo-api/tree/kafka-configurations)

**_HOW DO I TEST OUT THIS PR?_**
You should be able to setup a complete pipeline on your local machine. 

**_WHICH ENDPOINTS SHOULD BE READY FOR TESTING?:_** 
None

**_IS THERE ANY JENKINS CONSOLE LINK FOR CODE COVERAGE AND BUILD INFO?_**
None

**_ARE THERE ANY RELATED PRs?_**
None

### CODE REVIEW

**Review by Baalmart — COMMENTED** [review]
Great work @NoahNsimbe , great work! Really great! And must be exhausting?!! 

With the motivation of "reusability", could we explore using Helm charts instead of having many config files for different ENVS of the same microservices/jobs? More notes here: https://codefresh.io/helm-tutorial/helm-deployment-environments/

Awaiting your thoughts on this. Thanks again!

**Comment by NoahNsimbe** [comment]
> Great work @NoahNsimbe , great work! Really great! And must be exhausting?!!
> 
> With the motivation of "reusability", could we explore using Helm charts instead of having many config files for different ENVS of the same microservices/jobs? More notes here: https://codefresh.io/helm-tutorial/helm-deployment-environments/
> 
> Awaiting your thoughts on this. Thanks again!

Helm will definitely be of help. I shall look into it next sprint

**Review by danielogen — APPROVED** [review]
This looks good to me

**Review by ja-odur — APPROVED** [review]
LGTM

**Pull request merged**
