### PR TITLE
move to production

### PR DESCRIPTION
**Pull request by Baalmart**
**_WHAT DOES THIS PR DO?_**

- https://github.com/airqo-platform/AirQo-api/pull/1243
- https://github.com/airqo-platform/AirQo-api/pull/1259
- https://github.com/airqo-platform/AirQo-api/pull/1260
- #1252
- https://github.com/airqo-platform/AirQo-api/pull/1248
- https://github.com/airqo-platform/AirQo-api/pull/1261

### CODE REVIEW

**Review by 123MwanjeMike — CHANGES_REQUESTED** [review]
Changes by #1243 are failing in production

**Comment by Baalmart** [comment]
> Changes by #1243 are failing in staging

Thanks @123MwanjeMike for this observation! Will look into it asap.

**Comment by Baalmart** [comment]
> Changes by #1243 are failing in staging

Hi @123MwanjeMike , are you able to share any screenshot of these failures?
The file changes in that PR seem to be straight forward....just schema updates to the Sites entity.

I am happy to learn more of these failures so that I can start the problem solving process.

Thanks again!

**Comment by 123MwanjeMike** [comment]
> > Changes by #1243 are failing in staging
> 
> Hi @123MwanjeMike , are you able to share any screenshot of these failures? The file changes in that PR seem to be straight forward....just schema updates to the Sites entity.
> 
> I am happy to learn more of these failures so that I can start the problem solving process.
> 
> Thanks again!

Let me check via argoCD dashboard to see if I can find them

**Review by 123MwanjeMike — APPROVED** [review]
all is good now @Baalmart

**Comment by Baalmart** [comment]
@NoahNsimbe / @123MwanjeMike .....

I am merging this PR.....

Please be on standby in case of any need for us to do any fire fighting. :)

**Comment by Baalmart** [comment]
@NoahNsimbe / @123MwanjeMike .....

I am merging this PR.....

Please be on standby in case of any need for us to do any fire fighting. :)

**Pull request merged**
