### PR TITLE
enhancements, hotfixes and new endpoints for device (events) registry

### PR DESCRIPTION
**Pull request by Baalmart**
**_WHAT DOES THIS PR DO?_**

- [x] Create the new events endpoints via v2 (NEW)
- [x] Fix existing query issues (HOT FIXES)
- [x] Special requests (NICE TO HAVE)

**_WHAT ISSUES ARE RELATED TO THIS PR?_**

- Jira cards
    - [AN-330]

**_HOW DO I TEST OUT THIS PR?_**
```
cd src/device-registry
npm install
npm run stage-mac
```

**_WHICH ENDPOINTS SHOULD BE READY FOR TESTING?:_** 

NEW ONES:
- [x] [retrieve all the measurements identified by latitude and longitude](https://airqo-engineering.postman.co/workspace/internal~7a8e9fad-2d13-4d27-af27-f1f4e9a114bf/request/12513372-7bc4969e-a2aa-4cf3-ab5c-1ed482ab1280)
- [x] [retrieve all the measurements identified by its deviceId](https://airqo-engineering.postman.co/workspace/internal~7a8e9fad-2d13-4d27-af27-f1f4e9a114bf/request/12513372-dd3055ea-7f56-4989-9358-9a87a8a1f0d5)
- [x] [retrieve all the measurements identified by its airqloudId](https://airqo-engineering.postman.co/workspace/internal~7a8e9fad-2d13-4d27-af27-f1f4e9a114bf/request/12513372-13c69c1d-338b-4338-acdf-077bec36ab7c)
- [x] [retrieve all the measurements identified by its siteId](https://airqo-engineering.postman.co/workspace/internal~7a8e9fad-2d13-4d27-af27-f1f4e9a114bf/request/12513372-ca197fcb-0d69-4f3e-a86d-474caa874d40)

PERFORMANCE IMPROVEMENTS:
- [x] [Get Good AirQuality Measurements](https://airqo-engineering.postman.co/workspace/internal~7a8e9fad-2d13-4d27-af27-f1f4e9a114bf/request/12513372-635e9871-2ade-44e3-8222-5e4c4462ff15)
- [x] [Get Moderate AirQuality Measurements](https://airqo-engineering.postman.co/workspace/internal~7a8e9fad-2d13-4d27-af27-f1f4e9a114bf/request/12513372-5f8a2cfb-035c-46d9-b93c-4af432c49d71)
- [x] [Get U4SG air quality measurements](https://airqo-engineering.postman.co/workspace/internal~7a8e9fad-2d13-4d27-af27-f1f4e9a114bf/request/12513372-71df81d6-4cf0-4063-8cfd-5d72b9ba57db)
- [x] [Get unhealthy air quality measurements](https://airqo-engineering.postman.co/workspace/internal~7a8e9fad-2d13-4d27-af27-f1f4e9a114bf/request/12513372-bc2f8841-2938-42f8-8d45-d1f269e39407)
- [x] [Get hazardous air quality measurements](https://airqo-engineering.postman.co/workspace/internal~7a8e9fad-2d13-4d27-af27-f1f4e9a114bf/request/12513372-bf0acd1d-acb3-4efc-9e00-4705f76be4c2)
- [x] [Get very unhealthy air quality measurements](https://airqo-engineering.postman.co/workspace/internal~7a8e9fad-2d13-4d27-af27-f1f4e9a114bf/request/12513372-509ff92d-e5e2-4ea0-abad-9aafa1cf8c29)
- [ ] [transmit single event](https://airqo-engineering.postman.co/workspace/internal~7a8e9fad-2d13-4d27-af27-f1f4e9a114bf/request/12513372-759e2ecd-2717-4aad-9af3-419497b79a58)
- [ ] [transmit bulk events](https://airqo-engineering.postman.co/workspace/internal~7a8e9fad-2d13-4d27-af27-f1f4e9a114bf/request/12513372-c4afa441-4ed3-4ba9-b9b9-2e1fa44cfb9e)
- [ ] [Get Events V1](https://airqo-engineering.postman.co/workspace/internal~7a8e9fad-2d13-4d27-af27-f1f4e9a114bf/request/12513372-2f1360d4-2eaa-40b7-9ad4-eef1b03abbce)

**_SCREENSHOTS?:_** 
Screenshot 2023-04-14 at 06 30 26

[AN-330]: https://airqoteam.atlassian.net/browse/AN-330?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by NoahNsimbe — COMMENTED** [review]
Hi @Baalmart the API response time is very high. 11 seconds is too much. I suggest we optimise it further

**Comment by Baalmart** [comment]
> Hi @Baalmart the API response time is very high. 11 seconds is too much. I suggest we optimise it further

Sounds good, let me continue to explore more optimisations as we continue with the QA.
Thanks for the timely feedback @NoahNsimbe

**Comment by Baalmart** [comment]
> Hi @Baalmart the API response time is very high. 11 seconds is too much. I suggest we optimise it further

Hi @NoahNsimbe , unfortunately, we can't get it any lower than 9 seconds. See attached screenshot.
I am considering the usage of another database system called Influx which is more optimised for time series data.

A [separate PR](https://github.com/airqo-platform/AirQo-api/pull/1455) has been raised to support another database type in device-registry, but it might take sometime (about a month) before it's QA tests and full setup are completed.

On that note, I suggest that we move forward and utilise as we continue to make things better in the background.

Screenshot 2023-04-15 at 17 10 58

**Comment by Baalmart** [comment]
> > Hi @Baalmart the API response time is very high. 11 seconds is too much. I suggest we optimise it further
> 
> Hi @NoahNsimbe , unfortunately, we can't get it any lower than 9 seconds. See attached screenshot. I am considering the usage of another database system called Influx which is more optimised for time series data.
> 
> A [separate PR](https://github.com/airqo-platform/AirQo-api/pull/1455) has been raised to support another database type in device-registry, but it might take sometime (about a month) before it's QA tests and full setup are completed.
> 
> On that note, I suggest that we move forward and utilise as we continue to make things better in the background.
> 
> Screenshot 2023-04-15 at 17 10 58

Hi @NoahNsimbe :
Additionally, we have also added caching to reduce it to `2 (two) seconds` response time when the user access the endpoint within a window of 30 minutes. See attached screenshot.
Screenshot 2023-04-15 at 17 33 34

**Pull request merged**
