### PR TITLE
[DP-171] Predict Job Maintenance

### PR DESCRIPTION
**Pull request by danielogen**
# Predict Job Maintenance

**_WHAT DOES THIS PR DO?_**
- Perform maintenances on the predict job 
- Restrict the version of LightGBM model 
- Introduce staging bucket
- Small code clean up
- Update Dockerfile (use single dockerfile for various environments)

**_WHAT JIRA STORY/TASK IS RELATED TO THIS PR?_**
- [DP-171]

**_HOW DO I TEST OUT THIS PR?_**
- Checkout this PR, create a python virtual environment (`python3 -m venv env`) and install the necessary packages (`pip install -r requirements.txt`). *Set the environment in the `.env` file to `staging` and run `python main.py`.

- If you have docker, simply run `docker build -t <image_name> --target=staging .`. Wait for the build process to complete and then run `docker run -it <image_name>`

NB: 
- `.env` and service account key is available [here](https://drive.google.com/drive/u/1/folders/17BONK5SU6q2fPe3sclkxC11v0OjEUBjr)
- Results are stored in the `airqo_netmanager` and `airqo_netmanager_staging` for production and staging respectively.

**_WHICH ENDPOINTS SHOULD BE READY FOR TESTING?:_** 
- None

**_IS THERE ANY JENKINS CONSOLE LINK FOR CODE COVERAGE AND BUILD INFO?_**

N/A

**_ARE THERE ANY RELATED PRs?_**

N/A

[DP-171]: https://airqoteam.atlassian.net/browse/DP-171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by NoahNsimbe** [comment]
@danielogen please help with the `.env` file location

**Comment by danielogen** [comment]
> @danielogen please help with the `.env` file location

https://drive.google.com/drive/u/1/folders/17BONK5SU6q2fPe3sclkxC11v0OjEUBjr

**Review by NoahNsimbe — COMMENTED** [review]
@danielogen getting a few errors
Screenshot 2022-03-11 at 19 32 35

**Comment by danielogen** [comment]
> @danielogen getting a few errors. Using GCP Cloud shell
> 
> Screenshot 2022-03-11 at 19 32 35
> 
> 

Oh, I have just remembered that the staging bucket is based on a different model. If you run this PR on production it should work just fine 🙏.

**Comment by NoahNsimbe** [comment]
> > @danielogen getting a few errors. Using GCP Cloud shell
> > Screenshot 2022-03-11 at 19 32 35
> 
> Oh, I have just remembered that the staging bucket is based on a different model. If you run this PR on production it should work just fine 🙏.

HI @danielogen, I have tested with production and it works. Is it possible to first have this job run perfectly on staging before migrating to production?

**Comment by danielogen** [comment]
> 



> > > @danielogen getting a few errors. Using GCP Cloud shell
> > > Screenshot 2022-03-11 at 19 32 35
> > 
> > 
> > Oh, I have just remembered that the staging bucket is based on a different model. If you run this PR on production it should work just fine 🙏.
> 
> HI @danielogen, I have tested with production and it works. Is it possible to first have this job run perfectly on staging before migrating to production?

Sound cool @NoahNsimbe, so if you test it again now, should work on staging environment as well

**Review by NoahNsimbe — APPROVED** [review]
Many thanks @danielogen

**Review by sserurich — APPROVED** [review]
Looks  good, and the code  improvements are great
image

**Pull request merged**
