### PR TITLE
Readme edit

### PR DESCRIPTION
**Pull request by Psalmz777**
**_WHAT DOES THIS PR DO?_**

**_WHAT ISSUES ARE RELATED TO THIS PR?_**

- Jira cards
    - []()
- GitHub issues
    - Closes #<enter GitHub issue number here>

**_HOW DO I TEST OUT THIS PR?_**

**_WHICH ENDPOINTS SHOULD BE READY FOR TESTING?:_** 

**_IS THERE ANY JENKINS CONSOLE LINK FOR CODE COVERAGE AND BUILD INFO?_**

**_ARE THERE ANY RELATED PRs?_**

### CODE REVIEW

**Review by Baalmart — COMMENTED** [review]
Hi @Psalmz777 , could we also use the same PR to add the rest of the missing "microservices". 

Examples:

- Airflow
- metadata
- etc

**Comment by Psalmz777** [comment]
> Hi @Psalmz777 , could we also use the same PR to add the rest of the missing "microservices".
> 
> Examples:
> 
>     * Airflow
> 
>     * metadata
> 
>     * etc

Alright @Baalmart

**Comment by Baalmart** [comment]
Hi @Psalmz777 , how are we doing here?

**Review by Baalmart — COMMENTED** [review]
Hi @Psalmz777 , hope the PR is going strong?
Just wanted to highlight another PR where one of our microservices (airflow) is being renamed. You will want to be able to keep track of that and perhaps keep this a WIP until then? Anyway, please share suggestions accordingly. That PR is here: https://github.com/airqo-platform/AirQo-api/pull/2312

**Comment by Psalmz777** [comment]
> Hi @Psalmz777 , hope the PR is going strong? Just wanted to highlight another PR where one of our microservices (airflow) is being renamed. You will want to be able to keep track of that and perhaps keep this a WIP until then? Anyway, please share suggestions accordingly. That PR is here: #2312

Hi @Baalmart I will leave it as WIP until I'm done mlflow too

**Pull request closed without merging**
