### PR TITLE
App Insights API

### PR DESCRIPTION
**Pull request by NoahNsimbe**
# Feature

**_WHAT DOES THIS PR DO?_**

- [x] Exposes and API for querying App Insights
- [x] Replaces ongoing works in #614 

**_WHAT JIRA STORY/TASK IS RELATED TO THIS PR?_**
[MOB-7](https://airqoteam.atlassian.net/browse/MOB-7)
[MOB-42](https://airqoteam.atlassian.net/browse/MOB-42)

**_WHAT IS THE LINK TO THE PR BRANCH_**
[ft-app-insights-api](https://github.com/airqo-platform/AirQo-api/tree/ft-app-insights-api)

**_HOW DO I TEST OUT THIS PR?_**
Follow instructions in the [README.md file](https://github.com/airqo-platform/AirQo-api/tree/ft-app-insights-api/src/view#running-the-application)

**_WHICH ENDPOINTS SHOULD BE READY FOR TESTING?:_** 
[Get App Insights](https://app.gitbook.com/o/-MCogOVGQqjUharJKchL/s/-MKqyQkcfs54GYi-q96G/view-api)

**_IS THERE ANY JENKINS CONSOLE LINK FOR CODE COVERAGE AND BUILD INFO?_**
None

**_ARE THERE ANY RELATED PRs?_**
None

### CODE REVIEW

**Review by Baalmart — COMMENTED** [review]
These are some powerful introductions.  Thanks @NoahNsimbe 
However, we might need a team walk through since there are so many changed files.
Could you organise some sort of workshops for these PRs with many changed files?

**Comment by NoahNsimbe** [comment]
> These are some powerful introductions. Thanks @NoahNsimbe However, we might need a team walk through since there are so many changed files. Could you organise some sort of workshops for these PRs with many changed files?

We can have a walk through during one of our standups. I suggest we merge this for now because the next release to production (early next) relies on functionality in here. The changed files are multiple because I am setting up the API

**Review by 123MwanjeMike — APPROVED** [review]
Great work @NoahNsimbe 
LGTM

**Review by Baalmart — APPROVED** [review]
LGTM

**Pull request merged**
