### PR TITLE
Mob 91 backing up the user data

### PR DESCRIPTION
**Pull request by BenjaminSsempala**
**_WHAT DOES THIS PR DO?_**
This PR includes the implementation of a google Cloud function that initiates a Cloud Firestore data export to back up user data from firebase to GCP.  

**_WHAT ISSUES ARE RELATED TO THIS PR?_**
- Jira cards
    - [MOB-91](https://airqoteam.atlassian.net/browse/MOB-91?atlOrigin=eyJpIjoiYmY2NGNlZDNiMGRkNDI5ZGI2NWZjZTdmY2E1OWM3NzkiLCJwIjoiaiJ9) 
- GitHub issues
    - Closes #<enter GitHub issue number here>

**_HOW DO I TEST OUT THIS PR?_**
-Review the [Scheduled firestore Export function](https://console.firebase.google.com/u/1/project/airqo-250220/functions?consoleUI=FIREBASE) on the firebase console, or on the [GCP console](https://console.cloud.google.com/cloudscheduler/jobs/edit/us-central1/firebase-schedule-scheduledFirestoreExport-us-central1?authuser=1&project=airqo-250220)
-Look through the code to provide feedback.

**_WHICH ENDPOINTS SHOULD BE READY FOR TESTING?:_** 

**_IS THERE ANY JENKINS CONSOLE LINK FOR CODE COVERAGE AND BUILD INFO?_**

**_ARE THERE ANY RELATED PRs?_**

### CODE REVIEW

**Review by 123MwanjeMike — CHANGES_REQUESTED** [review]
Thanks @BenjaminSsempala 
I see the `src/firebase/backup/package-lock.json` file has no corresponding package.json file. Could we have this removed since there's already another package-lock.json file in functions directory that has a corresponding package.json file

**Comment by BenjaminSsempala** [comment]
Thank you @123MwanjeMike 
I've resolved that now.

> Thanks @BenjaminSsempala I see the `src/firebase/backup/package-lock.json` file has no corresponding package.json file. Could we have this removed since there's already another package-lock.json file in functions directory that has a corresponding package.json file

**Review by 123MwanjeMike — APPROVED** [review]
Thanks @BenjaminSsempala 
LGTM

**Comment by NoahNsimbe** [comment]
Hi @BenjaminSsempala, please add a README file

**Review by Mnoble-19 — APPROVED** [review]
LGTM

**Pull request merged**
