### PR TITLE
Ft location registry tenancy

### PR DESCRIPTION
**Pull request by lilly-muyama**
- What does this PR do?
This PR adds multi-tenancy to the location-registry microservice.
- What JIRA task is related to this PR?
The link to the JIRA board task is [here](https://airqoteam.atlassian.net/jira/software/projects/PLAT/boards/41?selectedIssue=PLAT-73).
- How do I test out this PR?
Git clone this repo `cd AirQo-api/src/location-registry` . And then run the following docker commands
`docker build -t us.gcr.io/airqo-250220/airqo-location-registry-api .` and `docker run -p 4000:8080 us.gcr.io/airqo-250220/airqo-location-registry-api`
- Which end points should are ready for testing?
All endpoints as shown [in this documentation](https://docs.google.com/spreadsheets/d/1-NGTDBtTcIi8Fg2UYSWjcK6geKrZdopz5kxRFsCEMPs/edit#gid=1270588885) You just need to add the tenant parameter to each url e.g. http://localhost:4000/api/v1/location_registry/create_id?tenant=kcca

Be sure to get the latest .env file

### CODE REVIEW

**Review by Baalmart — COMMENTED** [review]
Thanks @lilly-muyama 
I am somehow unable to run it using Docker....

- Tried running it using **GET locations** endpoint and was not successful , nothing was happening - was getting service request error as shown in screenshots.
- Also, what is the request body for /create_id [GET]?

image

image

**Comment by lilly-muyama** [comment]
> 
> 
> Thanks @lilly-muyama
> I am somehow unable to run it using Docker....
> 
>     * Tried running it using **GET locations** endpoint and was not successful , nothing was happening - was getting service request error as shown in screenshots.
> 
>     * Also, what is the request body for /create_id [GET]?
> 
> 
> image
> 
> image

There is no request body for the create_id endpoint. I hadn't used docker to test it. Let me check and see.

**Review by danielogen — APPROVED** [review]
Working well. Some [near] future recommendations: Adopting the DRY principle and separation of environments [dev, stage and production]

**Review by Baalmart — COMMENTED** [review]
I am now able to access Google services, thank God! I have also imported the location data for airqo and kcca into their respective databases. 
- Things are working as expected for get location details endpoint, the create_id endpoint
- So we need to do more error handling, the endpoints always return values even without a tenant specified. See screenshot
- Get details of location to be edited always returns the error respomse
- Secondly, getting the same response for different tenants, see screenshots below. LOCATIONS [GET]
- 
image

image

image

**Comment by lilly-muyama** [comment]
> 
> 
> I am now able to access Google services, thank God! I have also imported the location data for airqo and kcca into their respective databases.
> 
>     * Things are working as expected for get location details endpoint, the create_id endpoint
> 
>     * So we need to do more error handling, the endpoints always return values even without a tenant specified. See screenshot
> 
>     * Get details of location to be edited always returns the error respomse
> 
>     * Secondly, getting the same response for different tenants, see screenshots below. LOCATIONS [GET]
> 
> 
> image
> 
> image
> 
> image

All of these have been addressed.

**Review by Baalmart — CHANGES_REQUESTED** [review]
Thanks, the `Get all locations` works as expected, also returns responses fast.

- [ ] the endpoint for create location ID is confusing me, could be missing something - relating it to a GET is confusing. What is the real purpose of this endpoint?

- [ ] Still on the same endpoint [create location id], works well with airqo tenant but brings an error message when a different tenant is used 

- [ ] could we make that error message in JSON (from HTML) in an appropriate format that includes the cause of the error 

- [ ] Error handling, we can also be able to share the exact cause of an error in our response message. Resource: https://flask.palletsprojects.com/en/master/errorhandling/#:~:text=When%20an%20error%20occurs%20in,user%20when%20an%20error%20occurs. 

- [ ] We also need to separate our environments. The reviewers should be able to switch between different environments easily using different run commands perhaps? You could specify the different run commands (configuration objects) in classes and change ENVs at runtime accordingly.
Resources:
1. https://stackoverflow.com/questions/44951244/flask-production-and-development-mode
2. https://kelvinmwinuka.com/organising-flask-configurations/ 

- [ ] For non existent endpoints, could we return informative JSON responses? 

- [ ] Register Location endpoint - error response is not descriptive for non existent tenant - same case for existing tenant name - guess we need to handle cases where the user forgets to provide a request body, give them an appropriate JSON error response perhaps? - this particular endpoint also takes extremely long to finish execution. 

- [ ] Get details of location works as expected. Just that when a user forgets to enter the tenant AND when they enter a non existent tenant ID, they get the same error message reponse, we could try to differentiate the response for those two scenarios using appropriate error status codes and reponses. Same case for non existent location names ---all these three scenarios return the same error response. 

- [ ] For update Location, please change the HTTP verb to PUT instead of POST. Also, could we return the details of the updated location? 

- [ ] Get details of a location to be edited - As for this endpoint, we shall want to consider avoiding this network call - what if all the location details are loaded on user signin using redux and then a location's details are also picked from state. We shall also want to use a more appropriate HTTP verb (PUT) for all scenarios of updating and editing records. Otherwise, the endpoint works as expected. One last thing, what is the difference between this endpoint and "GET details of a location"? Lastly, we need to review the error responses as shared above.

**Review by Priscilla-AL — COMMENTED** [review]
The view function did not return a valid response. The function either returned None or ended without a return statement.

**Review by ja-odur — APPROVED** [review]
Tested all `GET` endpoints and works perfectly

**Comment by lilly-muyama** [comment]
> 
> 
> Thanks, the `Get all locations` works as expected, also returns responses fast.
> 
>     * [ ]  the endpoint for create location ID is confusing me, could be missing something - relating it to a GET is confusing. What is the real purpose of this endpoint?
> 
>     * [ ]  Still on the same endpoint [create location id], works well with airqo tenant but brings an error message when a different tenant is used
> 
>     * [ ]  could we make that error message in JSON (from HTML) in an appropriate format that includes the cause of the error
> 
>     * [ ]  Error handling, we can also be able to share the exact cause of an error in our response message. Resource: https://flask.palletsprojects.com/en/master/errorhandling/#:~:text=When%20an%20error%20occurs%20in,user%20when%20an%20error%20occurs.
> 
>     * [ ]  We also need to separate our environments. The reviewers should be able to switch between different environments easily using different run commands perhaps? You could specify the different run commands (configuration objects) in classes and change ENVs at runtime accordingly.
>       Resources:
> 
> 
>     1. https://stackoverflow.com/questions/44951244/flask-production-and-development-mode
> 
>     2. https://kelvinmwinuka.com/organising-flask-configurations/
> 
> 
>     * [ ]  For non existent endpoints, could we return informative JSON responses?
> 
>     * [ ]  Register Location endpoint - error response is not descriptive for non existent tenant - same case for existing tenant name - guess we need to handle cases where the user forgets to provide a request body, give them an appropriate JSON error response perhaps? - this particular endpoint also takes extremely long to finish execution.
> 
>     * [ ]  Get details of location works as expected. Just that when a user forgets to enter the tenant AND when they enter a non existent tenant ID, they get the same error message reponse, we could try to differentiate the response for those two scenarios using appropriate error status codes and reponses. Same case for non existent location names ---all these three scenarios return the same error response.
> 
>     * [ ]  For update Location, please change the HTTP verb to PUT instead of POST. Also, could we return the details of the updated location?
> 
>     * [ ]  Get details of a location to be edited - As for this endpoint, we shall want to consider avoiding this network call - what if all the location details are loaded on user signin using redux and then a location's details are also picked from state. We shall also want to use a more appropriate HTTP verb (PUT) for all scenarios of updating and editing records. Otherwise, the endpoint works as expected. One last thing, what is the difference between this endpoint and "GET details of a location"? Lastly, we need to review the error responses as shared above.

@Baalmart I have handled most of these where applicable. Please re-review and let me know if you have any additional comments.

**Review by Baalmart — APPROVED** [review]
Good

**Pull request merged**
