### PR TITLE
[nginx ingress] Update Locate Path

### PR DESCRIPTION
**Pull request by danielogen**
# Update Locate Path

**_WHAT DOES THIS PR DO?_**
- Updates locate path in nginx ingress files

**_WHAT JIRA STORY/TASK IS RELATED TO THIS PR?_**
- N/A

**_HOW DO I TEST OUT THIS PR?_**
- N/A

**_WHICH ENDPOINTS SHOULD BE READY FOR TESTING?:_** 
- N/A

**_IS THERE ANY JENKINS CONSOLE LINK FOR CODE COVERAGE AND BUILD INFO?_**

N/A

**_ARE THERE ANY RELATED PRs?_**
- https://github.com/airqo-platform/AirQo-api/pull/165

### CODE REVIEW

**Comment by NoahNsimbe** [comment]
@danielogen does the frontend use this API..?.If so, Have the frontend Engineers been informed of the update??

**Comment by NoahNsimbe** [comment]
@danielogen the documentation might require updating before or after the PR is merged.
https://app.gitbook.com/o/-MCogOVGQqjUharJKchL/s/-MKqyQkcfs54GYi-q96G/locate

**Comment by danielogen** [comment]
> @danielogen does the frontend use this API..?.If so, Have the frontend Engineers been informed of the update??

Yes, frontend use this API, this will be informed as soon as the API documentation is updated. This currently beginning worked on

**Comment by danielogen** [comment]
> @danielogen the documentation might require updating before or after the PR is merged. https://app.gitbook.com/o/-MCogOVGQqjUharJKchL/s/-MKqyQkcfs54GYi-q96G/locate

Here is the updated documentation https://docs.google.com/spreadsheets/d/1-NGTDBtTcIi8Fg2UYSWjcK6geKrZdopz5kxRFsCEMPs/edit#gid=562835484. 
I am currently moving it to gitbooks

**Review by NoahNsimbe — COMMENTED** [review]
LGTM

**Review by NoahNsimbe — APPROVED** [review]

**Comment by danielogen** [comment]
UPDATED DOCUMENTATION: https://app.gitbook.com/o/-MCogOVGQqjUharJKchL/s/-MKqyQkcfs54GYi-q96G/locate

**Review by Baalmart — APPROVED** [review]
LGTM

**Pull request merged**
