### PR TITLE
merge staging into production

### PR DESCRIPTION
**Pull request by Baalmart**
# merge staging into production

**_WHAT DOES THIS PR DO?_**
merge staging into production.

### CODE REVIEW

**Review by danielogen — APPROVED** [review]
LGTM

**Comment by Baalmart** [comment]
But wait a second. @danielogen , I do not see any file changes for the auth service as to regards to this issue [358](https://github.com/airqo-platform/AirQo-api/issues/358) which is only appearing in the production environment and **not** the staging environment.

So this means that we need to examine this issue more.

**Comment by danielogen** [comment]
> But wait a second. @danielogen , I do not see any file changes for the auth service as to regards to this issue [358](https://github.com/airqo-platform/AirQo-api/issues/358) which is only appearing in the production environment and **not** the staging environment.
> 
> 
> 
> So this means that we need to examine this issue more.

True, I also had the same observation but I thought I might be missing something!

**Review by danielogen — APPROVED** [review]
LGTM

**Pull request merged**
