### PR TITLE
Add docs redirect for mobile app privacy policy

### PR DESCRIPTION
**Pull request by 123MwanjeMike**
**_WHAT DOES THIS PR DO?_**
- Adds docs redirect for mobile app privacy policy

**_WHAT ISSUES ARE RELATED TO THIS PR?_**
- [PLATOPS-44](https://airqoteam.atlassian.net/browse/PLATOPS-44?atlOrigin=eyJpIjoiMDVlNzlhMmM4NjI5NGE4OThkMzBlMmI0ZTNhOTIzN2MiLCJwIjoiaiJ9)

**_HOW DO I TEST OUT THIS PR?_**
- Checkout https://staging-docs.airqo.net/airqo-application-documentations/
- You will be redirected to https://staging-docs.airqo.net/#/mobile_app/privacy_policy automatically

**_WHICH ENDPOINTS SHOULD BE READY FOR TESTING?:_** 
- /airqo-application-documentations/

**_IS THERE ANY JENKINS CONSOLE LINK FOR CODE COVERAGE AND BUILD INFO?_**
- n/a

**_ARE THERE ANY RELATED PRs?_**
- n/a

### CODE REVIEW

**Review by NoahNsimbe — APPROVED** [review]
LGTM

**Review by Baalmart — APPROVED** [review]
LGTM, thanks @123MwanjeMike

**Comment by Baalmart** [comment]
Hi @123MwanjeMike , could we attempt to seek out any other documentations that might be affected? I sense the concern is not just for the mobile application?
Thanks again!

**Comment by 123MwanjeMike** [comment]
Hi @Baalmart 
Kindly share some of these endpoints.
So far, whenever I access docs.airqo.net, I only get redirected to https://docs.airqo.net/airqo-application-documentations/ which makes me believe its the only route.
Kindly guide me here.

cc @NoahNsimbe

**Comment by Baalmart** [comment]
> Hi @Baalmart Kindly share some of these endpoints. So far, whenever I access docs.airqo.net, I only get redirected to https://docs.airqo.net/airqo-application-documentations/ which makes me believe its the only route. Kindly guide me here.
> 
> cc @NoahNsimbe

Hi @123MwanjeMike , please check my most recent forwarded email with the subject: **[Production Documentations] Fwd: Welcome to the AirQo Platform**

**Comment by 123MwanjeMike** [comment]
Well received.
Thanks again @Baalmart

**Pull request merged**
