### PR TITLE
Reimplement Site Registry

### PR DESCRIPTION
**Pull request by Baalmart**
# Reimplement Site Registry within Device Registry following the recent Site-CheckIn use case

**_WHAT DOES THIS PR DO?_**

- [x] Adds Site registry to the process of Device deployment
- [x] Introduces "new" unique Site identifiers/attributes. These unique site identifiers are `lat_long`, `id`, `generated_name` and `formatted_name`
- [x] During new Site creation, background process generates additional Site Information utilising the GPS coordinates provided.
- [x] Introduces a new collection (settings) for the storage of system wide settings. But not yet in active usage.

**_WHAT JIRA STORY/TASK IS RELATED TO THIS PR?_**
[PLAT-495]

**_WHAT IS THE LINK TO THE PR BRANCH_**
https://github.com/airqo-platform/AirQo-api/tree/reimplement-site-registry

**_HOW DO I TEST OUT THIS PR?_**
`cd AirQo-api/src/device-registry`
`npm install`
 `npm test` for unit tests
`npm run dev-mac` for Linux OR `npm run dev-pc` for Windows
The latest` .env` file is[ here.](https://docs.google.com/document/d/1R0ux6i4WaK-NssVQE_9IcTxfUs3ZYIUhSP1Aa7s_hqg/edit?usp=sharing)
To get some data into your local Dev  environment, please visit the Staging DB for AirQo and export the following collections into your development DB:
- devices
- sites
- activities

**_WHICH ENDPOINTS SHOULD BE READY FOR TESTING?:_** 

- [x] Deploy device
- [x] Recall device
- [x] Get Sites
- [x] Create Site
- [x] Update Site
- [x] Delete Site
- [x] Get Activity
- [x] Update Activity
- [x] Delete Activity

(1.) [`GET Sites`] http://localhost:3000/api/v1/devices/sites?tenant=airqo&lat_long=-0.265089_30.106887
Here, you can use any of the unique identifiers (`id, generated_name, lat_long`) as the query parameter.

_List of optional query parameters:_

```
-   lat_long,
-   id,
-   generated_name,
-   district,
-   region,
-   city,
-   street,
-   country,
-   parish,
-   name
```

(2.) [`DELETE Site`]  http://localhost:3000/api/v1/devices/sites?tenant=airqo&lat_long=0.224264_33.55948
Here, you can use any of the unique identifiers (`id, generated_name, lat_long`) as the query parameter.

(3.) [`PUT Site`]  http://localhost:3000/api/v1/devices/sites?tenant=airqo&lat_long=0.347014_32.6493
Here, you can use any of the unique identifiers (`id, generated_name, lat_long`) as the query parameter.
In case you want to remove site tags, use: `remove_site_tags: ["tag1", "tag2"]`
In case you want to add site tags, use: `add_site_tags:["tag1","tag2"]` as shown in the exampled below.
_BODY:_
```
{
    "latitude": 0.224264,
    "longitude": 33.55948,
    "name": "yeye_updatedThreed",
    "add_site_tags":["tag1","tag2"],

}
```
(4.) [`POST Site`]  http://localhost:3000/api/v1/devices/sites?tenant=airqo
_BODY:_
```
{
    "latitude": 0.2244264,
    "longitude": 33.5569948,
    "name": "yeyt",
    "site_tags":["tag1","tag2","tag3"]
}
```
(5.) [`DEPLOY  DEVICE`] POST: http://localhost:3000/api/v1/devices/activities/deploy?tenant=airqo&deviceName={DEVICE NAME}
_BODY:_
```
{
    "deviceName": "{DEVICE NAME}",
    "height": 23,
    "mountType": "wall",
    "powerType": "solar",
    "date": "2021-03-07T16:09:24.611Z",
    "latitude": "0.354723",
    "longitude": "32.5026232",
    "isPrimaryInLocation": false,
    "isUsedForCollocation": true,
    "site_id": "{SITE_OBJECT_ID}"
}
```

(6.) [`RECALL DEVICE`] POST: http://localhost:3000/api/v1/devices/activities/recall?tenant=airqo&deviceName={DEVICE NAME}

(7.) [`GET ACTIVITIES`] GET: http://localhost:3000/api/v1/devices/activities?tenant=airqo&id={OBJECT ID}
_List of optional query parameters:_
 
```

- device,
- id,
- activity_type,
- activity_tags,
- maintenance_type,

```

(8.) [`DELETE ACTIVITY`] DELETE: http://localhost:3000/api/v1/devices/activities?tenant=airqo&id={OBJECT ID}

(9.) [`UPDATE ACTIVITY`] PUT: http://localhost:3000/api/v1/devices/activities?tenant=airqo&id={OBJECT ID}
_BODY:_
For the tags, you can either use: `remove_tags` or `add_tags` to perform the corresponding actions accordingly. Both of them cannot be used at once. And both take in arrays. Validation will be added in due course in subsequent PRs I guess, this PR is getting large.
```
{
    "location": "location",
    "device": "devicetomoto",
    "date": "",
    " description": "",
    "activityType": "recallment",
    "nextMaintenance": "",
    "remove_tags": ["kikaka" ]
}
```

**_IS THERE ANY JENKINS CONSOLE LINK FOR CODE COVERAGE AND BUILD INFO?_**
N/A

**_ARE THERE ANY RELATED PRs?_**
N/A

[PLAT-495]: https://airqoteam.atlassian.net/browse/PLAT-495

### CODE REVIEW

**Comment by NoahNsimbe** [comment]
Use `id` for delete and put requests.

**Review by ja-odur — COMMENTED** [review]
@Baalmart I have tested this PR and these are my findings
- Both device and site `GET` endpoints return site and device information respectively
- The update endpoint works as expected
I did not test create and delete endpoints at the moment but will do at in a moment.

**Observation/feedback**
- The `PUT`, `DELETE` endpoints use only `lat-long` for site identification, could we use the mongo generated id instead or atleast both.
- I realised we can update the `longitude` and `latitude` of a given site, would this be an equivalent to moving a site a new location. I think we can put some restriction on when and how longitude and latitude of a site can be edited.
- I realised in most of the request body we are using `lat` and `long` keys yet the responses are `latitude` and `longitude`, maybe for consistency we could use the full names for request body keys.

**Review by NoahNsimbe — COMMENTED** [review]
Works as expected, Just a few comments left by @ja-odur that need to be addressed.

**Comment by Baalmart** [comment]
Thanks for the feedback, I will be addressing the feedback in a few.... @ja-odur 
> @Baalmart I have tested this PR and these are my findings
> 
> * Both device and site `GET` endpoints return site and device information respectively
> * The update endpoint works as expected
>   I did not test create and delete endpoints at the moment but will do at in a moment.
> 
> **Observation/feedback**
> 
> * The `PUT`, `DELETE` endpoints use only `lat-long` for site identification, could we use the mongo generated id instead or atleast both.
> * I realised we can update the `longitude` and `latitude` of a given site, would this be an equivalent to moving a site a new location. I think we can put some restriction on when and how longitude and latitude of a site can be edited.
> * I realised in most of the request body we are using `lat` and `long` keys yet the responses are `latitude` and `longitude`, maybe for consistency we could use the full names for request body keys.

**Comment by Baalmart** [comment]
@NoahNsimbe  , this has been done.
> Use `id` for delete and put requests.

**Comment by Baalmart** [comment]
All feedback has been addressed as suggested, please go ahead and test. @ja-odur 
> Thanks for the feedback, I will be addressing the feedback in a few.... @ja-odur
> 
> > @Baalmart I have tested this PR and these are my findings
> > 
> > * Both device and site `GET` endpoints return site and device information respectively
> > * The update endpoint works as expected
> >   I did not test create and delete endpoints at the moment but will do at in a moment.
> > 
> > **Observation/feedback**
> > 
> > * The `PUT`, `DELETE` endpoints use only `lat-long` for site identification, could we use the mongo generated id instead or atleast both.
> > * I realised we can update the `longitude` and `latitude` of a given site, would this be an equivalent to moving a site a new location. I think we can put some restriction on when and how longitude and latitude of a site can be edited.
> > * I realised in most of the request body we are using `lat` and `long` keys yet the responses are `latitude` and `longitude`, maybe for consistency we could use the full names for request body keys.

**Review by ja-odur — COMMENTED** [review]
I am getting this error while trying to create a site
image

**Review by ja-odur — COMMENTED** [review]
@Baalmart This might have slipped in. Trying to deploy a device without specifying `site_id` throw a validation error. I believe no changes are intended to be made in the deploy logic in ths PR.
image

**Comment by Baalmart** [comment]
Thanks, let me review, let me review and act accordingly. @ja-odur 
> @Baalmart This might have slipped in. Trying to deploy a device without specifying `site_id` throw a validation error. I believe no changes are intended to be made in the deploy logic in this PR.
> image

**Comment by ja-odur** [comment]
@Baalmart I am getting new error when creating a site

image

**Comment by Baalmart** [comment]
let me check, was actually preocuppied with deployment/recall and forgot to check out the issue you raised around creating a site. Give me some few....
> @Baalmart I am getting new error when creating a site
> 
> image

**Comment by Baalmart** [comment]
@ja-odur , resolved. Please proceed with your tests! :)
> @Baalmart I am getting new error when creating a site
> 
> image

**Review by ja-odur — APPROVED** [review]
LGTM

**Review by danielogen — APPROVED** [review]
Working well for me.

**Pull request merged**
