### PR TITLE
Collocation APIs

### PR DESCRIPTION
**Pull request by NoahNsimbe**
**_WHAT DOES THIS PR DO?_**
First version of the collocation APIs
**_WHAT ISSUES ARE RELATED TO THIS PR?_**

- Jira cards
    - []()
- GitHub issues
    - Closes #<enter GitHub issue number here>

**_HOW DO I TEST OUT THIS PR?_**

**_WHICH ENDPOINTS SHOULD BE READY FOR TESTING?:_** 
[Device Collocation endpoints](https://airqo-engineering.postman.co/workspace/internal~7a8e9fad-2d13-4d27-af27-f1f4e9a114bf/request/12513372-194eb76f-4204-411f-879c-0548a8edeca4)

**_IS THERE ANY JENKINS CONSOLE LINK FOR CODE COVERAGE AND BUILD INFO?_**

**_ARE THERE ANY RELATED PRs?_**

### CODE REVIEW

**Review by NsubugaAnold — APPROVED** [review]

**Comment by 123MwanjeMike** [comment]
Hi @Baalmart , I notice two slashes(`//`) in the url you are using.

**Comment by Baalmart** [comment]
Thanks @123MwanjeMike but even after correcting that, still same outcome.

**Comment by NoahNsimbe** [comment]
Thanks @Baalmart @123MwanjeMike . The deploy preview has some issues. I failed to identify them. What are going to do is;
1. update the README of the microservice to incorporate instructions on how to run the API. 
2. have a sync with @123MwanjeMike on its issues.

**Comment by Baalmart** [comment]
Thanks @123MwanjeMike but even after correcting that, still same outcome.

**Review by wabinyai — APPROVED** [review]
Looks good

**Review by Baalmart — APPROVED** [review]
All working nicely! Thanks @NoahNsimbe !

**Pull request merged**
