### PR TITLE
api gateway using nginx and haproxy

### PR DESCRIPTION
**Pull request by danielogen**
# Ingress and api gateway routes 

**_WHAT DOES THIS PR DO?_**
This PR introduces backend service routing for API gateway utilization

**_WHAT JIRA STORY/TASK IS RELATED TO THIS PR?_**
[PLAT-99](https://airqoteam.atlassian.net/browse/PLAT-99)
[PLAT-132](https://airqoteam.atlassian.net/browse/PLAT-132)

**_WHAT IS THE LINK TO THE PR BRANCH_**
https://github.com/airqo-platform/AirQo-frontend/tree/api-gateway

**_HOW DO I TEST OUT THIS PR?_**
Using endpoint of your choice, test endpoints of `location_registry`, `auth`, `device-registry` using the following base URL:
`http://staging-platform.airqo.net/api/v1/....` or `http://platform.airqo.net/api/v1/....`

**_WHICH ENDPOINTS SHOULD BE READY FOR TESTING?:_** 
All endpoints for `location_registry`, `auth`, `predict`, `incentives`, `data-mgt` and `device-registry`. 

**_IS THERE ANY JENKINS CONSOLE LINK FOR CODE COVERAGE AND BUILD INFO?_**
N/A

**_ARE THERE ANY RELATED PRs?_**
N/A

### CODE REVIEW

**Review by lilly-muyama — COMMENTED** [review]
I get Bad Gateway for any endpoint I am testing
Capture

**Comment by sserurich** [comment]
> I get Bad Gateway for any endpoint I am testing
> Capture

got the same with staging, and @danielogen  is aware rectifying it. the one for the platform.airqo.net I checked returned results successfully.

**Comment by danielogen** [comment]
Hi @lilly-muyama and @sserurich, things should be working now. Kindly remember to include the `tenant` parameter in the endpoint for the respective microservices. Regards!

**Review by lilly-muyama — APPROVED** [review]
LGTM

**Review by Priscilla-AL — APPROVED** [review]
looks good

**Review by sserurich — APPROVED** [review]
the endpoints that were previously throwing bad gate way error are now working fine on staging-platform sub domain.

**Pull request merged**
