### PR TITLE
[deviceStatus] Fix alternator powerType visibility

### PR DESCRIPTION
**Pull request by ja-odur**
#### Summary of Changes (What does this PR do?)
- update job to handle alternator powerType

#### Is this change ready to hit production in its current state?
- [x] Yes
- [ ] No

#### Status of maturity (all need to be checked before merging):

- [x] I consider this code done
- [ ] I've tested this locally
- [ ] This branch has been LGTM'ed by a reviewer

#### How should this be manually tested?
* Set the `.env` file for `device-status` micro-service. Here is the [.env](https://drive.google.com/file/d/1drLA_eh489BIxCO3iccbQSzZMZuxre_C/view?usp=sharing)
* Run the job following the instructions in the `README.md` file
* The Job should run successfully. You can also check the db for fun!

#### What are the relevant tickets?
- [PLAT-894](https://airqoteam.atlassian.net/browse/PLAT-894)

### CODE REVIEW

**Review by Baalmart — COMMENTED** [review]
Followed the run instructions but getting a few challenges, not sure what I could be missing. See screenshot. @ja-odur 
Screenshot 2021-11-26 at 21 02 13

**Comment by ja-odur** [comment]
> Followed the run instructions but getting a few challenges, not sure what I could be missing. See screenshot. @ja-odur Screenshot 2021-11-26 at 21 02 13

@Baalmart try using the new .env. New link in the description section

**Review by NoahNsimbe — APPROVED** [review]
LGTM!

**Review by Baalmart — APPROVED** [review]
LGTM

**Pull request merged**
