### PR TITLE
Refactor CI/CD files

### PR DESCRIPTION
**Pull request by 123MwanjeMike**
# Hotfix

**_WHAT DOES THIS PR DO?_**
- Removes CI/CD files that are no longer in use

**_WHAT JIRA STORY/TASK IS RELATED TO THIS PR?_**
- n/a

**_WHAT IS THE LINK TO THE PR BRANCH_**
- [refactor-cicd-files](https://github.com/airqo-platform/AirQo-api/tree/refactor-cicd-files)

**_HOW DO I TEST OUT THIS PR?_**
- n/a

**_WHICH ENDPOINTS SHOULD BE READY FOR TESTING?:_** 
- n/a

**_IS THERE ANY JENKINS CONSOLE LINK FOR CODE COVERAGE AND BUILD INFO?_**
- n/a

**_ARE THERE ANY RELATED PRs?_**
- n/a

### CODE REVIEW

**Comment by 123MwanjeMike** [comment]
Should I also remove the Jenkinsfiles? @Baalmart @NoahNsimbe

**Comment by NoahNsimbe** [comment]
> Should I also remove the Jenkinsfiles? @Baalmart @NoahNsimbe

I think let's leave them. We might use Jenkins in the future

**Comment by 123MwanjeMike** [comment]
> > Should I also remove the Jenkinsfiles? @Baalmart @NoahNsimbe
> 
> I think let's leave them. We might use Jenkins in the future @123MwanjeMike

Thanks @NoahNsimbe

**Review by Baalmart — APPROVED** [review]
LGTM

**Pull request merged**
