### PR TITLE
move to production

### PR DESCRIPTION
**Pull request by Baalmart**
# move to production

**_WHAT DOES THIS PR DO?_**

- [x] changes the data type for the Aspects field from String to Number
- [x] When querying site details, ensures that createdAt field is returned for the attached Devices and AirQlouds of that site.
- [ ] Some changes in data-mgt/python? @NoahNsimbe

### CODE REVIEW

**Review by Baalmart — COMMENTED** [review]
@123MwanjeMike , I do hope that our checks for the **ENVs** are all good for any changed micros in this migration? cc: @NoahNsimbe

**Comment by NoahNsimbe** [comment]
> @123MwanjeMike , I do hope that our checks for the **ENVs** are all good for any changed micros in this migration? cc: @NoahNsimbe

@Baalmart could you add a list of the changes you are making to production. Refer to the PR below
https://github.com/airqo-platform/AirQo-api/pull/793

**Comment by Baalmart** [comment]
> > @123MwanjeMike , I do hope that our checks for the **ENVs** are all good for any changed micros in this migration? cc: @NoahNsimbe
> 
> @Baalmart could you add a list of the changes you are making to production. Refer to the PR below #793

Done @NoahNsimbe , please check and also add the details for the changes in the data-mgt/python micro that you made. Thanks!

**Comment by NoahNsimbe** [comment]
> #793

@Baalmart could we add links

**Pull request merged**
