### PR TITLE
upgrade mongos backup disk size

### PR DESCRIPTION
**Pull request by 123MwanjeMike**
**_WHAT DOES THIS PR DO?_**
- [Set mongos-router-0 disk to medium size](https://github.com/airqo-platform/AirQo-api/pull/1608/commits/38ea8759dee32a20c21541d76773262041b16d67)(50GB)

**_WHAT ISSUES ARE RELATED TO THIS PR?_**

- Jira cards
    - []()
- GitHub issues
    - Closes #<enter GitHub issue number here>

**_HOW DO I TEST OUT THIS PR?_**

**_WHICH ENDPOINTS SHOULD BE READY FOR TESTING?:_** 

**_IS THERE ANY JENKINS CONSOLE LINK FOR CODE COVERAGE AND BUILD INFO?_**

**_ARE THERE ANY RELATED PRs?_**

### CODE REVIEW

**Review by Baalmart — COMMENTED** [review]
Thanks @123MwanjeMike , how does this look like from a cost optimisation stand point?

**Comment by 123MwanjeMike** [comment]
> Thanks @123MwanjeMike , how does this look like from a cost optimisation stand point?

Hi @Baalmart 
This will cost us an extra of about $4. We can however have it optimized as shared in out recent call.

**Comment by Baalmart** [comment]
Hi @123MwanjeMike , this PR has merge conflicts

**Comment by Baalmart** [comment]
> Hi @123MwanjeMike , this PR has merge conflicts

please ignore, looks like you have resolved the issues

**Comment by Baalmart** [comment]
> > Thanks @123MwanjeMike , how does this look like from a cost optimisation stand point?
> 
> Hi @Baalmart This will cost us an extra of about $4. We can however have it optimized as shared in out recent call.

Thanks @123MwanjeMike , I have also left a related comment (thread) in the #infrastructure Slack channel about **Automatically Deleting Time Series Documents**.

Thanks!

**Comment by 123MwanjeMike** [comment]
Hi @Baalmart 
I've downgraded the disk size back to 50GB as requested.

**Review by Baalmart — APPROVED** [review]
Hi @123MwanjeMike .....

**Pull request merged**
