### PR TITLE
[GP-MODEL] Kabale Spatial Model

### PR DESCRIPTION
**Pull request by danielogen**
**_WHAT DOES THIS PR DO?_**
- Creates customized spatial model for kabale AirQloud

**_WHAT ISSUES ARE RELATED TO THIS PR?_**

- Jira cards
    - [DP-300]
- GitHub issues
    - None

**_HOW DO I TEST OUT THIS PR?_**
- Set up a python environment
- Run `python main.py`
- View the result in MongoDB

**_WHICH ENDPOINTS SHOULD BE READY FOR TESTING?:_** 
- https://staging-platform.airqo.net/api/v1/devices/airqlouds?tenant=airqo&name=kabale

**_IS THERE ANY JENKINS CONSOLE LINK FOR CODE COVERAGE AND BUILD INFO?_**
- N/A

**_ARE THERE ANY RELATED PRs?_**
- N/A

[DP-300]: https://airqoteam.atlassian.net/browse/DP-300?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by wabinyai — APPROVED** [review]
Looks ok

**Comment by 123MwanjeMike** [comment]
Hi team.
Please review this PR so that it may get merged.
It has gotten stale and yet I see it already has an approval.
cc @danielogen

**Comment by 123MwanjeMike** [comment]
This PR's branch has been stale for 3 months.
Please consider deleting it if it's obsolete to minimise the size of the repo clone.
cc @danielogen

**Review by wabinyai — APPROVED** [review]
Looks good

**Review by uman95 — APPROVED** [review]
Looks good.

**Comment by sserurich** [comment]
@uman95 , kindly resolve the conflicts and push again, there might have been changes from recent staging that are not captured in this branch since it's been a while.

**Pull request closed without merging**
