### PR TITLE
set up the pagination support for the GET Events endpoint

### PR DESCRIPTION
**Pull request by Baalmart**
# set up the pagination support for the GET Events endpoint

**_WHAT DOES THIS PR DO?_**

- [x] set up the pagination support for the GET Events endpoint
- [x] Refactors many sections of  the `Create Event `use case to accommodate the pagination support

**_WHAT JIRA STORY/TASK IS RELATED TO THIS PR?_**
[PLAT-865]

**_WHAT IS THE LINK TO THE PR BRANCH_**
https://github.com/airqo-platform/AirQo-api/tree/ft-create-event-PLAT-865

**_HOW DO I TEST OUT THIS PR?_**
README, staging
Please ensure that you update your` .env` accordingly. Just updated the [online version](https://docs.google.com/document/d/1R0ux6i4WaK-NssVQE_9IcTxfUs3ZYIUhSP1Aa7s_hqg/edit?usp=sharing).

**_WHICH ENDPOINTS SHOULD BE READY FOR TESTING?:_** 

- [x] [GET Events](https://app.gitbook.com/o/-MCogOVGQqjUharJKchL/s/-MKqyQkcfs54GYi-q96G/device-registry/events#get-events)
- [x] [Get devices count](https://app.gitbook.com/o/-MCogOVGQqjUharJKchL/s/-MKqyQkcfs54GYi-q96G/device-registry/create-devices#get-the-count-of-devices-on-the-network)

**_IS THERE ANY JENKINS CONSOLE LINK FOR CODE COVERAGE AND BUILD INFO?_**
N/A

**_SCREENSHOTS?_**
Screenshot 2021-11-29 at 21 41 26

[PLAT-865]: https://airqoteam.atlassian.net/browse/PLAT-865?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by NoahNsimbe — COMMENTED** [review]
@Baalmart based on the screenshot you shared, could we stick to the original structure of the response body and just add the meta body for the sake of backward compatibility. The final response body would be 
Screenshot 2021-11-30 at 12 10 35

**Review by NoahNsimbe — COMMENTED** [review]
@Baalmart, I get this error
Screenshot 2021-11-30 at 12 06 49

**Comment by Baalmart** [comment]
> @Baalmart based on the screenshot you shared, could we stick to the original structure of the response body for the sake of backward compatibility and just add the meta body. The final response body would be Screenshot 2021-11-30 at 12 10 35

Thanks for this suggestion, let me attempt to effect it. @NoahNsimbe

**Comment by Baalmart** [comment]
> @Baalmart, I get this error Screenshot 2021-11-30 at 12 06 49

I have failed to reproduce this error. Perhaps you could share some console logs also. @NoahNsimbe

**Comment by Baalmart** [comment]
> > @Baalmart based on the screenshot you shared, could we stick to the original structure of the response body for the sake of backward compatibility and just add the meta body. The final response body would be Screenshot 2021-11-30 at 12 10 35
> 
> Thanks for this suggestion, let me attempt to effect it. @NoahNsimbe

This has been resolved. @NoahNsimbe see screenshot below:
Screenshot 2021-12-01 at 13 27 21

**Comment by NoahNsimbe** [comment]
> > @Baalmart, I get this error Screenshot 2021-11-30 at 12 06 49
> 
> I have failed to reproduce this error. Perhaps you could share some console logs also. @NoahNsimbe

Screenshot 2021-12-01 at 14 07 09
@Baalmart

**Comment by NoahNsimbe** [comment]
Could we stick to the default number of records returned for now. @Baalmart

**Pull request merged**
