### PR TITLE
[chore] Github template to formalise our Pull Requests

### PR DESCRIPTION
**Pull request by Baalmart**
- What does this PR do?
This PR introduces a Github template that is supposed to automatically spins up whenever anyone wants to create a new PR.

- What JIRA task is related to this PR?
There is no JIRA link for this.

### CODE REVIEW

**Review by lilly-muyama — COMMENTED** [review]
Can we first understand what each of these mean?

**Comment by danielogen** [comment]
Is there a way of testing this PR?

**Review by danielogen — APPROVED** [review]
Looking good to me. To view the `.md` content, go to `chore-pr-template` then to `.github` folder and chick the `.md` file. All from GitHub.
Screenshot 2020-08-31 at 17 01 12

**Comment by Baalmart** [comment]
> Can we first understand what each of these mean?

I think majority of them are relatable to what we have been using already.
New things are about [E2E tests](https://www.katalon.com/resources-center/blog/end-to-end-e2e-testing/) and writing unit tests (Test Driven Development) which we have not been heavily involved in....we are gravitating towards that.

**Pull request merged**
