### PR TITLE
[Device Registry] Features, Enhancements and Bugs

### PR DESCRIPTION
**Pull request by Baalmart**
# Features, Enhancements and Bugs

**_WHAT DOES THIS PR DO?_**

- [x] Creates a new endpoint for getting device measurements 

- [ ] Ensure that the indexed fields do not store/retrieve duplicate values

- [ ] Deal with DB query optimisations. 

- [x] Updates the paths for all endpoints related to Events 

- [x] Fix a runtime error with Device Deploy/Recall/Maintain - "sometimes, devices could be deployed successfully before recall"

- [x] Introduces caching on the GET Events endpoint. 

- [x] Adds a new CRUD endpoints for location activities (deploy, maintain and recall). 

- [ ] For maintenance, if date is null, then use the next maintenance function. Otherwise, use the one provided by the user. 

- [x] For deployment, the return response including the device details. Should also include the ID of the device.

**_WHAT JIRA STORY/TASK IS RELATED TO THIS PR?_**
[PLAT-242](https://airqoteam.atlassian.net/browse/PLAT-242?atlOrigin=eyJpIjoiZWEwZjhjYjVkMTNiNGJkNTkxODM3ZTIyNzE0NmFkMzciLCJwIjoiaiJ9)

**_WHAT IS THE LINK TO THE PR BRANCH_**
https://github.com/airqo-platform/AirQo-api/compare/staging...hotfix-event-timestamps

**_HOW DO I TEST OUT THIS PR?_**
`cd AirQo-api/src/device-registry`
`npm install`
In another shell tab, start your Redis server accordingly (run `redis-server` for Linux)
In your `.env `file, momentarily change the `REDIS_SERVER` to point `127.0.0.1`
Remember to undo this change at the end of it all.

> For Linux

`npm run stage-mac`

> For Windows

`npm run stage-pc`

**_WHICH ENDPOINTS SHOULD BE READY FOR TESTING?:_** 

- [x] get Events [GET]: http://localhost:3000/api/v1/devices/events?comp={COMPONENT_NAME}&device={DEVICE_NAME}&tenant={TENANT}

- [x] Add Events [POST]: http://localhost:3000/api/v1/devices/events/add?device=aq_100&component=aq_100_s2_pm2_5&tenant=airqo 

- [x] Add Events in Bulk [POST]: http://localhost:3000/api/v1/devices/events/add/bulk?device=aq_100&component=aq_100_s2_pm2_5&tenant=airqo 

- [x] Push One Event [POST]: http://localhost:3000/api/v1/devices/events/push/one?tenant=airqo
Use the write Key for any of the test devices: aq_501 or aq_601 while at it. 

- [x] Push Many Events [POST]: http://localhost:3000/api/v1/devices/events/push?tenant=airqo
Use the write Key for any of the test devices: aq_501 or aq_601 while at it.  

- [x] Update an activity log [PUT]: http://localhost:3000/api/v1/devices/ts/activity/update?tenant=airqo&id={OBJECT_ID} 

- [x] Delete an activity log [DELETE]: http://localhost:3000/api/v1/devices/ts/activity/delete?tenant=airqo&id={OBJECT_ID} 

- [x] List Logs [GET]: http://localhost:3000/api/v1/devices/ts/activity?tenant=airqo&device={DEVICE_NAME}

 **_SCREENSHOTS_**

- Update log
image

- Add Events in Bulk
image

- Push One Event
image

- Push Many Events
image

- Add Events
image

- Updated Activity Responses to include Updated Device Details
image

- List logs
image

**_IS THERE ANY JENKINS CONSOLE LINK FOR CODE COVERAGE AND BUILD INFO?_**
N/A

**_ARE THERE ANY RELATED PRs?_**
N/A

### CODE REVIEW

**Review by lilly-muyama — COMMENTED** [review]
- When a parameter is missing, can we have error messages that correspond to the issue. E.g when the tenant id is missing, the message says `unable to find component..`. This should also be done for when the device name or component name is missing.

- It doesn't seem to work for KCCA devices

- Since this endpoint gets data from the `events` collection, it is hard to review it conclusively since it has data for less than 10 devices and very few records, in some cases, only one for a component. My suggestion is the problems with streaming data into the `events` table should be addressed first before this PR is merged.

**Comment by Baalmart** [comment]
Thanks @lilly-muyama 

> * When a parameter is missing, can we have error messages that correspond to the issue. E.g when the tenant id is missing, the message says `unable to find component..`. This should also be done for when the device name or component name is missing.

Let me review this asap - shall share a new commit asap

> * It doesn't seem to work for KCCA devices

Yeah, kind of. So it works but it takes long. WHY? We need to apply optimisation techniques like indexing and sharding. This definitely needs to be addressed BEFORE we merge this PR. Thanks. :) 


> * Since this endpoint gets data from the `events` collection, it is hard to review it conclusively since that table seems to have data for less than 10 devices and very few records, in some cases, only one for a component. My suggestion is the problems with streaming data into the `events` table should be addressed first before this PR is merged.

- [ ] The current content in the Events table should not be a blocker. WHY? This PR is just about retrieving content from that collection. This PR is not meant to address the effectiveness/performance of the already deployed streaming jobs.  Work on investigating the performance of the streaming jobs is found in a [separate PR](https://github.com/airqo-platform/AirQo-api/pull/171).

- [ ] The records in the Events collection have been increasing with time. KCCA has over 100K records and AirQo now have over 5K records. So you may want to "skip" and examine the latest records.

**Comment by Baalmart** [comment]
- add `events` to the path of the endpoint

**Review by ja-odur — APPROVED** [review]
LGTM

**Review by sserurich — COMMENTED** [review]
The endpoint for adding even values doesn't succeed as shown in attached image. complains of certain required field. Also it could be better if we list the missing fields instead of it being generic in the response.
image

**Comment by sserurich** [comment]
> Hi @sserurich :
> Using the same details in your screenshot, I am unable to reproduce your issue. Please see the screenshot
> image
> 
> > The endpoint for adding even values doesn't succeed as shown in attached image. complains of certain required field. Also it could be better if we list the missing fields instead of it being generic in the response.
> > image

@Baalmart , not sure what I might be missing. @danielogen  had same issue when he tested it out.

**Comment by sserurich** [comment]
Also @Baalmart  on the api for pushing one event, am getting this
image

**Comment by Baalmart** [comment]
Hi @sserurich :
Let us try out the "manual" approach below:
Just switch to staging branch, delete local PR branch, pull PR branch again from origin and then test again.

> Also @Baalmart on the api for pushing one event, am getting this
> image

**Comment by sserurich** [comment]
> Hi @sserurich :
> Let us try out the "manual" approach below:
> Just switch to staging branch, delete local PR branch, pull PR branch again from origin and then test again.
> 
> > Also @Baalmart on the api for pushing one event, am getting this
> > image

alright @Baalmart , will let you know.

**Comment by sserurich** [comment]
> > Hi @sserurich :
> > Let us try out the "manual" approach below:
> > Just switch to staging branch, delete local PR branch, pull PR branch again from origin and then test again.
> > > Also @Baalmart on the api for pushing one event, am getting this
> > > image
> 
> alright @Baalmart , will let you know.

@Baalmart , I did this and was examining everything line by line and observed , I had a typo in uncertaintyValue.. endpoint nows succeeds , thanks 
image

**Comment by sserurich** [comment]
> Hi @sserurich :
> Let us try out the "manual" approach below:
> Just switch to staging branch, delete local PR branch, pull PR branch again from origin and then test again.
> 
> > Also @Baalmart on the api for pushing one event, am getting this
> > image

@Baalmart , even the one for pushing one event has succeeded.  the reason I was getting issue was because "api_key" , I had used it successfully to push multiple events.. but on further inspecting again, I have realized for one event , its "apiKey".. may be the improvement here could be ensuring consistency.

**Review by sserurich — APPROVED** [review]
it works well. there some minor comments of mentioning the actual name of the required fields that are missing incase a request doesn't supply it which can be worked on later.

**Pull request merged**
