### PR TITLE
argo cd k8s manifests

### PR DESCRIPTION
**Pull request by 123MwanjeMike**
**_WHAT DOES THIS PR DO?_**
- Adds argocd manifests for the setup

**_WHAT ISSUES ARE RELATED TO THIS PR?_**
- [PLATOPS-35](https://airqoteam.atlassian.net/browse/PLATOPS-35?atlOrigin=eyJpIjoiOWUzYjRjMDRlZTc1NDBjMDg4Mjk4NzQzZDE1MzhkZTgiLCJwIjoiaiJ9)

**_HOW DO I TEST OUT THIS PR?_**
- Checkout [platform.airqo.net/argocd](https://platform.airqo.net/argocd/applications?syncApps=true)
image

**_WHICH ENDPOINTS SHOULD BE READY FOR TESTING?:_** 
- /argocd

**_IS THERE ANY JENKINS CONSOLE LINK FOR CODE COVERAGE AND BUILD INFO?_**
- n/a

**_ARE THERE ANY RELATED PRs?_**
- n/a

### CODE REVIEW

**Review by Baalmart — COMMENTED** [review]
Hi @123MwanjeMike , could you add some descriptive review comments? Just to act as guidelines? Thanks!

**Comment by 123MwanjeMike** [comment]
Sure thing @Baalmart 
Let me add those.

**Comment by Baalmart** [comment]
Thanks!

**Comment by 123MwanjeMike** [comment]
Hi @Baalmart, I've added [this README](https://github.com/airqo-platform/AirQo-api/blob/cdc01f366fc2b58885cd9bcd688bffa1d547fc5f/k8s/argo-cd/README.md) as a detailed guide of this ArgoCD installation.
It has basically talks about everything done in this PR

**Comment by Baalmart** [comment]
> this README

this is brilliant @123MwanjeMike , many thanks!

**Review by Baalmart — APPROVED** [review]
Hi @123MwanjeMike , thanks for this! This LGTM

Just a reminder that a few painless review comments on each changed file help to make the review process smoother. Adding review comments helps the reviewers catch issues easily and it is another smooth way of "marketing" a PR since it makes life easier for the reviewers.

All in all, you lose nothing by adding PR review comments. :)

**Review by Baalmart — COMMENTED** [review]
And irrespective of the presence of a very detailed README, review comments still come in handy since you cannot expect your usually BUSY. reviewers to read through all the content of a README file. @123MwanjeMike

**Comment by 123MwanjeMike** [comment]
Thank you @Baalmart for the remainder.
This has been noted and will  e effected in any new PRs

**Pull request merged**
