### PR TITLE
Move to production

### PR DESCRIPTION
**Pull request by NoahNsimbe**
**_Summary of changes_**

### @123MwanjeMike 
- [x] #1111
- [x] https://github.com/airqo-platform/AirQo-api/pull/1121

### @Baalmart 
- [ ] https://github.com/airqo-platform/AirQo-api/pull/1101
- [ ] https://github.com/airqo-platform/AirQo-api/pull/1122

### @NoahNsimbe 
- [x] #1113 
- [x] #1112
- [x] https://github.com/airqo-platform/AirQo-api/pull/1117
- [x] https://github.com/airqo-platform/AirQo-api/pull/1118
- [x] https://github.com/airqo-platform/AirQo-api/pull/1115
- [x] https://github.com/airqo-platform/AirQo-api/pull/1114

### CODE REVIEW

**Review by 123MwanjeMike — APPROVED** [review]

**Comment by 123MwanjeMike** [comment]
Hi @Baalmart 
What are the Redocly Registry checks for?

**Comment by Baalmart** [comment]
Hi @123MwanjeMike I am also not sure. I thought you could be best placed to answer that? I am not working on anything relates to redocly at the moment.

**Comment by 123MwanjeMike** [comment]
> Hi @123MwanjeMike I am also not sure. I thought you could be best placed to answer that? I am not working on anything relates to redocly at the moment.

I didn't add it either. Maybe @NoahNsimbe has some insights, yes?

**Comment by NoahNsimbe** [comment]
> > Hi @123MwanjeMike I am also not sure. I thought you could be best placed to answer that? I am not working on anything relates to redocly at the moment.
> 
> I didn't add it either. Maybe @NoahNsimbe has some insights, yes?

I don't know about it.

**Comment by 123MwanjeMike** [comment]
> > > Hi @123MwanjeMike I am also not sure. I thought you could be best placed to answer that? I am not working on anything relates to redocly at the moment.
> > 
> > 
> > I didn't add it either. Maybe @NoahNsimbe has some insights, yes?
> 
> I don't know about it.

We might need to investigate how this was added @Baalmart especially since none of us did, and have it removed if it's not being used.

**Comment by Baalmart** [comment]
Alright! I will also cc @BenjaminSsempala just in case he might also have some insights. Thanks!

I will also continue to investigate on the side. Thanks @123MwanjeMike !

**Review by Codebmk — APPROVED** [review]

**Pull request merged**
