### PR TITLE
chore: data & env segregation in device monitoring microservice

### PR DESCRIPTION
**Pull request by danielogen**
- **What does this PR do?**
This PR adds multi-tenancy to the `device-monitoring` microservice.
- **What JIRA task is related to this PR?**
The link to the JIRA board task is [here](https://airqoteam.atlassian.net/browse/PLAT-73).
- **How do I test out this PR?**
Git clone this repo `cd AirQo-api/src/device-monitoring`. 
```
**using docker**
**Production:** `docker build -t prod-device-monitor .` and `docker run -it -p 5555:4001 prod-device-monitor`
**Staging:** `docker build -t stage-device-monitor -f Docker.stage.txt .` and `docker run -it -p 5555:4001 stage-device-monitor`
```

```
**locally**
 Create and activate a python virtual env. Using: `python3 -m venv env`, `source env/bin/activate` and `pip install -r requirements.txt`. Now run `flask run` to test out the points using any REST client of your choice.
```
NB: By default, the `.env` file points to the development DB. You are advised to use docker if you wish to utilize `production` or `staging` DB. In all case checkout out `http://127.0.0.0:<port_number>/health` endpoint to confirm the DB you will be hitting. 

- **Which endpoints should or are ready for testing?**
All endpoints as shown [in this documentation](https://docs.google.com/spreadsheets/d/1-NGTDBtTcIi8Fg2UYSWjcK6geKrZdopz5kxRFsCEMPs/edit#gid=1063367751) You just need to add the tenant parameter to each URL e.g. http://localhost:5555/device/monitor/status?tenant=airqo or `?tenant=kcca`

### CODE REVIEW

**Review by Baalmart — COMMENTED** [review]
Thanks @danielogen 👍 

The following feedback follows the implementations after the [previous feedback](https://github.com/airqo-platform/AirQo-api/pull/149#pullrequestreview-497226485).

- [x] **Get device status summary:** works as expected. Also returns the appropriate error response when one uses the wrong HTTP verb for an endpoint. We could explore returning that error response in JSON rather than HTML. Appropriate response is also returned for wrong organisation which is awesome.

- [x] **Number of devices online/offline:**  returns well for AirQo organisation. As for kcca, returns a 500 error but still in HTML (could be good to maintain JSON format throughout). The same for other non existent orgs (500 error in HTML - internal server error). As for using the wrong HTTP verb in the request, appropriate bad request error response is sent back in HTML - let's explore JSON.

- [x] **list of offline devices:** Endpoint works well for AirQo organisation. Returns appropriate HTML error response for non existent endpoints - we could explore using JSON. Using a wrong HTTP vern returns a server error in HTML - we could explore making this JSON and more informative. 

- [x] **Network Uptime:** Returns 500 server error response (HTML) for non existent tenant. Also returns appropriate error response for missing the tenant query param. Also return appropriate error response (HTML) for wrong HTTP verb used. Could we try changing the HTML to JSON? 

- [x] **List of Online and Offline:** Appropriate error responses (HTML) are returned for both non existent endpoint and wrong tenant ID. Data is returned for airqo organisation which is awesome. We could explore maintaining JSON responses instead of HTML. 

- [x] **List maintenance log:**  Error response (JSON) for non existent tenant is returned - awesome. Error response (HTML) for non existent endpoint is shared too. Error responses (JSON)for non existent tenant and missing tenant are also returned - awesome. Can we explore changing that one HTML response to JSON? 

- [ ] **List maintenance log for a single device:** 

> - Non existent endpoint: Appropriate error response exists in HTML. Consider JSON.
> - Non existent organisation: All good here, informative JSON response returned
> - Missing tenant ID in request: All good here
> - Missing device name: Appropriate HTML response similar is returned - could be more descriptive and in JSON.
> - Incorrect device name: Not handled at all - returns the response for missing tenant ID
> - Response when airqo tenant is provided (with wrong device name): returns response for invalid tenant ID.
> - Response when airqo tenant is provided (with device without maintenance records): returns response for invalid tenant ID/organisation.
> - Response when kcca tenant is provided (wrong device name): returns wrong tenant provided.
> - Response when kcca tenant is provided (correct device name): returns wrong tenant provided.
> - Response when kcca tenant is provided (missing device name): returns wrong org provided in JSON. 

- [ ] **List power type:** 

> - Non existent endpoint: Appropriate error response exists in HTML. Consider JSON.
> - Non existent organisation: All good here, informative JSON response returned
> - Missing tenant ID in request: All good here
> - Using airqo as tenant ID: All good here.
> - Using KCCA as tenant ID: returns data but no power types - I guess we just need to do some data entry here.

- [ ]  **Device Uptime:** 

> - Non existent endpoint: Appropriate error response exists in HTML. Consider JSON.
> - Non existent organisation (non existent channel ID) and vice versa: 404 returned in HTML showing URL not found. Consider using JSON and making response more informative.
> - Existing organisation and existing channel ID (without data): All good here. Appropriate JSON response indicating missing data.
> - Missing tenant ID in request: All good here
> - Using airqo as tenant ID: All good here.
> - Using KCCA as tenant ID: Get 500 server error response in HTML. Consider JSON and more descriptive of the cause of the server error. 

- [ ] **Battery Voltage  graph data:** 

> - Non existent endpoint: Appropriate error response exists in HTML. Consider JSON.
> - Non existent organisation (non existent channel ID) and vice versa: 500 returned in HTML showing internal server error. Consider using JSON and making response more informative.
> - Non existent organisation (existing channel ID): 500 returned in HTML showing internal server error. Consider using JSON and making response more informative.
> - Existing organisation and existing channel ID (without data):  500 returned in HTML showing internal server error. Consider using JSON and making response more informative.
> - Missing tenant ID in request: All good here
> - Using airqo as tenant ID (with channel ID that has data): All good here.
> - Using KCCA as tenant ID (with random channel ID provided): Get 500 server error response in HTML. Consider JSON and more descriptive of the cause of the server error. 

- [ ] **Sensor Correlation graph data:** 

> - Non existent endpoint: Appropriate error response exists in HTML. Consider JSON.
> - Non existent organisation (non existent channel ID) and vice versa: 500 returned in HTML showing internal server error. Consider using JSON and making response more informative.
> - Non existent organisation (existing channel ID): 500 returned in HTML showing internal server error. Consider using JSON and making response more informative.
> - Existing organisation and existing channel ID (without data):  500 returned in HTML showing internal server error. Consider using JSON and making response more informative.
> - Existing organisation and existing channel ID (with data):  All good here, returns the data in JSON format.
> - Missing tenant ID in request: All good here
> - Using airqo as tenant ID (with channel ID that has data): All good here.
> - Using KCCA as tenant ID (with random channel ID provided): Get 500 server error response in HTML. Consider JSON and more descriptive of the cause of the server error.

**Review by lilly-muyama — COMMENTED** [review]
Testing the second endpoint in the api doumentation only returns a response when tenant=airqo otherwise for anything else, this error appears:
Capture

**Comment by danielogen** [comment]
> Testing the second endpoint in the api doumentation only returns a response when tenant=airqo otherwise for anything else, this error appears:
> 
> Capture
> 
> 

Thanks @lilly-muyama for the feedback. I believe this is due to absence of data. Let me add an exception clause. Where you able to test the other endpoints & env separation? Thanks again!!

**Review by ja-odur — COMMENTED** [review]
Great work all the endpoints but 2 have some issues;
1)/api/v1/device/monitor/status/latest?tenant=kcca
2) /api/v1/monitor/devices/online_offline?tenant=kcca
with tenancy set to kcca for both endpoints. I get an internal server error

**Comment by danielogen** [comment]
> Great work all the endpoints but 2 have some issues;
> 1)/api/v1/device/monitor/status/latest?tenant=kcca
> 2) /api/v1/monitor/devices/online_offline?tenant=kcca
> with tenancy set to kcca for both endpoints. I get an internal server error

Thanks @ja-odur. I have resolved the error. Kindly re-review when you get some time.

**Comment by danielogen** [comment]
Hi @lilly-muyama & @Baalmart, I have resolved the issues raised in the PR review. Kindly re-review when you get time. Thank and happy independence

**Comment by Baalmart** [comment]
> Thanks @danielogen 👍
> 
> The following feedback follows the implementations after the [previous feedback](https://github.com/airqo-platform/AirQo-api/pull/149#pullrequestreview-497226485).
> 
> * [x]  **Get device status summary:** works as expected. Also returns the appropriate error response when one uses the wrong HTTP verb for an endpoint. We could explore returning that error response in JSON rather than HTML. Appropriate response is also returned for wrong organisation which is awesome.
> * [x]  **Number of devices online/offline:**  returns well for AirQo organisation. As for kcca, returns a 500 error but still in HTML (could be good to maintain JSON format throughout). The same for other non existent orgs (500 error in HTML - internal server error). As for using the wrong HTTP verb in the request, appropriate bad request error response is sent back in HTML - let's explore JSON.
> * [x]  **list of offline devices:** Endpoint works well for AirQo organisation. Returns appropriate HTML error response for non existent endpoints - we could explore using JSON. Using a wrong HTTP vern returns a server error in HTML - we could explore making this JSON and more informative.
> * [x]  **Network Uptime:** Returns 500 server error response (HTML) for non existent tenant. Also returns appropriate error response for missing the tenant query param. Also return appropriate error response (HTML) for wrong HTTP verb used. Could we try changing the HTML to JSON?
> * [x]  **List of Online and Offline:** Appropriate error responses (HTML) are returned for both non existent endpoint and wrong tenant ID. Data is returned for airqo organisation which is awesome. We could explore maintaining JSON responses instead of HTML.
> * [x]  **List maintenance log:**  Error response (JSON) for non existent tenant is returned - awesome. Error response (HTML) for non existent endpoint is shared too. Error responses (JSON)for non existent tenant and missing tenant are also returned - awesome. Can we explore changing that one HTML response to JSON?
> * [x]  **List maintenance log for a single device:**
> 
> > * Non existent endpoint: Appropriate error response exists in HTML. Consider JSON.
> > * Non existent organisation: All good here, informative JSON response returned
> > * Missing tenant ID in request: All good here
> > * Missing device name: Appropriate HTML response similar is returned - could be more descriptive and in JSON.
> > * Incorrect device name: Not handled at all - returns the response for missing tenant ID
> > * Response when airqo tenant is provided (with wrong device name): returns response for invalid tenant ID.
> > * Response when airqo tenant is provided (with device without maintenance records): returns response for invalid tenant ID/organisation.
> > * Response when kcca tenant is provided (wrong device name): returns wrong tenant provided.
> > * Response when kcca tenant is provided (correct device name): returns wrong tenant provided.
> > * Response when kcca tenant is provided (missing device name): returns wrong org provided in JSON.
> 
> * [x]  **List power type:**
> 
> > * Non existent endpoint: Appropriate error response exists in HTML. Consider JSON.
> > * Non existent organisation: All good here, informative JSON response returned
> > * Missing tenant ID in request: All good here
> > * Using airqo as tenant ID: All good here.
> > * Using KCCA as tenant ID: returns data but no power types - I guess we just need to do some data entry here.
> 
> * [ ]   **Device Uptime:**
> 
> > * Non existent endpoint: Appropriate error response exists in HTML. Consider JSON.
> > * Non existent organisation (non existent channel ID) and vice versa: 404 returned in HTML showing URL not found. Consider using JSON and making response more informative.
> > * Existing organisation and existing channel ID (without data): All good here. Appropriate JSON response indicating missing data.
> > * Missing tenant ID in request: All good here
> > * Using airqo as tenant ID: All good here.
> > * Using KCCA as tenant ID: Get 500 server error response in HTML. Consider JSON and more descriptive of the cause of the server error.
> 
> * [ ]  **Battery Voltage  graph data:**
> 
> > * Non existent endpoint: Appropriate error response exists in HTML. Consider JSON.
> > * Non existent organisation (non existent channel ID) and vice versa: 500 returned in HTML showing internal server error. Consider using JSON and making response more informative.
> > * Non existent organisation (existing channel ID): 500 returned in HTML showing internal server error. Consider using JSON and making response more informative.
> > * Existing organisation and existing channel ID (without data):  500 returned in HTML showing internal server error. Consider using JSON and making response more informative.
> > * Missing tenant ID in request: All good here
> > * Using airqo as tenant ID (with channel ID that has data): All good here.
> > * Using KCCA as tenant ID (with random channel ID provided): Get 500 server error response in HTML. Consider JSON and more descriptive of the cause of the server error.
> 
> * [ ]  **Sensor Correlation graph data:**
> 
> > * Non existent endpoint: Appropriate error response exists in HTML. Consider JSON.
> > * Non existent organisation (non existent channel ID) and vice versa: 500 returned in HTML showing internal server error. Consider using JSON and making response more informative.
> > * Non existent organisation (existing channel ID): 500 returned in HTML showing internal server error. Consider using JSON and making response more informative.
> > * Existing organisation and existing channel ID (without data):  500 returned in HTML showing internal server error. Consider using JSON and making response more informative.
> > * Existing organisation and existing channel ID (with data):  All good here, returns the data in JSON format.
> > * Missing tenant ID in request: All good here
> > * Using airqo as tenant ID (with channel ID that has data): All good here.
> > * Using KCCA as tenant ID (with random channel ID provided): Get 500 server error response in HTML. Consider JSON and more descriptive of the cause of the server error.

- For device uptime of KCCA
image

- For channel ID that does not exist (battery voltage)
image

- Non existent channel ID (Sensor correlation Graph data)
image

- For endpoints that need channel ID as params in the request- they  expect numbers - if we use the same for KCCA which does not have channel IDs, it has alphanumeric device names - it will bring 500 server errors. We could use device names instead of channel IDs for conistency or allow different TYPES in the channel ID field? See screenshot
image

**Review by Baalmart — APPROVED** [review]
Good

**Pull request merged**
