### PR TITLE
renaming location registry to site registry

### PR DESCRIPTION
**Pull request by Baalmart**
# Chore

**_WHAT DOES THIS PR DO?_**
Just renames location registry to site registry. 

**_WHAT JIRA STORY/TASK IS RELATED TO THIS PR?_**
N/A

**_WHAT IS THE LINK TO THE PR BRANCH_**
https://github.com/airqo-platform/AirQo-api/tree/rename-loc-registry

**_HOW DO I TEST OUT THIS PR?_**
Just test out all endpoints for location registry.

**_WHICH ENDPOINTS SHOULD BE READY FOR TESTING?:_** 
ALL as specified in the [API documentations [the location-registry sheet]](https://docs.google.com/spreadsheets/d/1-NGTDBtTcIi8Fg2UYSWjcK6geKrZdopz5kxRFsCEMPs/edit#gid=897606332)

**_IS THERE ANY JENKINS CONSOLE LINK FOR CODE COVERAGE AND BUILD INFO?_**
N/A

**_ARE THERE ANY RELATED PRs?_**
N/A

### CODE REVIEW

**Review by ja-odur — APPROVED** [review]
LGTM

**Review by danielogen — APPROVED** [review]
LGTM - just a quick question, are we going to rename the endpoints as well?

**Comment by danielogen** [comment]
> LGTM - just a quick question, are we going to rename the endpoints as well?

Ignore me - I've seen it in another PR. Thanks!

**Comment by Baalmart** [comment]
> LGTM - just a quick question, are we going to rename the endpoints as well?

That should be the logical next step, I guess. Thanks. Let me make it a "Feature" Request here.

**Pull request merged**
