### PR TITLE
Hotfix for reset password

### PR DESCRIPTION
**Pull request by Baalmart**
# Hotfix

**_WHAT DOES THIS PR DO?_**

- [ ] Updates the ports fronted urls for the reset password use case 

- [ ] Introduces multi-tenancy on the frontend url for reset password - using query parameters

**_WHAT JIRA STORY/TASK IS RELATED TO THIS PR?_**
N/A

**_WHAT IS THE LINK TO THE PR BRANCH_**
https://github.com/airqo-platform/AirQo-api/tree/hotfix-reset-password

**_HOW DO I TEST OUT THIS PR?_**
cd AirQo-api/src/auth-service
npm install

> for MAC

npm run dev-mac

> for Windows OS

npm run dev-pc

**_WHICH ENDPOINTS SHOULD BE READY FOR TESTING?:_** 

- [ ] forgot password: http://localhost:3000/api/v1/users/forgotPassword?tenant={ORGANISATION} [POST]
{"email":"{EMAIL ADDRESS}"}
- [ ] reset password: http://localhost:3000/api/v1/users/reset/you?resetPasswordToken={token}&tenant={ORGANISATION} [GET]

**_IS THERE ANY JENKINS CONSOLE LINK FOR CODE COVERAGE AND BUILD INFO?_**
N/A

**_ARE THERE ANY RELATED PRs?_**
There is a [frontend PR](https://github.com/airqo-platform/AirQo-frontend/pull/186) related to this.

### CODE REVIEW

**Review by danielogen — COMMENTED** [review]
Hi @Baalmart ;  I'm getting the error below. Maybe am doing something wrong?


Screenshot 2021-02-09 at 14 05 23

**Review by Priscilla-AL — COMMENTED** [review]
Hi Martin, am getting the same error as Daniel.

**Review by sserurich — COMMENTED** [review]
@Baalmart , I have pulled the latest branch and seems am still missing something aswell.
image

**Review by Priscilla-AL — COMMENTED** [review]
@Baalmart '../utils/errors' does not exist on the remote branch either

**Comment by danielogen** [comment]
> Hi @Baalmart ; I'm getting the error below. Maybe am doing something wrong?
> 
> Screenshot 2021-02-09 at 14 05 23

Seems the `errors.js` does not exit on the remote branch either. see this link: https://github.com/airqo-platform/AirQo-api/tree/hotfix-reset-password/src/auth-service/utils. Thanks

**Comment by ja-odur** [comment]
> > Hi @Baalmart ; I'm getting the error below. Maybe am doing something wrong?
> > Screenshot 2021-02-09 at 14 05 23
> 
> Seems the `errors.js` does not exit on the remote branch either. see this link: https://github.com/airqo-platform/AirQo-api/tree/hotfix-reset-password/src/auth-service/utils. Thanks

I got the same error too

**Comment by Baalmart** [comment]
Should be fine now, had "silenced" some untracked files in my vscode recently, that was the problem.
cc: @Priscilla-AL @lilly-muyama @sserurich 

> > > Hi @Baalmart ; I'm getting the error below. Maybe am doing something wrong?
> > > Screenshot 2021-02-09 at 14 05 23
> > 
> > 
> > Seems the `errors.js` does not exit on the remote branch either. see this link: https://github.com/airqo-platform/AirQo-api/tree/hotfix-reset-password/src/auth-service/utils. Thanks
> 
> I got the same error too

**Comment by danielogen** [comment]
> Should be fine now, had "silenced" some untracked files in my vscode recently, that was the problem.
> cc: @Priscilla-AL @lilly-muyama @sserurich
> 
> > > > Hi @Baalmart ; I'm getting the error below. Maybe am doing something wrong?
> > > > Screenshot 2021-02-09 at 14 05 23
> > > 
> > > 
> > > Seems the `errors.js` does not exit on the remote branch either. see this link: https://github.com/airqo-platform/AirQo-api/tree/hotfix-reset-password/src/auth-service/utils. Thanks
> > 
> > 
> > I got the same error too

Thanks @Baalmart ...things are working well now.

**Review by danielogen — APPROVED** [review]
working well as expected

**Review by ja-odur — APPROVED** [review]
LGTM

**Pull request merged**
