### PR TITLE
add an additional sensor (field) in gen 5 devices

### PR DESCRIPTION
**Pull request by Baalmart**
# include undefined sensor for recent Gen 5 devices

**_WHAT DOES THIS PR DO?_**
Defines the `undefined` sensor for recent Gen 5 devices whenever one queries the recent endpoint of data management service.

**_WHAT JIRA STORY/TASK IS RELATED TO THIS PR?_**
N/A

**_WHAT IS THE LINK TO THE PR BRANCH_**
https://github.com/airqo-platform/AirQo-api/tree/hotfix-extra-field

**_HOW DO I TEST OUT THIS PR?_**
`cd AirQo-api/src/data-mgt/node`
`npm install`
`npm run stage-mac `for Linux OR `npm run stage-pc` for Windows

**_WHICH ENDPOINTS SHOULD BE READY FOR TESTING?:_** 
The one for getting the most recent Events (descriptive) as described here: https://docs.airqo.net/airqo-platform-api/data-management#get-last-entry-descriptive

Look out for Gen 5 devices accordingly as you are testing this out, you will recognise that they have an additional field/sensor names _externalAltitude_

image

**_IS THERE ANY JENKINS CONSOLE LINK FOR CODE COVERAGE AND BUILD INFO?_**
N/A

**_ARE THERE ANY RELATED PRs?_**
N/A

### CODE REVIEW

**Review by danielogen — APPROVED** [review]
Working well on my side. Neat and nice!

**Review by Priscilla-AL — APPROVED** [review]
works as expected.

**Review by Priscilla-AL — COMMENTED** [review]
we could consider an appropriate response for devices that are not returning values . Currently the message I get is error -1

**Comment by Baalmart** [comment]
> we could consider an appropriate response for devices that are not returning values . Currently the message I get is error -1

Good point, let me create a new issue for it.

**Pull request merged**
